###################################################################

# Created by write_sdc on Fri Mar  4 20:02:42 2022

###################################################################
set sdc_version 2.0

set_units -time ns -resistance MOhm -capacitance fF -voltage V -current mA
create_clock [get_ports clk]  -name clk -period 4 -waveform {0 2}
group_path -name input_group  -from [list [get_ports {din[1]}] [get_ports {din[2]}] [get_ports {din[3]}]    \
[get_ports {din[4]}] [get_ports {din[5]}] [get_ports {din[6]}] [get_ports      \
{din[7]}] [get_ports {din[8]}] [get_ports {din[9]}] [get_ports {din[10]}]      \
[get_ports {din[11]}] [get_ports {din[12]}] [get_ports {din[13]}] [get_ports   \
{din[14]}] [get_ports {din[15]}] [get_ports {din[16]}] [get_ports {din[17]}]   \
[get_ports {din[18]}] [get_ports {din[19]}] [get_ports {din[20]}] [get_ports   \
{din[21]}] [get_ports {din[22]}] [get_ports {din[23]}] [get_ports {din[24]}]   \
[get_ports {din[25]}] [get_ports {din[26]}] [get_ports {din[27]}] [get_ports   \
{din[28]}] [get_ports {din[29]}] [get_ports {din[30]}] [get_ports {din[31]}]   \
[get_ports {din[32]}] [get_ports {din[33]}] [get_ports {din[34]}] [get_ports   \
{din[35]}] [get_ports {din[36]}] [get_ports {din[37]}] [get_ports {din[38]}]   \
[get_ports {din[39]}] [get_ports {din[40]}] [get_ports {din[41]}] [get_ports   \
{din[42]}] [get_ports {din[43]}] [get_ports {din[44]}] [get_ports {din[45]}]   \
[get_ports {din[46]}] [get_ports {din[47]}] [get_ports {din[48]}] [get_ports   \
{din[49]}] [get_ports {din[50]}] [get_ports {din[51]}] [get_ports {din[52]}]   \
[get_ports {din[53]}] [get_ports {din[54]}] [get_ports {din[55]}] [get_ports   \
{din[56]}] [get_ports {din[57]}] [get_ports {din[58]}] [get_ports {din[59]}]   \
[get_ports {din[60]}] [get_ports {din[61]}] [get_ports {din[62]}] [get_ports   \
{din[63]}] [get_ports {din[64]}] [get_ports {key1[1]}] [get_ports {key1[2]}]   \
[get_ports {key1[3]}] [get_ports {key1[4]}] [get_ports {key1[5]}] [get_ports   \
{key1[6]}] [get_ports {key1[7]}] [get_ports {key1[9]}] [get_ports {key1[10]}]  \
[get_ports {key1[11]}] [get_ports {key1[12]}] [get_ports {key1[13]}]           \
[get_ports {key1[14]}] [get_ports {key1[15]}] [get_ports {key1[17]}]           \
[get_ports {key1[18]}] [get_ports {key1[19]}] [get_ports {key1[20]}]           \
[get_ports {key1[21]}] [get_ports {key1[22]}] [get_ports {key1[23]}]           \
[get_ports {key1[25]}] [get_ports {key1[26]}] [get_ports {key1[27]}]           \
[get_ports {key1[28]}] [get_ports {key1[29]}] [get_ports {key1[30]}]           \
[get_ports {key1[31]}] [get_ports {key1[33]}] [get_ports {key1[34]}]           \
[get_ports {key1[35]}] [get_ports {key1[36]}] [get_ports {key1[37]}]           \
[get_ports {key1[38]}] [get_ports {key1[39]}] [get_ports {key1[41]}]           \
[get_ports {key1[42]}] [get_ports {key1[43]}] [get_ports {key1[44]}]           \
[get_ports {key1[45]}] [get_ports {key1[46]}] [get_ports {key1[47]}]           \
[get_ports {key1[49]}] [get_ports {key1[50]}] [get_ports {key1[51]}]           \
[get_ports {key1[52]}] [get_ports {key1[53]}] [get_ports {key1[54]}]           \
[get_ports {key1[55]}] [get_ports {key1[57]}] [get_ports {key1[58]}]           \
[get_ports {key1[59]}] [get_ports {key1[60]}] [get_ports {key1[61]}]           \
[get_ports {key1[62]}] [get_ports {key1[63]}] [get_ports {key2[1]}] [get_ports \
{key2[2]}] [get_ports {key2[3]}] [get_ports {key2[4]}] [get_ports {key2[5]}]   \
[get_ports {key2[6]}] [get_ports {key2[7]}] [get_ports {key2[9]}] [get_ports   \
{key2[10]}] [get_ports {key2[11]}] [get_ports {key2[12]}] [get_ports           \
{key2[13]}] [get_ports {key2[14]}] [get_ports {key2[15]}] [get_ports           \
{key2[17]}] [get_ports {key2[18]}] [get_ports {key2[19]}] [get_ports           \
{key2[20]}] [get_ports {key2[21]}] [get_ports {key2[22]}] [get_ports           \
{key2[23]}] [get_ports {key2[25]}] [get_ports {key2[26]}] [get_ports           \
{key2[27]}] [get_ports {key2[28]}] [get_ports {key2[29]}] [get_ports           \
{key2[30]}] [get_ports {key2[31]}] [get_ports {key2[33]}] [get_ports           \
{key2[34]}] [get_ports {key2[35]}] [get_ports {key2[36]}] [get_ports           \
{key2[37]}] [get_ports {key2[38]}] [get_ports {key2[39]}] [get_ports           \
{key2[41]}] [get_ports {key2[42]}] [get_ports {key2[43]}] [get_ports           \
{key2[44]}] [get_ports {key2[45]}] [get_ports {key2[46]}] [get_ports           \
{key2[47]}] [get_ports {key2[49]}] [get_ports {key2[50]}] [get_ports           \
{key2[51]}] [get_ports {key2[52]}] [get_ports {key2[53]}] [get_ports           \
{key2[54]}] [get_ports {key2[55]}] [get_ports {key2[57]}] [get_ports           \
{key2[58]}] [get_ports {key2[59]}] [get_ports {key2[60]}] [get_ports           \
{key2[61]}] [get_ports {key2[62]}] [get_ports {key2[63]}] [get_ports           \
{key3[1]}] [get_ports {key3[2]}] [get_ports {key3[3]}] [get_ports {key3[4]}]   \
[get_ports {key3[5]}] [get_ports {key3[6]}] [get_ports {key3[7]}] [get_ports   \
{key3[9]}] [get_ports {key3[10]}] [get_ports {key3[11]}] [get_ports            \
{key3[12]}] [get_ports {key3[13]}] [get_ports {key3[14]}] [get_ports           \
{key3[15]}] [get_ports {key3[17]}] [get_ports {key3[18]}] [get_ports           \
{key3[19]}] [get_ports {key3[20]}] [get_ports {key3[21]}] [get_ports           \
{key3[22]}] [get_ports {key3[23]}] [get_ports {key3[25]}] [get_ports           \
{key3[26]}] [get_ports {key3[27]}] [get_ports {key3[28]}] [get_ports           \
{key3[29]}] [get_ports {key3[30]}] [get_ports {key3[31]}] [get_ports           \
{key3[33]}] [get_ports {key3[34]}] [get_ports {key3[35]}] [get_ports           \
{key3[36]}] [get_ports {key3[37]}] [get_ports {key3[38]}] [get_ports           \
{key3[39]}] [get_ports {key3[41]}] [get_ports {key3[42]}] [get_ports           \
{key3[43]}] [get_ports {key3[44]}] [get_ports {key3[45]}] [get_ports           \
{key3[46]}] [get_ports {key3[47]}] [get_ports {key3[49]}] [get_ports           \
{key3[50]}] [get_ports {key3[51]}] [get_ports {key3[52]}] [get_ports           \
{key3[53]}] [get_ports {key3[54]}] [get_ports {key3[55]}] [get_ports           \
{key3[57]}] [get_ports {key3[58]}] [get_ports {key3[59]}] [get_ports           \
{key3[60]}] [get_ports {key3[61]}] [get_ports {key3[62]}] [get_ports           \
{key3[63]}] [get_ports drdy] [get_ports krdy] [get_ports enc] [get_ports rstn] \
[get_ports en] [get_ports clk]]
group_path -name output_group  -to [list [get_ports {dout[1]}] [get_ports {dout[2]}] [get_ports {dout[3]}]   \
[get_ports {dout[4]}] [get_ports {dout[5]}] [get_ports {dout[6]}] [get_ports   \
{dout[7]}] [get_ports {dout[8]}] [get_ports {dout[9]}] [get_ports {dout[10]}]  \
[get_ports {dout[11]}] [get_ports {dout[12]}] [get_ports {dout[13]}]           \
[get_ports {dout[14]}] [get_ports {dout[15]}] [get_ports {dout[16]}]           \
[get_ports {dout[17]}] [get_ports {dout[18]}] [get_ports {dout[19]}]           \
[get_ports {dout[20]}] [get_ports {dout[21]}] [get_ports {dout[22]}]           \
[get_ports {dout[23]}] [get_ports {dout[24]}] [get_ports {dout[25]}]           \
[get_ports {dout[26]}] [get_ports {dout[27]}] [get_ports {dout[28]}]           \
[get_ports {dout[29]}] [get_ports {dout[30]}] [get_ports {dout[31]}]           \
[get_ports {dout[32]}] [get_ports {dout[33]}] [get_ports {dout[34]}]           \
[get_ports {dout[35]}] [get_ports {dout[36]}] [get_ports {dout[37]}]           \
[get_ports {dout[38]}] [get_ports {dout[39]}] [get_ports {dout[40]}]           \
[get_ports {dout[41]}] [get_ports {dout[42]}] [get_ports {dout[43]}]           \
[get_ports {dout[44]}] [get_ports {dout[45]}] [get_ports {dout[46]}]           \
[get_ports {dout[47]}] [get_ports {dout[48]}] [get_ports {dout[49]}]           \
[get_ports {dout[50]}] [get_ports {dout[51]}] [get_ports {dout[52]}]           \
[get_ports {dout[53]}] [get_ports {dout[54]}] [get_ports {dout[55]}]           \
[get_ports {dout[56]}] [get_ports {dout[57]}] [get_ports {dout[58]}]           \
[get_ports {dout[59]}] [get_ports {dout[60]}] [get_ports {dout[61]}]           \
[get_ports {dout[62]}] [get_ports {dout[63]}] [get_ports {dout[64]}]           \
[get_ports bsy] [get_ports dvld]]
set_input_delay -clock clk  -max 0.5  [get_ports {din[1]}]
set_input_delay -clock clk  -min 0  [get_ports {din[1]}]
set_input_delay -clock clk  -max 0.5  [get_ports {din[2]}]
set_input_delay -clock clk  -min 0  [get_ports {din[2]}]
set_input_delay -clock clk  -max 0.5  [get_ports {din[3]}]
set_input_delay -clock clk  -min 0  [get_ports {din[3]}]
set_input_delay -clock clk  -max 0.5  [get_ports {din[4]}]
set_input_delay -clock clk  -min 0  [get_ports {din[4]}]
set_input_delay -clock clk  -max 0.5  [get_ports {din[5]}]
set_input_delay -clock clk  -min 0  [get_ports {din[5]}]
set_input_delay -clock clk  -max 0.5  [get_ports {din[6]}]
set_input_delay -clock clk  -min 0  [get_ports {din[6]}]
set_input_delay -clock clk  -max 0.5  [get_ports {din[7]}]
set_input_delay -clock clk  -min 0  [get_ports {din[7]}]
set_input_delay -clock clk  -max 0.5  [get_ports {din[8]}]
set_input_delay -clock clk  -min 0  [get_ports {din[8]}]
set_input_delay -clock clk  -max 0.5  [get_ports {din[9]}]
set_input_delay -clock clk  -min 0  [get_ports {din[9]}]
set_input_delay -clock clk  -max 0.5  [get_ports {din[10]}]
set_input_delay -clock clk  -min 0  [get_ports {din[10]}]
set_input_delay -clock clk  -max 0.5  [get_ports {din[11]}]
set_input_delay -clock clk  -min 0  [get_ports {din[11]}]
set_input_delay -clock clk  -max 0.5  [get_ports {din[12]}]
set_input_delay -clock clk  -min 0  [get_ports {din[12]}]
set_input_delay -clock clk  -max 0.5  [get_ports {din[13]}]
set_input_delay -clock clk  -min 0  [get_ports {din[13]}]
set_input_delay -clock clk  -max 0.5  [get_ports {din[14]}]
set_input_delay -clock clk  -min 0  [get_ports {din[14]}]
set_input_delay -clock clk  -max 0.5  [get_ports {din[15]}]
set_input_delay -clock clk  -min 0  [get_ports {din[15]}]
set_input_delay -clock clk  -max 0.5  [get_ports {din[16]}]
set_input_delay -clock clk  -min 0  [get_ports {din[16]}]
set_input_delay -clock clk  -max 0.5  [get_ports {din[17]}]
set_input_delay -clock clk  -min 0  [get_ports {din[17]}]
set_input_delay -clock clk  -max 0.5  [get_ports {din[18]}]
set_input_delay -clock clk  -min 0  [get_ports {din[18]}]
set_input_delay -clock clk  -max 0.5  [get_ports {din[19]}]
set_input_delay -clock clk  -min 0  [get_ports {din[19]}]
set_input_delay -clock clk  -max 0.5  [get_ports {din[20]}]
set_input_delay -clock clk  -min 0  [get_ports {din[20]}]
set_input_delay -clock clk  -max 0.5  [get_ports {din[21]}]
set_input_delay -clock clk  -min 0  [get_ports {din[21]}]
set_input_delay -clock clk  -max 0.5  [get_ports {din[22]}]
set_input_delay -clock clk  -min 0  [get_ports {din[22]}]
set_input_delay -clock clk  -max 0.5  [get_ports {din[23]}]
set_input_delay -clock clk  -min 0  [get_ports {din[23]}]
set_input_delay -clock clk  -max 0.5  [get_ports {din[24]}]
set_input_delay -clock clk  -min 0  [get_ports {din[24]}]
set_input_delay -clock clk  -max 0.5  [get_ports {din[25]}]
set_input_delay -clock clk  -min 0  [get_ports {din[25]}]
set_input_delay -clock clk  -max 0.5  [get_ports {din[26]}]
set_input_delay -clock clk  -min 0  [get_ports {din[26]}]
set_input_delay -clock clk  -max 0.5  [get_ports {din[27]}]
set_input_delay -clock clk  -min 0  [get_ports {din[27]}]
set_input_delay -clock clk  -max 0.5  [get_ports {din[28]}]
set_input_delay -clock clk  -min 0  [get_ports {din[28]}]
set_input_delay -clock clk  -max 0.5  [get_ports {din[29]}]
set_input_delay -clock clk  -min 0  [get_ports {din[29]}]
set_input_delay -clock clk  -max 0.5  [get_ports {din[30]}]
set_input_delay -clock clk  -min 0  [get_ports {din[30]}]
set_input_delay -clock clk  -max 0.5  [get_ports {din[31]}]
set_input_delay -clock clk  -min 0  [get_ports {din[31]}]
set_input_delay -clock clk  -max 0.5  [get_ports {din[32]}]
set_input_delay -clock clk  -min 0  [get_ports {din[32]}]
set_input_delay -clock clk  -max 0.5  [get_ports {din[33]}]
set_input_delay -clock clk  -min 0  [get_ports {din[33]}]
set_input_delay -clock clk  -max 0.5  [get_ports {din[34]}]
set_input_delay -clock clk  -min 0  [get_ports {din[34]}]
set_input_delay -clock clk  -max 0.5  [get_ports {din[35]}]
set_input_delay -clock clk  -min 0  [get_ports {din[35]}]
set_input_delay -clock clk  -max 0.5  [get_ports {din[36]}]
set_input_delay -clock clk  -min 0  [get_ports {din[36]}]
set_input_delay -clock clk  -max 0.5  [get_ports {din[37]}]
set_input_delay -clock clk  -min 0  [get_ports {din[37]}]
set_input_delay -clock clk  -max 0.5  [get_ports {din[38]}]
set_input_delay -clock clk  -min 0  [get_ports {din[38]}]
set_input_delay -clock clk  -max 0.5  [get_ports {din[39]}]
set_input_delay -clock clk  -min 0  [get_ports {din[39]}]
set_input_delay -clock clk  -max 0.5  [get_ports {din[40]}]
set_input_delay -clock clk  -min 0  [get_ports {din[40]}]
set_input_delay -clock clk  -max 0.5  [get_ports {din[41]}]
set_input_delay -clock clk  -min 0  [get_ports {din[41]}]
set_input_delay -clock clk  -max 0.5  [get_ports {din[42]}]
set_input_delay -clock clk  -min 0  [get_ports {din[42]}]
set_input_delay -clock clk  -max 0.5  [get_ports {din[43]}]
set_input_delay -clock clk  -min 0  [get_ports {din[43]}]
set_input_delay -clock clk  -max 0.5  [get_ports {din[44]}]
set_input_delay -clock clk  -min 0  [get_ports {din[44]}]
set_input_delay -clock clk  -max 0.5  [get_ports {din[45]}]
set_input_delay -clock clk  -min 0  [get_ports {din[45]}]
set_input_delay -clock clk  -max 0.5  [get_ports {din[46]}]
set_input_delay -clock clk  -min 0  [get_ports {din[46]}]
set_input_delay -clock clk  -max 0.5  [get_ports {din[47]}]
set_input_delay -clock clk  -min 0  [get_ports {din[47]}]
set_input_delay -clock clk  -max 0.5  [get_ports {din[48]}]
set_input_delay -clock clk  -min 0  [get_ports {din[48]}]
set_input_delay -clock clk  -max 0.5  [get_ports {din[49]}]
set_input_delay -clock clk  -min 0  [get_ports {din[49]}]
set_input_delay -clock clk  -max 0.5  [get_ports {din[50]}]
set_input_delay -clock clk  -min 0  [get_ports {din[50]}]
set_input_delay -clock clk  -max 0.5  [get_ports {din[51]}]
set_input_delay -clock clk  -min 0  [get_ports {din[51]}]
set_input_delay -clock clk  -max 0.5  [get_ports {din[52]}]
set_input_delay -clock clk  -min 0  [get_ports {din[52]}]
set_input_delay -clock clk  -max 0.5  [get_ports {din[53]}]
set_input_delay -clock clk  -min 0  [get_ports {din[53]}]
set_input_delay -clock clk  -max 0.5  [get_ports {din[54]}]
set_input_delay -clock clk  -min 0  [get_ports {din[54]}]
set_input_delay -clock clk  -max 0.5  [get_ports {din[55]}]
set_input_delay -clock clk  -min 0  [get_ports {din[55]}]
set_input_delay -clock clk  -max 0.5  [get_ports {din[56]}]
set_input_delay -clock clk  -min 0  [get_ports {din[56]}]
set_input_delay -clock clk  -max 0.5  [get_ports {din[57]}]
set_input_delay -clock clk  -min 0  [get_ports {din[57]}]
set_input_delay -clock clk  -max 0.5  [get_ports {din[58]}]
set_input_delay -clock clk  -min 0  [get_ports {din[58]}]
set_input_delay -clock clk  -max 0.5  [get_ports {din[59]}]
set_input_delay -clock clk  -min 0  [get_ports {din[59]}]
set_input_delay -clock clk  -max 0.5  [get_ports {din[60]}]
set_input_delay -clock clk  -min 0  [get_ports {din[60]}]
set_input_delay -clock clk  -max 0.5  [get_ports {din[61]}]
set_input_delay -clock clk  -min 0  [get_ports {din[61]}]
set_input_delay -clock clk  -max 0.5  [get_ports {din[62]}]
set_input_delay -clock clk  -min 0  [get_ports {din[62]}]
set_input_delay -clock clk  -max 0.5  [get_ports {din[63]}]
set_input_delay -clock clk  -min 0  [get_ports {din[63]}]
set_input_delay -clock clk  -max 0.5  [get_ports {din[64]}]
set_input_delay -clock clk  -min 0  [get_ports {din[64]}]
set_input_delay -clock clk  -max 0.5  [get_ports {key1[1]}]
set_input_delay -clock clk  -min 0  [get_ports {key1[1]}]
set_input_delay -clock clk  -max 0.5  [get_ports {key1[2]}]
set_input_delay -clock clk  -min 0  [get_ports {key1[2]}]
set_input_delay -clock clk  -max 0.5  [get_ports {key1[3]}]
set_input_delay -clock clk  -min 0  [get_ports {key1[3]}]
set_input_delay -clock clk  -max 0.5  [get_ports {key1[4]}]
set_input_delay -clock clk  -min 0  [get_ports {key1[4]}]
set_input_delay -clock clk  -max 0.5  [get_ports {key1[5]}]
set_input_delay -clock clk  -min 0  [get_ports {key1[5]}]
set_input_delay -clock clk  -max 0.5  [get_ports {key1[6]}]
set_input_delay -clock clk  -min 0  [get_ports {key1[6]}]
set_input_delay -clock clk  -max 0.5  [get_ports {key1[7]}]
set_input_delay -clock clk  -min 0  [get_ports {key1[7]}]
set_input_delay -clock clk  -max 0.5  [get_ports {key1[9]}]
set_input_delay -clock clk  -min 0  [get_ports {key1[9]}]
set_input_delay -clock clk  -max 0.5  [get_ports {key1[10]}]
set_input_delay -clock clk  -min 0  [get_ports {key1[10]}]
set_input_delay -clock clk  -max 0.5  [get_ports {key1[11]}]
set_input_delay -clock clk  -min 0  [get_ports {key1[11]}]
set_input_delay -clock clk  -max 0.5  [get_ports {key1[12]}]
set_input_delay -clock clk  -min 0  [get_ports {key1[12]}]
set_input_delay -clock clk  -max 0.5  [get_ports {key1[13]}]
set_input_delay -clock clk  -min 0  [get_ports {key1[13]}]
set_input_delay -clock clk  -max 0.5  [get_ports {key1[14]}]
set_input_delay -clock clk  -min 0  [get_ports {key1[14]}]
set_input_delay -clock clk  -max 0.5  [get_ports {key1[15]}]
set_input_delay -clock clk  -min 0  [get_ports {key1[15]}]
set_input_delay -clock clk  -max 0.5  [get_ports {key1[17]}]
set_input_delay -clock clk  -min 0  [get_ports {key1[17]}]
set_input_delay -clock clk  -max 0.5  [get_ports {key1[18]}]
set_input_delay -clock clk  -min 0  [get_ports {key1[18]}]
set_input_delay -clock clk  -max 0.5  [get_ports {key1[19]}]
set_input_delay -clock clk  -min 0  [get_ports {key1[19]}]
set_input_delay -clock clk  -max 0.5  [get_ports {key1[20]}]
set_input_delay -clock clk  -min 0  [get_ports {key1[20]}]
set_input_delay -clock clk  -max 0.5  [get_ports {key1[21]}]
set_input_delay -clock clk  -min 0  [get_ports {key1[21]}]
set_input_delay -clock clk  -max 0.5  [get_ports {key1[22]}]
set_input_delay -clock clk  -min 0  [get_ports {key1[22]}]
set_input_delay -clock clk  -max 0.5  [get_ports {key1[23]}]
set_input_delay -clock clk  -min 0  [get_ports {key1[23]}]
set_input_delay -clock clk  -max 0.5  [get_ports {key1[25]}]
set_input_delay -clock clk  -min 0  [get_ports {key1[25]}]
set_input_delay -clock clk  -max 0.5  [get_ports {key1[26]}]
set_input_delay -clock clk  -min 0  [get_ports {key1[26]}]
set_input_delay -clock clk  -max 0.5  [get_ports {key1[27]}]
set_input_delay -clock clk  -min 0  [get_ports {key1[27]}]
set_input_delay -clock clk  -max 0.5  [get_ports {key1[28]}]
set_input_delay -clock clk  -min 0  [get_ports {key1[28]}]
set_input_delay -clock clk  -max 0.5  [get_ports {key1[29]}]
set_input_delay -clock clk  -min 0  [get_ports {key1[29]}]
set_input_delay -clock clk  -max 0.5  [get_ports {key1[30]}]
set_input_delay -clock clk  -min 0  [get_ports {key1[30]}]
set_input_delay -clock clk  -max 0.5  [get_ports {key1[31]}]
set_input_delay -clock clk  -min 0  [get_ports {key1[31]}]
set_input_delay -clock clk  -max 0.5  [get_ports {key1[33]}]
set_input_delay -clock clk  -min 0  [get_ports {key1[33]}]
set_input_delay -clock clk  -max 0.5  [get_ports {key1[34]}]
set_input_delay -clock clk  -min 0  [get_ports {key1[34]}]
set_input_delay -clock clk  -max 0.5  [get_ports {key1[35]}]
set_input_delay -clock clk  -min 0  [get_ports {key1[35]}]
set_input_delay -clock clk  -max 0.5  [get_ports {key1[36]}]
set_input_delay -clock clk  -min 0  [get_ports {key1[36]}]
set_input_delay -clock clk  -max 0.5  [get_ports {key1[37]}]
set_input_delay -clock clk  -min 0  [get_ports {key1[37]}]
set_input_delay -clock clk  -max 0.5  [get_ports {key1[38]}]
set_input_delay -clock clk  -min 0  [get_ports {key1[38]}]
set_input_delay -clock clk  -max 0.5  [get_ports {key1[39]}]
set_input_delay -clock clk  -min 0  [get_ports {key1[39]}]
set_input_delay -clock clk  -max 0.5  [get_ports {key1[41]}]
set_input_delay -clock clk  -min 0  [get_ports {key1[41]}]
set_input_delay -clock clk  -max 0.5  [get_ports {key1[42]}]
set_input_delay -clock clk  -min 0  [get_ports {key1[42]}]
set_input_delay -clock clk  -max 0.5  [get_ports {key1[43]}]
set_input_delay -clock clk  -min 0  [get_ports {key1[43]}]
set_input_delay -clock clk  -max 0.5  [get_ports {key1[44]}]
set_input_delay -clock clk  -min 0  [get_ports {key1[44]}]
set_input_delay -clock clk  -max 0.5  [get_ports {key1[45]}]
set_input_delay -clock clk  -min 0  [get_ports {key1[45]}]
set_input_delay -clock clk  -max 0.5  [get_ports {key1[46]}]
set_input_delay -clock clk  -min 0  [get_ports {key1[46]}]
set_input_delay -clock clk  -max 0.5  [get_ports {key1[47]}]
set_input_delay -clock clk  -min 0  [get_ports {key1[47]}]
set_input_delay -clock clk  -max 0.5  [get_ports {key1[49]}]
set_input_delay -clock clk  -min 0  [get_ports {key1[49]}]
set_input_delay -clock clk  -max 0.5  [get_ports {key1[50]}]
set_input_delay -clock clk  -min 0  [get_ports {key1[50]}]
set_input_delay -clock clk  -max 0.5  [get_ports {key1[51]}]
set_input_delay -clock clk  -min 0  [get_ports {key1[51]}]
set_input_delay -clock clk  -max 0.5  [get_ports {key1[52]}]
set_input_delay -clock clk  -min 0  [get_ports {key1[52]}]
set_input_delay -clock clk  -max 0.5  [get_ports {key1[53]}]
set_input_delay -clock clk  -min 0  [get_ports {key1[53]}]
set_input_delay -clock clk  -max 0.5  [get_ports {key1[54]}]
set_input_delay -clock clk  -min 0  [get_ports {key1[54]}]
set_input_delay -clock clk  -max 0.5  [get_ports {key1[55]}]
set_input_delay -clock clk  -min 0  [get_ports {key1[55]}]
set_input_delay -clock clk  -max 0.5  [get_ports {key1[57]}]
set_input_delay -clock clk  -min 0  [get_ports {key1[57]}]
set_input_delay -clock clk  -max 0.5  [get_ports {key1[58]}]
set_input_delay -clock clk  -min 0  [get_ports {key1[58]}]
set_input_delay -clock clk  -max 0.5  [get_ports {key1[59]}]
set_input_delay -clock clk  -min 0  [get_ports {key1[59]}]
set_input_delay -clock clk  -max 0.5  [get_ports {key1[60]}]
set_input_delay -clock clk  -min 0  [get_ports {key1[60]}]
set_input_delay -clock clk  -max 0.5  [get_ports {key1[61]}]
set_input_delay -clock clk  -min 0  [get_ports {key1[61]}]
set_input_delay -clock clk  -max 0.5  [get_ports {key1[62]}]
set_input_delay -clock clk  -min 0  [get_ports {key1[62]}]
set_input_delay -clock clk  -max 0.5  [get_ports {key1[63]}]
set_input_delay -clock clk  -min 0  [get_ports {key1[63]}]
set_input_delay -clock clk  -max 0.5  [get_ports {key2[1]}]
set_input_delay -clock clk  -min 0  [get_ports {key2[1]}]
set_input_delay -clock clk  -max 0.5  [get_ports {key2[2]}]
set_input_delay -clock clk  -min 0  [get_ports {key2[2]}]
set_input_delay -clock clk  -max 0.5  [get_ports {key2[3]}]
set_input_delay -clock clk  -min 0  [get_ports {key2[3]}]
set_input_delay -clock clk  -max 0.5  [get_ports {key2[4]}]
set_input_delay -clock clk  -min 0  [get_ports {key2[4]}]
set_input_delay -clock clk  -max 0.5  [get_ports {key2[5]}]
set_input_delay -clock clk  -min 0  [get_ports {key2[5]}]
set_input_delay -clock clk  -max 0.5  [get_ports {key2[6]}]
set_input_delay -clock clk  -min 0  [get_ports {key2[6]}]
set_input_delay -clock clk  -max 0.5  [get_ports {key2[7]}]
set_input_delay -clock clk  -min 0  [get_ports {key2[7]}]
set_input_delay -clock clk  -max 0.5  [get_ports {key2[9]}]
set_input_delay -clock clk  -min 0  [get_ports {key2[9]}]
set_input_delay -clock clk  -max 0.5  [get_ports {key2[10]}]
set_input_delay -clock clk  -min 0  [get_ports {key2[10]}]
set_input_delay -clock clk  -max 0.5  [get_ports {key2[11]}]
set_input_delay -clock clk  -min 0  [get_ports {key2[11]}]
set_input_delay -clock clk  -max 0.5  [get_ports {key2[12]}]
set_input_delay -clock clk  -min 0  [get_ports {key2[12]}]
set_input_delay -clock clk  -max 0.5  [get_ports {key2[13]}]
set_input_delay -clock clk  -min 0  [get_ports {key2[13]}]
set_input_delay -clock clk  -max 0.5  [get_ports {key2[14]}]
set_input_delay -clock clk  -min 0  [get_ports {key2[14]}]
set_input_delay -clock clk  -max 0.5  [get_ports {key2[15]}]
set_input_delay -clock clk  -min 0  [get_ports {key2[15]}]
set_input_delay -clock clk  -max 0.5  [get_ports {key2[17]}]
set_input_delay -clock clk  -min 0  [get_ports {key2[17]}]
set_input_delay -clock clk  -max 0.5  [get_ports {key2[18]}]
set_input_delay -clock clk  -min 0  [get_ports {key2[18]}]
set_input_delay -clock clk  -max 0.5  [get_ports {key2[19]}]
set_input_delay -clock clk  -min 0  [get_ports {key2[19]}]
set_input_delay -clock clk  -max 0.5  [get_ports {key2[20]}]
set_input_delay -clock clk  -min 0  [get_ports {key2[20]}]
set_input_delay -clock clk  -max 0.5  [get_ports {key2[21]}]
set_input_delay -clock clk  -min 0  [get_ports {key2[21]}]
set_input_delay -clock clk  -max 0.5  [get_ports {key2[22]}]
set_input_delay -clock clk  -min 0  [get_ports {key2[22]}]
set_input_delay -clock clk  -max 0.5  [get_ports {key2[23]}]
set_input_delay -clock clk  -min 0  [get_ports {key2[23]}]
set_input_delay -clock clk  -max 0.5  [get_ports {key2[25]}]
set_input_delay -clock clk  -min 0  [get_ports {key2[25]}]
set_input_delay -clock clk  -max 0.5  [get_ports {key2[26]}]
set_input_delay -clock clk  -min 0  [get_ports {key2[26]}]
set_input_delay -clock clk  -max 0.5  [get_ports {key2[27]}]
set_input_delay -clock clk  -min 0  [get_ports {key2[27]}]
set_input_delay -clock clk  -max 0.5  [get_ports {key2[28]}]
set_input_delay -clock clk  -min 0  [get_ports {key2[28]}]
set_input_delay -clock clk  -max 0.5  [get_ports {key2[29]}]
set_input_delay -clock clk  -min 0  [get_ports {key2[29]}]
set_input_delay -clock clk  -max 0.5  [get_ports {key2[30]}]
set_input_delay -clock clk  -min 0  [get_ports {key2[30]}]
set_input_delay -clock clk  -max 0.5  [get_ports {key2[31]}]
set_input_delay -clock clk  -min 0  [get_ports {key2[31]}]
set_input_delay -clock clk  -max 0.5  [get_ports {key2[33]}]
set_input_delay -clock clk  -min 0  [get_ports {key2[33]}]
set_input_delay -clock clk  -max 0.5  [get_ports {key2[34]}]
set_input_delay -clock clk  -min 0  [get_ports {key2[34]}]
set_input_delay -clock clk  -max 0.5  [get_ports {key2[35]}]
set_input_delay -clock clk  -min 0  [get_ports {key2[35]}]
set_input_delay -clock clk  -max 0.5  [get_ports {key2[36]}]
set_input_delay -clock clk  -min 0  [get_ports {key2[36]}]
set_input_delay -clock clk  -max 0.5  [get_ports {key2[37]}]
set_input_delay -clock clk  -min 0  [get_ports {key2[37]}]
set_input_delay -clock clk  -max 0.5  [get_ports {key2[38]}]
set_input_delay -clock clk  -min 0  [get_ports {key2[38]}]
set_input_delay -clock clk  -max 0.5  [get_ports {key2[39]}]
set_input_delay -clock clk  -min 0  [get_ports {key2[39]}]
set_input_delay -clock clk  -max 0.5  [get_ports {key2[41]}]
set_input_delay -clock clk  -min 0  [get_ports {key2[41]}]
set_input_delay -clock clk  -max 0.5  [get_ports {key2[42]}]
set_input_delay -clock clk  -min 0  [get_ports {key2[42]}]
set_input_delay -clock clk  -max 0.5  [get_ports {key2[43]}]
set_input_delay -clock clk  -min 0  [get_ports {key2[43]}]
set_input_delay -clock clk  -max 0.5  [get_ports {key2[44]}]
set_input_delay -clock clk  -min 0  [get_ports {key2[44]}]
set_input_delay -clock clk  -max 0.5  [get_ports {key2[45]}]
set_input_delay -clock clk  -min 0  [get_ports {key2[45]}]
set_input_delay -clock clk  -max 0.5  [get_ports {key2[46]}]
set_input_delay -clock clk  -min 0  [get_ports {key2[46]}]
set_input_delay -clock clk  -max 0.5  [get_ports {key2[47]}]
set_input_delay -clock clk  -min 0  [get_ports {key2[47]}]
set_input_delay -clock clk  -max 0.5  [get_ports {key2[49]}]
set_input_delay -clock clk  -min 0  [get_ports {key2[49]}]
set_input_delay -clock clk  -max 0.5  [get_ports {key2[50]}]
set_input_delay -clock clk  -min 0  [get_ports {key2[50]}]
set_input_delay -clock clk  -max 0.5  [get_ports {key2[51]}]
set_input_delay -clock clk  -min 0  [get_ports {key2[51]}]
set_input_delay -clock clk  -max 0.5  [get_ports {key2[52]}]
set_input_delay -clock clk  -min 0  [get_ports {key2[52]}]
set_input_delay -clock clk  -max 0.5  [get_ports {key2[53]}]
set_input_delay -clock clk  -min 0  [get_ports {key2[53]}]
set_input_delay -clock clk  -max 0.5  [get_ports {key2[54]}]
set_input_delay -clock clk  -min 0  [get_ports {key2[54]}]
set_input_delay -clock clk  -max 0.5  [get_ports {key2[55]}]
set_input_delay -clock clk  -min 0  [get_ports {key2[55]}]
set_input_delay -clock clk  -max 0.5  [get_ports {key2[57]}]
set_input_delay -clock clk  -min 0  [get_ports {key2[57]}]
set_input_delay -clock clk  -max 0.5  [get_ports {key2[58]}]
set_input_delay -clock clk  -min 0  [get_ports {key2[58]}]
set_input_delay -clock clk  -max 0.5  [get_ports {key2[59]}]
set_input_delay -clock clk  -min 0  [get_ports {key2[59]}]
set_input_delay -clock clk  -max 0.5  [get_ports {key2[60]}]
set_input_delay -clock clk  -min 0  [get_ports {key2[60]}]
set_input_delay -clock clk  -max 0.5  [get_ports {key2[61]}]
set_input_delay -clock clk  -min 0  [get_ports {key2[61]}]
set_input_delay -clock clk  -max 0.5  [get_ports {key2[62]}]
set_input_delay -clock clk  -min 0  [get_ports {key2[62]}]
set_input_delay -clock clk  -max 0.5  [get_ports {key2[63]}]
set_input_delay -clock clk  -min 0  [get_ports {key2[63]}]
set_input_delay -clock clk  -max 0.5  [get_ports {key3[1]}]
set_input_delay -clock clk  -min 0  [get_ports {key3[1]}]
set_input_delay -clock clk  -max 0.5  [get_ports {key3[2]}]
set_input_delay -clock clk  -min 0  [get_ports {key3[2]}]
set_input_delay -clock clk  -max 0.5  [get_ports {key3[3]}]
set_input_delay -clock clk  -min 0  [get_ports {key3[3]}]
set_input_delay -clock clk  -max 0.5  [get_ports {key3[4]}]
set_input_delay -clock clk  -min 0  [get_ports {key3[4]}]
set_input_delay -clock clk  -max 0.5  [get_ports {key3[5]}]
set_input_delay -clock clk  -min 0  [get_ports {key3[5]}]
set_input_delay -clock clk  -max 0.5  [get_ports {key3[6]}]
set_input_delay -clock clk  -min 0  [get_ports {key3[6]}]
set_input_delay -clock clk  -max 0.5  [get_ports {key3[7]}]
set_input_delay -clock clk  -min 0  [get_ports {key3[7]}]
set_input_delay -clock clk  -max 0.5  [get_ports {key3[9]}]
set_input_delay -clock clk  -min 0  [get_ports {key3[9]}]
set_input_delay -clock clk  -max 0.5  [get_ports {key3[10]}]
set_input_delay -clock clk  -min 0  [get_ports {key3[10]}]
set_input_delay -clock clk  -max 0.5  [get_ports {key3[11]}]
set_input_delay -clock clk  -min 0  [get_ports {key3[11]}]
set_input_delay -clock clk  -max 0.5  [get_ports {key3[12]}]
set_input_delay -clock clk  -min 0  [get_ports {key3[12]}]
set_input_delay -clock clk  -max 0.5  [get_ports {key3[13]}]
set_input_delay -clock clk  -min 0  [get_ports {key3[13]}]
set_input_delay -clock clk  -max 0.5  [get_ports {key3[14]}]
set_input_delay -clock clk  -min 0  [get_ports {key3[14]}]
set_input_delay -clock clk  -max 0.5  [get_ports {key3[15]}]
set_input_delay -clock clk  -min 0  [get_ports {key3[15]}]
set_input_delay -clock clk  -max 0.5  [get_ports {key3[17]}]
set_input_delay -clock clk  -min 0  [get_ports {key3[17]}]
set_input_delay -clock clk  -max 0.5  [get_ports {key3[18]}]
set_input_delay -clock clk  -min 0  [get_ports {key3[18]}]
set_input_delay -clock clk  -max 0.5  [get_ports {key3[19]}]
set_input_delay -clock clk  -min 0  [get_ports {key3[19]}]
set_input_delay -clock clk  -max 0.5  [get_ports {key3[20]}]
set_input_delay -clock clk  -min 0  [get_ports {key3[20]}]
set_input_delay -clock clk  -max 0.5  [get_ports {key3[21]}]
set_input_delay -clock clk  -min 0  [get_ports {key3[21]}]
set_input_delay -clock clk  -max 0.5  [get_ports {key3[22]}]
set_input_delay -clock clk  -min 0  [get_ports {key3[22]}]
set_input_delay -clock clk  -max 0.5  [get_ports {key3[23]}]
set_input_delay -clock clk  -min 0  [get_ports {key3[23]}]
set_input_delay -clock clk  -max 0.5  [get_ports {key3[25]}]
set_input_delay -clock clk  -min 0  [get_ports {key3[25]}]
set_input_delay -clock clk  -max 0.5  [get_ports {key3[26]}]
set_input_delay -clock clk  -min 0  [get_ports {key3[26]}]
set_input_delay -clock clk  -max 0.5  [get_ports {key3[27]}]
set_input_delay -clock clk  -min 0  [get_ports {key3[27]}]
set_input_delay -clock clk  -max 0.5  [get_ports {key3[28]}]
set_input_delay -clock clk  -min 0  [get_ports {key3[28]}]
set_input_delay -clock clk  -max 0.5  [get_ports {key3[29]}]
set_input_delay -clock clk  -min 0  [get_ports {key3[29]}]
set_input_delay -clock clk  -max 0.5  [get_ports {key3[30]}]
set_input_delay -clock clk  -min 0  [get_ports {key3[30]}]
set_input_delay -clock clk  -max 0.5  [get_ports {key3[31]}]
set_input_delay -clock clk  -min 0  [get_ports {key3[31]}]
set_input_delay -clock clk  -max 0.5  [get_ports {key3[33]}]
set_input_delay -clock clk  -min 0  [get_ports {key3[33]}]
set_input_delay -clock clk  -max 0.5  [get_ports {key3[34]}]
set_input_delay -clock clk  -min 0  [get_ports {key3[34]}]
set_input_delay -clock clk  -max 0.5  [get_ports {key3[35]}]
set_input_delay -clock clk  -min 0  [get_ports {key3[35]}]
set_input_delay -clock clk  -max 0.5  [get_ports {key3[36]}]
set_input_delay -clock clk  -min 0  [get_ports {key3[36]}]
set_input_delay -clock clk  -max 0.5  [get_ports {key3[37]}]
set_input_delay -clock clk  -min 0  [get_ports {key3[37]}]
set_input_delay -clock clk  -max 0.5  [get_ports {key3[38]}]
set_input_delay -clock clk  -min 0  [get_ports {key3[38]}]
set_input_delay -clock clk  -max 0.5  [get_ports {key3[39]}]
set_input_delay -clock clk  -min 0  [get_ports {key3[39]}]
set_input_delay -clock clk  -max 0.5  [get_ports {key3[41]}]
set_input_delay -clock clk  -min 0  [get_ports {key3[41]}]
set_input_delay -clock clk  -max 0.5  [get_ports {key3[42]}]
set_input_delay -clock clk  -min 0  [get_ports {key3[42]}]
set_input_delay -clock clk  -max 0.5  [get_ports {key3[43]}]
set_input_delay -clock clk  -min 0  [get_ports {key3[43]}]
set_input_delay -clock clk  -max 0.5  [get_ports {key3[44]}]
set_input_delay -clock clk  -min 0  [get_ports {key3[44]}]
set_input_delay -clock clk  -max 0.5  [get_ports {key3[45]}]
set_input_delay -clock clk  -min 0  [get_ports {key3[45]}]
set_input_delay -clock clk  -max 0.5  [get_ports {key3[46]}]
set_input_delay -clock clk  -min 0  [get_ports {key3[46]}]
set_input_delay -clock clk  -max 0.5  [get_ports {key3[47]}]
set_input_delay -clock clk  -min 0  [get_ports {key3[47]}]
set_input_delay -clock clk  -max 0.5  [get_ports {key3[49]}]
set_input_delay -clock clk  -min 0  [get_ports {key3[49]}]
set_input_delay -clock clk  -max 0.5  [get_ports {key3[50]}]
set_input_delay -clock clk  -min 0  [get_ports {key3[50]}]
set_input_delay -clock clk  -max 0.5  [get_ports {key3[51]}]
set_input_delay -clock clk  -min 0  [get_ports {key3[51]}]
set_input_delay -clock clk  -max 0.5  [get_ports {key3[52]}]
set_input_delay -clock clk  -min 0  [get_ports {key3[52]}]
set_input_delay -clock clk  -max 0.5  [get_ports {key3[53]}]
set_input_delay -clock clk  -min 0  [get_ports {key3[53]}]
set_input_delay -clock clk  -max 0.5  [get_ports {key3[54]}]
set_input_delay -clock clk  -min 0  [get_ports {key3[54]}]
set_input_delay -clock clk  -max 0.5  [get_ports {key3[55]}]
set_input_delay -clock clk  -min 0  [get_ports {key3[55]}]
set_input_delay -clock clk  -max 0.5  [get_ports {key3[57]}]
set_input_delay -clock clk  -min 0  [get_ports {key3[57]}]
set_input_delay -clock clk  -max 0.5  [get_ports {key3[58]}]
set_input_delay -clock clk  -min 0  [get_ports {key3[58]}]
set_input_delay -clock clk  -max 0.5  [get_ports {key3[59]}]
set_input_delay -clock clk  -min 0  [get_ports {key3[59]}]
set_input_delay -clock clk  -max 0.5  [get_ports {key3[60]}]
set_input_delay -clock clk  -min 0  [get_ports {key3[60]}]
set_input_delay -clock clk  -max 0.5  [get_ports {key3[61]}]
set_input_delay -clock clk  -min 0  [get_ports {key3[61]}]
set_input_delay -clock clk  -max 0.5  [get_ports {key3[62]}]
set_input_delay -clock clk  -min 0  [get_ports {key3[62]}]
set_input_delay -clock clk  -max 0.5  [get_ports {key3[63]}]
set_input_delay -clock clk  -min 0  [get_ports {key3[63]}]
set_input_delay -clock clk  -max 0.5  [get_ports drdy]
set_input_delay -clock clk  -min 0  [get_ports drdy]
set_input_delay -clock clk  -max 0.5  [get_ports krdy]
set_input_delay -clock clk  -min 0  [get_ports krdy]
set_input_delay -clock clk  -max 0.5  [get_ports enc]
set_input_delay -clock clk  -min 0  [get_ports enc]
set_input_delay -clock clk  -max 0.5  [get_ports rstn]
set_input_delay -clock clk  -min 0  [get_ports rstn]
set_input_delay -clock clk  -max 0.5  [get_ports en]
set_input_delay -clock clk  -min 0  [get_ports en]
set_output_delay -clock clk  0.5  [get_ports {dout[1]}]
set_output_delay -clock clk  0.5  [get_ports {dout[2]}]
set_output_delay -clock clk  0.5  [get_ports {dout[3]}]
set_output_delay -clock clk  0.5  [get_ports {dout[4]}]
set_output_delay -clock clk  0.5  [get_ports {dout[5]}]
set_output_delay -clock clk  0.5  [get_ports {dout[6]}]
set_output_delay -clock clk  0.5  [get_ports {dout[7]}]
set_output_delay -clock clk  0.5  [get_ports {dout[8]}]
set_output_delay -clock clk  0.5  [get_ports {dout[9]}]
set_output_delay -clock clk  0.5  [get_ports {dout[10]}]
set_output_delay -clock clk  0.5  [get_ports {dout[11]}]
set_output_delay -clock clk  0.5  [get_ports {dout[12]}]
set_output_delay -clock clk  0.5  [get_ports {dout[13]}]
set_output_delay -clock clk  0.5  [get_ports {dout[14]}]
set_output_delay -clock clk  0.5  [get_ports {dout[15]}]
set_output_delay -clock clk  0.5  [get_ports {dout[16]}]
set_output_delay -clock clk  0.5  [get_ports {dout[17]}]
set_output_delay -clock clk  0.5  [get_ports {dout[18]}]
set_output_delay -clock clk  0.5  [get_ports {dout[19]}]
set_output_delay -clock clk  0.5  [get_ports {dout[20]}]
set_output_delay -clock clk  0.5  [get_ports {dout[21]}]
set_output_delay -clock clk  0.5  [get_ports {dout[22]}]
set_output_delay -clock clk  0.5  [get_ports {dout[23]}]
set_output_delay -clock clk  0.5  [get_ports {dout[24]}]
set_output_delay -clock clk  0.5  [get_ports {dout[25]}]
set_output_delay -clock clk  0.5  [get_ports {dout[26]}]
set_output_delay -clock clk  0.5  [get_ports {dout[27]}]
set_output_delay -clock clk  0.5  [get_ports {dout[28]}]
set_output_delay -clock clk  0.5  [get_ports {dout[29]}]
set_output_delay -clock clk  0.5  [get_ports {dout[30]}]
set_output_delay -clock clk  0.5  [get_ports {dout[31]}]
set_output_delay -clock clk  0.5  [get_ports {dout[32]}]
set_output_delay -clock clk  0.5  [get_ports {dout[33]}]
set_output_delay -clock clk  0.5  [get_ports {dout[34]}]
set_output_delay -clock clk  0.5  [get_ports {dout[35]}]
set_output_delay -clock clk  0.5  [get_ports {dout[36]}]
set_output_delay -clock clk  0.5  [get_ports {dout[37]}]
set_output_delay -clock clk  0.5  [get_ports {dout[38]}]
set_output_delay -clock clk  0.5  [get_ports {dout[39]}]
set_output_delay -clock clk  0.5  [get_ports {dout[40]}]
set_output_delay -clock clk  0.5  [get_ports {dout[41]}]
set_output_delay -clock clk  0.5  [get_ports {dout[42]}]
set_output_delay -clock clk  0.5  [get_ports {dout[43]}]
set_output_delay -clock clk  0.5  [get_ports {dout[44]}]
set_output_delay -clock clk  0.5  [get_ports {dout[45]}]
set_output_delay -clock clk  0.5  [get_ports {dout[46]}]
set_output_delay -clock clk  0.5  [get_ports {dout[47]}]
set_output_delay -clock clk  0.5  [get_ports {dout[48]}]
set_output_delay -clock clk  0.5  [get_ports {dout[49]}]
set_output_delay -clock clk  0.5  [get_ports {dout[50]}]
set_output_delay -clock clk  0.5  [get_ports {dout[51]}]
set_output_delay -clock clk  0.5  [get_ports {dout[52]}]
set_output_delay -clock clk  0.5  [get_ports {dout[53]}]
set_output_delay -clock clk  0.5  [get_ports {dout[54]}]
set_output_delay -clock clk  0.5  [get_ports {dout[55]}]
set_output_delay -clock clk  0.5  [get_ports {dout[56]}]
set_output_delay -clock clk  0.5  [get_ports {dout[57]}]
set_output_delay -clock clk  0.5  [get_ports {dout[58]}]
set_output_delay -clock clk  0.5  [get_ports {dout[59]}]
set_output_delay -clock clk  0.5  [get_ports {dout[60]}]
set_output_delay -clock clk  0.5  [get_ports {dout[61]}]
set_output_delay -clock clk  0.5  [get_ports {dout[62]}]
set_output_delay -clock clk  0.5  [get_ports {dout[63]}]
set_output_delay -clock clk  0.5  [get_ports {dout[64]}]
set_output_delay -clock clk  0.5  [get_ports bsy]
set_output_delay -clock clk  0.5  [get_ports dvld]
