###################################################################

# Created by write_sdc on Thu Jan 13 13:53:40 2022

###################################################################
set sdc_version 2.0

set_units -time ns -resistance MOhm -capacitance fF -voltage V -current mA
create_clock [get_ports clock]  -name CRYPTOCLK  -period 10  -waveform {0 5}
group_path -name input_group  -from [list [get_ports clock] [get_ports resetn] [get_ports enc_dec]          \
[get_ports key_exp] [get_ports start] [get_ports {text_in[127]}] [get_ports    \
{text_in[126]}] [get_ports {text_in[125]}] [get_ports {text_in[124]}]          \
[get_ports {text_in[123]}] [get_ports {text_in[122]}] [get_ports               \
{text_in[121]}] [get_ports {text_in[120]}] [get_ports {text_in[119]}]          \
[get_ports {text_in[118]}] [get_ports {text_in[117]}] [get_ports               \
{text_in[116]}] [get_ports {text_in[115]}] [get_ports {text_in[114]}]          \
[get_ports {text_in[113]}] [get_ports {text_in[112]}] [get_ports               \
{text_in[111]}] [get_ports {text_in[110]}] [get_ports {text_in[109]}]          \
[get_ports {text_in[108]}] [get_ports {text_in[107]}] [get_ports               \
{text_in[106]}] [get_ports {text_in[105]}] [get_ports {text_in[104]}]          \
[get_ports {text_in[103]}] [get_ports {text_in[102]}] [get_ports               \
{text_in[101]}] [get_ports {text_in[100]}] [get_ports {text_in[99]}]           \
[get_ports {text_in[98]}] [get_ports {text_in[97]}] [get_ports {text_in[96]}]  \
[get_ports {text_in[95]}] [get_ports {text_in[94]}] [get_ports {text_in[93]}]  \
[get_ports {text_in[92]}] [get_ports {text_in[91]}] [get_ports {text_in[90]}]  \
[get_ports {text_in[89]}] [get_ports {text_in[88]}] [get_ports {text_in[87]}]  \
[get_ports {text_in[86]}] [get_ports {text_in[85]}] [get_ports {text_in[84]}]  \
[get_ports {text_in[83]}] [get_ports {text_in[82]}] [get_ports {text_in[81]}]  \
[get_ports {text_in[80]}] [get_ports {text_in[79]}] [get_ports {text_in[78]}]  \
[get_ports {text_in[77]}] [get_ports {text_in[76]}] [get_ports {text_in[75]}]  \
[get_ports {text_in[74]}] [get_ports {text_in[73]}] [get_ports {text_in[72]}]  \
[get_ports {text_in[71]}] [get_ports {text_in[70]}] [get_ports {text_in[69]}]  \
[get_ports {text_in[68]}] [get_ports {text_in[67]}] [get_ports {text_in[66]}]  \
[get_ports {text_in[65]}] [get_ports {text_in[64]}] [get_ports {text_in[63]}]  \
[get_ports {text_in[62]}] [get_ports {text_in[61]}] [get_ports {text_in[60]}]  \
[get_ports {text_in[59]}] [get_ports {text_in[58]}] [get_ports {text_in[57]}]  \
[get_ports {text_in[56]}] [get_ports {text_in[55]}] [get_ports {text_in[54]}]  \
[get_ports {text_in[53]}] [get_ports {text_in[52]}] [get_ports {text_in[51]}]  \
[get_ports {text_in[50]}] [get_ports {text_in[49]}] [get_ports {text_in[48]}]  \
[get_ports {text_in[47]}] [get_ports {text_in[46]}] [get_ports {text_in[45]}]  \
[get_ports {text_in[44]}] [get_ports {text_in[43]}] [get_ports {text_in[42]}]  \
[get_ports {text_in[41]}] [get_ports {text_in[40]}] [get_ports {text_in[39]}]  \
[get_ports {text_in[38]}] [get_ports {text_in[37]}] [get_ports {text_in[36]}]  \
[get_ports {text_in[35]}] [get_ports {text_in[34]}] [get_ports {text_in[33]}]  \
[get_ports {text_in[32]}] [get_ports {text_in[31]}] [get_ports {text_in[30]}]  \
[get_ports {text_in[29]}] [get_ports {text_in[28]}] [get_ports {text_in[27]}]  \
[get_ports {text_in[26]}] [get_ports {text_in[25]}] [get_ports {text_in[24]}]  \
[get_ports {text_in[23]}] [get_ports {text_in[22]}] [get_ports {text_in[21]}]  \
[get_ports {text_in[20]}] [get_ports {text_in[19]}] [get_ports {text_in[18]}]  \
[get_ports {text_in[17]}] [get_ports {text_in[16]}] [get_ports {text_in[15]}]  \
[get_ports {text_in[14]}] [get_ports {text_in[13]}] [get_ports {text_in[12]}]  \
[get_ports {text_in[11]}] [get_ports {text_in[10]}] [get_ports {text_in[9]}]   \
[get_ports {text_in[8]}] [get_ports {text_in[7]}] [get_ports {text_in[6]}]     \
[get_ports {text_in[5]}] [get_ports {text_in[4]}] [get_ports {text_in[3]}]     \
[get_ports {text_in[2]}] [get_ports {text_in[1]}] [get_ports {text_in[0]}]     \
[get_ports {key_in[127]}] [get_ports {key_in[126]}] [get_ports {key_in[125]}]  \
[get_ports {key_in[124]}] [get_ports {key_in[123]}] [get_ports {key_in[122]}]  \
[get_ports {key_in[121]}] [get_ports {key_in[120]}] [get_ports {key_in[119]}]  \
[get_ports {key_in[118]}] [get_ports {key_in[117]}] [get_ports {key_in[116]}]  \
[get_ports {key_in[115]}] [get_ports {key_in[114]}] [get_ports {key_in[113]}]  \
[get_ports {key_in[112]}] [get_ports {key_in[111]}] [get_ports {key_in[110]}]  \
[get_ports {key_in[109]}] [get_ports {key_in[108]}] [get_ports {key_in[107]}]  \
[get_ports {key_in[106]}] [get_ports {key_in[105]}] [get_ports {key_in[104]}]  \
[get_ports {key_in[103]}] [get_ports {key_in[102]}] [get_ports {key_in[101]}]  \
[get_ports {key_in[100]}] [get_ports {key_in[99]}] [get_ports {key_in[98]}]    \
[get_ports {key_in[97]}] [get_ports {key_in[96]}] [get_ports {key_in[95]}]     \
[get_ports {key_in[94]}] [get_ports {key_in[93]}] [get_ports {key_in[92]}]     \
[get_ports {key_in[91]}] [get_ports {key_in[90]}] [get_ports {key_in[89]}]     \
[get_ports {key_in[88]}] [get_ports {key_in[87]}] [get_ports {key_in[86]}]     \
[get_ports {key_in[85]}] [get_ports {key_in[84]}] [get_ports {key_in[83]}]     \
[get_ports {key_in[82]}] [get_ports {key_in[81]}] [get_ports {key_in[80]}]     \
[get_ports {key_in[79]}] [get_ports {key_in[78]}] [get_ports {key_in[77]}]     \
[get_ports {key_in[76]}] [get_ports {key_in[75]}] [get_ports {key_in[74]}]     \
[get_ports {key_in[73]}] [get_ports {key_in[72]}] [get_ports {key_in[71]}]     \
[get_ports {key_in[70]}] [get_ports {key_in[69]}] [get_ports {key_in[68]}]     \
[get_ports {key_in[67]}] [get_ports {key_in[66]}] [get_ports {key_in[65]}]     \
[get_ports {key_in[64]}] [get_ports {key_in[63]}] [get_ports {key_in[62]}]     \
[get_ports {key_in[61]}] [get_ports {key_in[60]}] [get_ports {key_in[59]}]     \
[get_ports {key_in[58]}] [get_ports {key_in[57]}] [get_ports {key_in[56]}]     \
[get_ports {key_in[55]}] [get_ports {key_in[54]}] [get_ports {key_in[53]}]     \
[get_ports {key_in[52]}] [get_ports {key_in[51]}] [get_ports {key_in[50]}]     \
[get_ports {key_in[49]}] [get_ports {key_in[48]}] [get_ports {key_in[47]}]     \
[get_ports {key_in[46]}] [get_ports {key_in[45]}] [get_ports {key_in[44]}]     \
[get_ports {key_in[43]}] [get_ports {key_in[42]}] [get_ports {key_in[41]}]     \
[get_ports {key_in[40]}] [get_ports {key_in[39]}] [get_ports {key_in[38]}]     \
[get_ports {key_in[37]}] [get_ports {key_in[36]}] [get_ports {key_in[35]}]     \
[get_ports {key_in[34]}] [get_ports {key_in[33]}] [get_ports {key_in[32]}]     \
[get_ports {key_in[31]}] [get_ports {key_in[30]}] [get_ports {key_in[29]}]     \
[get_ports {key_in[28]}] [get_ports {key_in[27]}] [get_ports {key_in[26]}]     \
[get_ports {key_in[25]}] [get_ports {key_in[24]}] [get_ports {key_in[23]}]     \
[get_ports {key_in[22]}] [get_ports {key_in[21]}] [get_ports {key_in[20]}]     \
[get_ports {key_in[19]}] [get_ports {key_in[18]}] [get_ports {key_in[17]}]     \
[get_ports {key_in[16]}] [get_ports {key_in[15]}] [get_ports {key_in[14]}]     \
[get_ports {key_in[13]}] [get_ports {key_in[12]}] [get_ports {key_in[11]}]     \
[get_ports {key_in[10]}] [get_ports {key_in[9]}] [get_ports {key_in[8]}]       \
[get_ports {key_in[7]}] [get_ports {key_in[6]}] [get_ports {key_in[5]}]        \
[get_ports {key_in[4]}] [get_ports {key_in[3]}] [get_ports {key_in[2]}]        \
[get_ports {key_in[1]}] [get_ports {key_in[0]}]]
group_path -name output_group  -to [list [get_ports {text_out[127]}] [get_ports {text_out[126]}] [get_ports  \
{text_out[125]}] [get_ports {text_out[124]}] [get_ports {text_out[123]}]       \
[get_ports {text_out[122]}] [get_ports {text_out[121]}] [get_ports             \
{text_out[120]}] [get_ports {text_out[119]}] [get_ports {text_out[118]}]       \
[get_ports {text_out[117]}] [get_ports {text_out[116]}] [get_ports             \
{text_out[115]}] [get_ports {text_out[114]}] [get_ports {text_out[113]}]       \
[get_ports {text_out[112]}] [get_ports {text_out[111]}] [get_ports             \
{text_out[110]}] [get_ports {text_out[109]}] [get_ports {text_out[108]}]       \
[get_ports {text_out[107]}] [get_ports {text_out[106]}] [get_ports             \
{text_out[105]}] [get_ports {text_out[104]}] [get_ports {text_out[103]}]       \
[get_ports {text_out[102]}] [get_ports {text_out[101]}] [get_ports             \
{text_out[100]}] [get_ports {text_out[99]}] [get_ports {text_out[98]}]         \
[get_ports {text_out[97]}] [get_ports {text_out[96]}] [get_ports               \
{text_out[95]}] [get_ports {text_out[94]}] [get_ports {text_out[93]}]          \
[get_ports {text_out[92]}] [get_ports {text_out[91]}] [get_ports               \
{text_out[90]}] [get_ports {text_out[89]}] [get_ports {text_out[88]}]          \
[get_ports {text_out[87]}] [get_ports {text_out[86]}] [get_ports               \
{text_out[85]}] [get_ports {text_out[84]}] [get_ports {text_out[83]}]          \
[get_ports {text_out[82]}] [get_ports {text_out[81]}] [get_ports               \
{text_out[80]}] [get_ports {text_out[79]}] [get_ports {text_out[78]}]          \
[get_ports {text_out[77]}] [get_ports {text_out[76]}] [get_ports               \
{text_out[75]}] [get_ports {text_out[74]}] [get_ports {text_out[73]}]          \
[get_ports {text_out[72]}] [get_ports {text_out[71]}] [get_ports               \
{text_out[70]}] [get_ports {text_out[69]}] [get_ports {text_out[68]}]          \
[get_ports {text_out[67]}] [get_ports {text_out[66]}] [get_ports               \
{text_out[65]}] [get_ports {text_out[64]}] [get_ports {text_out[63]}]          \
[get_ports {text_out[62]}] [get_ports {text_out[61]}] [get_ports               \
{text_out[60]}] [get_ports {text_out[59]}] [get_ports {text_out[58]}]          \
[get_ports {text_out[57]}] [get_ports {text_out[56]}] [get_ports               \
{text_out[55]}] [get_ports {text_out[54]}] [get_ports {text_out[53]}]          \
[get_ports {text_out[52]}] [get_ports {text_out[51]}] [get_ports               \
{text_out[50]}] [get_ports {text_out[49]}] [get_ports {text_out[48]}]          \
[get_ports {text_out[47]}] [get_ports {text_out[46]}] [get_ports               \
{text_out[45]}] [get_ports {text_out[44]}] [get_ports {text_out[43]}]          \
[get_ports {text_out[42]}] [get_ports {text_out[41]}] [get_ports               \
{text_out[40]}] [get_ports {text_out[39]}] [get_ports {text_out[38]}]          \
[get_ports {text_out[37]}] [get_ports {text_out[36]}] [get_ports               \
{text_out[35]}] [get_ports {text_out[34]}] [get_ports {text_out[33]}]          \
[get_ports {text_out[32]}] [get_ports {text_out[31]}] [get_ports               \
{text_out[30]}] [get_ports {text_out[29]}] [get_ports {text_out[28]}]          \
[get_ports {text_out[27]}] [get_ports {text_out[26]}] [get_ports               \
{text_out[25]}] [get_ports {text_out[24]}] [get_ports {text_out[23]}]          \
[get_ports {text_out[22]}] [get_ports {text_out[21]}] [get_ports               \
{text_out[20]}] [get_ports {text_out[19]}] [get_ports {text_out[18]}]          \
[get_ports {text_out[17]}] [get_ports {text_out[16]}] [get_ports               \
{text_out[15]}] [get_ports {text_out[14]}] [get_ports {text_out[13]}]          \
[get_ports {text_out[12]}] [get_ports {text_out[11]}] [get_ports               \
{text_out[10]}] [get_ports {text_out[9]}] [get_ports {text_out[8]}] [get_ports \
{text_out[7]}] [get_ports {text_out[6]}] [get_ports {text_out[5]}] [get_ports  \
{text_out[4]}] [get_ports {text_out[3]}] [get_ports {text_out[2]}] [get_ports  \
{text_out[1]}] [get_ports {text_out[0]}] [get_ports key_val] [get_ports        \
text_val] [get_ports busy]]
set_input_delay -clock CRYPTOCLK  -max 0.5  [get_ports resetn]
set_input_delay -clock CRYPTOCLK  -min 0  [get_ports resetn]
set_input_delay -clock CRYPTOCLK  -max 0.5  [get_ports enc_dec]
set_input_delay -clock CRYPTOCLK  -min 0  [get_ports enc_dec]
set_input_delay -clock CRYPTOCLK  -max 0.5  [get_ports key_exp]
set_input_delay -clock CRYPTOCLK  -min 0  [get_ports key_exp]
set_input_delay -clock CRYPTOCLK  -max 0.5  [get_ports start]
set_input_delay -clock CRYPTOCLK  -min 0  [get_ports start]
set_input_delay -clock CRYPTOCLK  -max 0.5  [get_ports {text_in[127]}]
set_input_delay -clock CRYPTOCLK  -min 0  [get_ports {text_in[127]}]
set_input_delay -clock CRYPTOCLK  -max 0.5  [get_ports {text_in[126]}]
set_input_delay -clock CRYPTOCLK  -min 0  [get_ports {text_in[126]}]
set_input_delay -clock CRYPTOCLK  -max 0.5  [get_ports {text_in[125]}]
set_input_delay -clock CRYPTOCLK  -min 0  [get_ports {text_in[125]}]
set_input_delay -clock CRYPTOCLK  -max 0.5  [get_ports {text_in[124]}]
set_input_delay -clock CRYPTOCLK  -min 0  [get_ports {text_in[124]}]
set_input_delay -clock CRYPTOCLK  -max 0.5  [get_ports {text_in[123]}]
set_input_delay -clock CRYPTOCLK  -min 0  [get_ports {text_in[123]}]
set_input_delay -clock CRYPTOCLK  -max 0.5  [get_ports {text_in[122]}]
set_input_delay -clock CRYPTOCLK  -min 0  [get_ports {text_in[122]}]
set_input_delay -clock CRYPTOCLK  -max 0.5  [get_ports {text_in[121]}]
set_input_delay -clock CRYPTOCLK  -min 0  [get_ports {text_in[121]}]
set_input_delay -clock CRYPTOCLK  -max 0.5  [get_ports {text_in[120]}]
set_input_delay -clock CRYPTOCLK  -min 0  [get_ports {text_in[120]}]
set_input_delay -clock CRYPTOCLK  -max 0.5  [get_ports {text_in[119]}]
set_input_delay -clock CRYPTOCLK  -min 0  [get_ports {text_in[119]}]
set_input_delay -clock CRYPTOCLK  -max 0.5  [get_ports {text_in[118]}]
set_input_delay -clock CRYPTOCLK  -min 0  [get_ports {text_in[118]}]
set_input_delay -clock CRYPTOCLK  -max 0.5  [get_ports {text_in[117]}]
set_input_delay -clock CRYPTOCLK  -min 0  [get_ports {text_in[117]}]
set_input_delay -clock CRYPTOCLK  -max 0.5  [get_ports {text_in[116]}]
set_input_delay -clock CRYPTOCLK  -min 0  [get_ports {text_in[116]}]
set_input_delay -clock CRYPTOCLK  -max 0.5  [get_ports {text_in[115]}]
set_input_delay -clock CRYPTOCLK  -min 0  [get_ports {text_in[115]}]
set_input_delay -clock CRYPTOCLK  -max 0.5  [get_ports {text_in[114]}]
set_input_delay -clock CRYPTOCLK  -min 0  [get_ports {text_in[114]}]
set_input_delay -clock CRYPTOCLK  -max 0.5  [get_ports {text_in[113]}]
set_input_delay -clock CRYPTOCLK  -min 0  [get_ports {text_in[113]}]
set_input_delay -clock CRYPTOCLK  -max 0.5  [get_ports {text_in[112]}]
set_input_delay -clock CRYPTOCLK  -min 0  [get_ports {text_in[112]}]
set_input_delay -clock CRYPTOCLK  -max 0.5  [get_ports {text_in[111]}]
set_input_delay -clock CRYPTOCLK  -min 0  [get_ports {text_in[111]}]
set_input_delay -clock CRYPTOCLK  -max 0.5  [get_ports {text_in[110]}]
set_input_delay -clock CRYPTOCLK  -min 0  [get_ports {text_in[110]}]
set_input_delay -clock CRYPTOCLK  -max 0.5  [get_ports {text_in[109]}]
set_input_delay -clock CRYPTOCLK  -min 0  [get_ports {text_in[109]}]
set_input_delay -clock CRYPTOCLK  -max 0.5  [get_ports {text_in[108]}]
set_input_delay -clock CRYPTOCLK  -min 0  [get_ports {text_in[108]}]
set_input_delay -clock CRYPTOCLK  -max 0.5  [get_ports {text_in[107]}]
set_input_delay -clock CRYPTOCLK  -min 0  [get_ports {text_in[107]}]
set_input_delay -clock CRYPTOCLK  -max 0.5  [get_ports {text_in[106]}]
set_input_delay -clock CRYPTOCLK  -min 0  [get_ports {text_in[106]}]
set_input_delay -clock CRYPTOCLK  -max 0.5  [get_ports {text_in[105]}]
set_input_delay -clock CRYPTOCLK  -min 0  [get_ports {text_in[105]}]
set_input_delay -clock CRYPTOCLK  -max 0.5  [get_ports {text_in[104]}]
set_input_delay -clock CRYPTOCLK  -min 0  [get_ports {text_in[104]}]
set_input_delay -clock CRYPTOCLK  -max 0.5  [get_ports {text_in[103]}]
set_input_delay -clock CRYPTOCLK  -min 0  [get_ports {text_in[103]}]
set_input_delay -clock CRYPTOCLK  -max 0.5  [get_ports {text_in[102]}]
set_input_delay -clock CRYPTOCLK  -min 0  [get_ports {text_in[102]}]
set_input_delay -clock CRYPTOCLK  -max 0.5  [get_ports {text_in[101]}]
set_input_delay -clock CRYPTOCLK  -min 0  [get_ports {text_in[101]}]
set_input_delay -clock CRYPTOCLK  -max 0.5  [get_ports {text_in[100]}]
set_input_delay -clock CRYPTOCLK  -min 0  [get_ports {text_in[100]}]
set_input_delay -clock CRYPTOCLK  -max 0.5  [get_ports {text_in[99]}]
set_input_delay -clock CRYPTOCLK  -min 0  [get_ports {text_in[99]}]
set_input_delay -clock CRYPTOCLK  -max 0.5  [get_ports {text_in[98]}]
set_input_delay -clock CRYPTOCLK  -min 0  [get_ports {text_in[98]}]
set_input_delay -clock CRYPTOCLK  -max 0.5  [get_ports {text_in[97]}]
set_input_delay -clock CRYPTOCLK  -min 0  [get_ports {text_in[97]}]
set_input_delay -clock CRYPTOCLK  -max 0.5  [get_ports {text_in[96]}]
set_input_delay -clock CRYPTOCLK  -min 0  [get_ports {text_in[96]}]
set_input_delay -clock CRYPTOCLK  -max 0.5  [get_ports {text_in[95]}]
set_input_delay -clock CRYPTOCLK  -min 0  [get_ports {text_in[95]}]
set_input_delay -clock CRYPTOCLK  -max 0.5  [get_ports {text_in[94]}]
set_input_delay -clock CRYPTOCLK  -min 0  [get_ports {text_in[94]}]
set_input_delay -clock CRYPTOCLK  -max 0.5  [get_ports {text_in[93]}]
set_input_delay -clock CRYPTOCLK  -min 0  [get_ports {text_in[93]}]
set_input_delay -clock CRYPTOCLK  -max 0.5  [get_ports {text_in[92]}]
set_input_delay -clock CRYPTOCLK  -min 0  [get_ports {text_in[92]}]
set_input_delay -clock CRYPTOCLK  -max 0.5  [get_ports {text_in[91]}]
set_input_delay -clock CRYPTOCLK  -min 0  [get_ports {text_in[91]}]
set_input_delay -clock CRYPTOCLK  -max 0.5  [get_ports {text_in[90]}]
set_input_delay -clock CRYPTOCLK  -min 0  [get_ports {text_in[90]}]
set_input_delay -clock CRYPTOCLK  -max 0.5  [get_ports {text_in[89]}]
set_input_delay -clock CRYPTOCLK  -min 0  [get_ports {text_in[89]}]
set_input_delay -clock CRYPTOCLK  -max 0.5  [get_ports {text_in[88]}]
set_input_delay -clock CRYPTOCLK  -min 0  [get_ports {text_in[88]}]
set_input_delay -clock CRYPTOCLK  -max 0.5  [get_ports {text_in[87]}]
set_input_delay -clock CRYPTOCLK  -min 0  [get_ports {text_in[87]}]
set_input_delay -clock CRYPTOCLK  -max 0.5  [get_ports {text_in[86]}]
set_input_delay -clock CRYPTOCLK  -min 0  [get_ports {text_in[86]}]
set_input_delay -clock CRYPTOCLK  -max 0.5  [get_ports {text_in[85]}]
set_input_delay -clock CRYPTOCLK  -min 0  [get_ports {text_in[85]}]
set_input_delay -clock CRYPTOCLK  -max 0.5  [get_ports {text_in[84]}]
set_input_delay -clock CRYPTOCLK  -min 0  [get_ports {text_in[84]}]
set_input_delay -clock CRYPTOCLK  -max 0.5  [get_ports {text_in[83]}]
set_input_delay -clock CRYPTOCLK  -min 0  [get_ports {text_in[83]}]
set_input_delay -clock CRYPTOCLK  -max 0.5  [get_ports {text_in[82]}]
set_input_delay -clock CRYPTOCLK  -min 0  [get_ports {text_in[82]}]
set_input_delay -clock CRYPTOCLK  -max 0.5  [get_ports {text_in[81]}]
set_input_delay -clock CRYPTOCLK  -min 0  [get_ports {text_in[81]}]
set_input_delay -clock CRYPTOCLK  -max 0.5  [get_ports {text_in[80]}]
set_input_delay -clock CRYPTOCLK  -min 0  [get_ports {text_in[80]}]
set_input_delay -clock CRYPTOCLK  -max 0.5  [get_ports {text_in[79]}]
set_input_delay -clock CRYPTOCLK  -min 0  [get_ports {text_in[79]}]
set_input_delay -clock CRYPTOCLK  -max 0.5  [get_ports {text_in[78]}]
set_input_delay -clock CRYPTOCLK  -min 0  [get_ports {text_in[78]}]
set_input_delay -clock CRYPTOCLK  -max 0.5  [get_ports {text_in[77]}]
set_input_delay -clock CRYPTOCLK  -min 0  [get_ports {text_in[77]}]
set_input_delay -clock CRYPTOCLK  -max 0.5  [get_ports {text_in[76]}]
set_input_delay -clock CRYPTOCLK  -min 0  [get_ports {text_in[76]}]
set_input_delay -clock CRYPTOCLK  -max 0.5  [get_ports {text_in[75]}]
set_input_delay -clock CRYPTOCLK  -min 0  [get_ports {text_in[75]}]
set_input_delay -clock CRYPTOCLK  -max 0.5  [get_ports {text_in[74]}]
set_input_delay -clock CRYPTOCLK  -min 0  [get_ports {text_in[74]}]
set_input_delay -clock CRYPTOCLK  -max 0.5  [get_ports {text_in[73]}]
set_input_delay -clock CRYPTOCLK  -min 0  [get_ports {text_in[73]}]
set_input_delay -clock CRYPTOCLK  -max 0.5  [get_ports {text_in[72]}]
set_input_delay -clock CRYPTOCLK  -min 0  [get_ports {text_in[72]}]
set_input_delay -clock CRYPTOCLK  -max 0.5  [get_ports {text_in[71]}]
set_input_delay -clock CRYPTOCLK  -min 0  [get_ports {text_in[71]}]
set_input_delay -clock CRYPTOCLK  -max 0.5  [get_ports {text_in[70]}]
set_input_delay -clock CRYPTOCLK  -min 0  [get_ports {text_in[70]}]
set_input_delay -clock CRYPTOCLK  -max 0.5  [get_ports {text_in[69]}]
set_input_delay -clock CRYPTOCLK  -min 0  [get_ports {text_in[69]}]
set_input_delay -clock CRYPTOCLK  -max 0.5  [get_ports {text_in[68]}]
set_input_delay -clock CRYPTOCLK  -min 0  [get_ports {text_in[68]}]
set_input_delay -clock CRYPTOCLK  -max 0.5  [get_ports {text_in[67]}]
set_input_delay -clock CRYPTOCLK  -min 0  [get_ports {text_in[67]}]
set_input_delay -clock CRYPTOCLK  -max 0.5  [get_ports {text_in[66]}]
set_input_delay -clock CRYPTOCLK  -min 0  [get_ports {text_in[66]}]
set_input_delay -clock CRYPTOCLK  -max 0.5  [get_ports {text_in[65]}]
set_input_delay -clock CRYPTOCLK  -min 0  [get_ports {text_in[65]}]
set_input_delay -clock CRYPTOCLK  -max 0.5  [get_ports {text_in[64]}]
set_input_delay -clock CRYPTOCLK  -min 0  [get_ports {text_in[64]}]
set_input_delay -clock CRYPTOCLK  -max 0.5  [get_ports {text_in[63]}]
set_input_delay -clock CRYPTOCLK  -min 0  [get_ports {text_in[63]}]
set_input_delay -clock CRYPTOCLK  -max 0.5  [get_ports {text_in[62]}]
set_input_delay -clock CRYPTOCLK  -min 0  [get_ports {text_in[62]}]
set_input_delay -clock CRYPTOCLK  -max 0.5  [get_ports {text_in[61]}]
set_input_delay -clock CRYPTOCLK  -min 0  [get_ports {text_in[61]}]
set_input_delay -clock CRYPTOCLK  -max 0.5  [get_ports {text_in[60]}]
set_input_delay -clock CRYPTOCLK  -min 0  [get_ports {text_in[60]}]
set_input_delay -clock CRYPTOCLK  -max 0.5  [get_ports {text_in[59]}]
set_input_delay -clock CRYPTOCLK  -min 0  [get_ports {text_in[59]}]
set_input_delay -clock CRYPTOCLK  -max 0.5  [get_ports {text_in[58]}]
set_input_delay -clock CRYPTOCLK  -min 0  [get_ports {text_in[58]}]
set_input_delay -clock CRYPTOCLK  -max 0.5  [get_ports {text_in[57]}]
set_input_delay -clock CRYPTOCLK  -min 0  [get_ports {text_in[57]}]
set_input_delay -clock CRYPTOCLK  -max 0.5  [get_ports {text_in[56]}]
set_input_delay -clock CRYPTOCLK  -min 0  [get_ports {text_in[56]}]
set_input_delay -clock CRYPTOCLK  -max 0.5  [get_ports {text_in[55]}]
set_input_delay -clock CRYPTOCLK  -min 0  [get_ports {text_in[55]}]
set_input_delay -clock CRYPTOCLK  -max 0.5  [get_ports {text_in[54]}]
set_input_delay -clock CRYPTOCLK  -min 0  [get_ports {text_in[54]}]
set_input_delay -clock CRYPTOCLK  -max 0.5  [get_ports {text_in[53]}]
set_input_delay -clock CRYPTOCLK  -min 0  [get_ports {text_in[53]}]
set_input_delay -clock CRYPTOCLK  -max 0.5  [get_ports {text_in[52]}]
set_input_delay -clock CRYPTOCLK  -min 0  [get_ports {text_in[52]}]
set_input_delay -clock CRYPTOCLK  -max 0.5  [get_ports {text_in[51]}]
set_input_delay -clock CRYPTOCLK  -min 0  [get_ports {text_in[51]}]
set_input_delay -clock CRYPTOCLK  -max 0.5  [get_ports {text_in[50]}]
set_input_delay -clock CRYPTOCLK  -min 0  [get_ports {text_in[50]}]
set_input_delay -clock CRYPTOCLK  -max 0.5  [get_ports {text_in[49]}]
set_input_delay -clock CRYPTOCLK  -min 0  [get_ports {text_in[49]}]
set_input_delay -clock CRYPTOCLK  -max 0.5  [get_ports {text_in[48]}]
set_input_delay -clock CRYPTOCLK  -min 0  [get_ports {text_in[48]}]
set_input_delay -clock CRYPTOCLK  -max 0.5  [get_ports {text_in[47]}]
set_input_delay -clock CRYPTOCLK  -min 0  [get_ports {text_in[47]}]
set_input_delay -clock CRYPTOCLK  -max 0.5  [get_ports {text_in[46]}]
set_input_delay -clock CRYPTOCLK  -min 0  [get_ports {text_in[46]}]
set_input_delay -clock CRYPTOCLK  -max 0.5  [get_ports {text_in[45]}]
set_input_delay -clock CRYPTOCLK  -min 0  [get_ports {text_in[45]}]
set_input_delay -clock CRYPTOCLK  -max 0.5  [get_ports {text_in[44]}]
set_input_delay -clock CRYPTOCLK  -min 0  [get_ports {text_in[44]}]
set_input_delay -clock CRYPTOCLK  -max 0.5  [get_ports {text_in[43]}]
set_input_delay -clock CRYPTOCLK  -min 0  [get_ports {text_in[43]}]
set_input_delay -clock CRYPTOCLK  -max 0.5  [get_ports {text_in[42]}]
set_input_delay -clock CRYPTOCLK  -min 0  [get_ports {text_in[42]}]
set_input_delay -clock CRYPTOCLK  -max 0.5  [get_ports {text_in[41]}]
set_input_delay -clock CRYPTOCLK  -min 0  [get_ports {text_in[41]}]
set_input_delay -clock CRYPTOCLK  -max 0.5  [get_ports {text_in[40]}]
set_input_delay -clock CRYPTOCLK  -min 0  [get_ports {text_in[40]}]
set_input_delay -clock CRYPTOCLK  -max 0.5  [get_ports {text_in[39]}]
set_input_delay -clock CRYPTOCLK  -min 0  [get_ports {text_in[39]}]
set_input_delay -clock CRYPTOCLK  -max 0.5  [get_ports {text_in[38]}]
set_input_delay -clock CRYPTOCLK  -min 0  [get_ports {text_in[38]}]
set_input_delay -clock CRYPTOCLK  -max 0.5  [get_ports {text_in[37]}]
set_input_delay -clock CRYPTOCLK  -min 0  [get_ports {text_in[37]}]
set_input_delay -clock CRYPTOCLK  -max 0.5  [get_ports {text_in[36]}]
set_input_delay -clock CRYPTOCLK  -min 0  [get_ports {text_in[36]}]
set_input_delay -clock CRYPTOCLK  -max 0.5  [get_ports {text_in[35]}]
set_input_delay -clock CRYPTOCLK  -min 0  [get_ports {text_in[35]}]
set_input_delay -clock CRYPTOCLK  -max 0.5  [get_ports {text_in[34]}]
set_input_delay -clock CRYPTOCLK  -min 0  [get_ports {text_in[34]}]
set_input_delay -clock CRYPTOCLK  -max 0.5  [get_ports {text_in[33]}]
set_input_delay -clock CRYPTOCLK  -min 0  [get_ports {text_in[33]}]
set_input_delay -clock CRYPTOCLK  -max 0.5  [get_ports {text_in[32]}]
set_input_delay -clock CRYPTOCLK  -min 0  [get_ports {text_in[32]}]
set_input_delay -clock CRYPTOCLK  -max 0.5  [get_ports {text_in[31]}]
set_input_delay -clock CRYPTOCLK  -min 0  [get_ports {text_in[31]}]
set_input_delay -clock CRYPTOCLK  -max 0.5  [get_ports {text_in[30]}]
set_input_delay -clock CRYPTOCLK  -min 0  [get_ports {text_in[30]}]
set_input_delay -clock CRYPTOCLK  -max 0.5  [get_ports {text_in[29]}]
set_input_delay -clock CRYPTOCLK  -min 0  [get_ports {text_in[29]}]
set_input_delay -clock CRYPTOCLK  -max 0.5  [get_ports {text_in[28]}]
set_input_delay -clock CRYPTOCLK  -min 0  [get_ports {text_in[28]}]
set_input_delay -clock CRYPTOCLK  -max 0.5  [get_ports {text_in[27]}]
set_input_delay -clock CRYPTOCLK  -min 0  [get_ports {text_in[27]}]
set_input_delay -clock CRYPTOCLK  -max 0.5  [get_ports {text_in[26]}]
set_input_delay -clock CRYPTOCLK  -min 0  [get_ports {text_in[26]}]
set_input_delay -clock CRYPTOCLK  -max 0.5  [get_ports {text_in[25]}]
set_input_delay -clock CRYPTOCLK  -min 0  [get_ports {text_in[25]}]
set_input_delay -clock CRYPTOCLK  -max 0.5  [get_ports {text_in[24]}]
set_input_delay -clock CRYPTOCLK  -min 0  [get_ports {text_in[24]}]
set_input_delay -clock CRYPTOCLK  -max 0.5  [get_ports {text_in[23]}]
set_input_delay -clock CRYPTOCLK  -min 0  [get_ports {text_in[23]}]
set_input_delay -clock CRYPTOCLK  -max 0.5  [get_ports {text_in[22]}]
set_input_delay -clock CRYPTOCLK  -min 0  [get_ports {text_in[22]}]
set_input_delay -clock CRYPTOCLK  -max 0.5  [get_ports {text_in[21]}]
set_input_delay -clock CRYPTOCLK  -min 0  [get_ports {text_in[21]}]
set_input_delay -clock CRYPTOCLK  -max 0.5  [get_ports {text_in[20]}]
set_input_delay -clock CRYPTOCLK  -min 0  [get_ports {text_in[20]}]
set_input_delay -clock CRYPTOCLK  -max 0.5  [get_ports {text_in[19]}]
set_input_delay -clock CRYPTOCLK  -min 0  [get_ports {text_in[19]}]
set_input_delay -clock CRYPTOCLK  -max 0.5  [get_ports {text_in[18]}]
set_input_delay -clock CRYPTOCLK  -min 0  [get_ports {text_in[18]}]
set_input_delay -clock CRYPTOCLK  -max 0.5  [get_ports {text_in[17]}]
set_input_delay -clock CRYPTOCLK  -min 0  [get_ports {text_in[17]}]
set_input_delay -clock CRYPTOCLK  -max 0.5  [get_ports {text_in[16]}]
set_input_delay -clock CRYPTOCLK  -min 0  [get_ports {text_in[16]}]
set_input_delay -clock CRYPTOCLK  -max 0.5  [get_ports {text_in[15]}]
set_input_delay -clock CRYPTOCLK  -min 0  [get_ports {text_in[15]}]
set_input_delay -clock CRYPTOCLK  -max 0.5  [get_ports {text_in[14]}]
set_input_delay -clock CRYPTOCLK  -min 0  [get_ports {text_in[14]}]
set_input_delay -clock CRYPTOCLK  -max 0.5  [get_ports {text_in[13]}]
set_input_delay -clock CRYPTOCLK  -min 0  [get_ports {text_in[13]}]
set_input_delay -clock CRYPTOCLK  -max 0.5  [get_ports {text_in[12]}]
set_input_delay -clock CRYPTOCLK  -min 0  [get_ports {text_in[12]}]
set_input_delay -clock CRYPTOCLK  -max 0.5  [get_ports {text_in[11]}]
set_input_delay -clock CRYPTOCLK  -min 0  [get_ports {text_in[11]}]
set_input_delay -clock CRYPTOCLK  -max 0.5  [get_ports {text_in[10]}]
set_input_delay -clock CRYPTOCLK  -min 0  [get_ports {text_in[10]}]
set_input_delay -clock CRYPTOCLK  -max 0.5  [get_ports {text_in[9]}]
set_input_delay -clock CRYPTOCLK  -min 0  [get_ports {text_in[9]}]
set_input_delay -clock CRYPTOCLK  -max 0.5  [get_ports {text_in[8]}]
set_input_delay -clock CRYPTOCLK  -min 0  [get_ports {text_in[8]}]
set_input_delay -clock CRYPTOCLK  -max 0.5  [get_ports {text_in[7]}]
set_input_delay -clock CRYPTOCLK  -min 0  [get_ports {text_in[7]}]
set_input_delay -clock CRYPTOCLK  -max 0.5  [get_ports {text_in[6]}]
set_input_delay -clock CRYPTOCLK  -min 0  [get_ports {text_in[6]}]
set_input_delay -clock CRYPTOCLK  -max 0.5  [get_ports {text_in[5]}]
set_input_delay -clock CRYPTOCLK  -min 0  [get_ports {text_in[5]}]
set_input_delay -clock CRYPTOCLK  -max 0.5  [get_ports {text_in[4]}]
set_input_delay -clock CRYPTOCLK  -min 0  [get_ports {text_in[4]}]
set_input_delay -clock CRYPTOCLK  -max 0.5  [get_ports {text_in[3]}]
set_input_delay -clock CRYPTOCLK  -min 0  [get_ports {text_in[3]}]
set_input_delay -clock CRYPTOCLK  -max 0.5  [get_ports {text_in[2]}]
set_input_delay -clock CRYPTOCLK  -min 0  [get_ports {text_in[2]}]
set_input_delay -clock CRYPTOCLK  -max 0.5  [get_ports {text_in[1]}]
set_input_delay -clock CRYPTOCLK  -min 0  [get_ports {text_in[1]}]
set_input_delay -clock CRYPTOCLK  -max 0.5  [get_ports {text_in[0]}]
set_input_delay -clock CRYPTOCLK  -min 0  [get_ports {text_in[0]}]
set_input_delay -clock CRYPTOCLK  -max 0.5  [get_ports {key_in[127]}]
set_input_delay -clock CRYPTOCLK  -min 0  [get_ports {key_in[127]}]
set_input_delay -clock CRYPTOCLK  -max 0.5  [get_ports {key_in[126]}]
set_input_delay -clock CRYPTOCLK  -min 0  [get_ports {key_in[126]}]
set_input_delay -clock CRYPTOCLK  -max 0.5  [get_ports {key_in[125]}]
set_input_delay -clock CRYPTOCLK  -min 0  [get_ports {key_in[125]}]
set_input_delay -clock CRYPTOCLK  -max 0.5  [get_ports {key_in[124]}]
set_input_delay -clock CRYPTOCLK  -min 0  [get_ports {key_in[124]}]
set_input_delay -clock CRYPTOCLK  -max 0.5  [get_ports {key_in[123]}]
set_input_delay -clock CRYPTOCLK  -min 0  [get_ports {key_in[123]}]
set_input_delay -clock CRYPTOCLK  -max 0.5  [get_ports {key_in[122]}]
set_input_delay -clock CRYPTOCLK  -min 0  [get_ports {key_in[122]}]
set_input_delay -clock CRYPTOCLK  -max 0.5  [get_ports {key_in[121]}]
set_input_delay -clock CRYPTOCLK  -min 0  [get_ports {key_in[121]}]
set_input_delay -clock CRYPTOCLK  -max 0.5  [get_ports {key_in[120]}]
set_input_delay -clock CRYPTOCLK  -min 0  [get_ports {key_in[120]}]
set_input_delay -clock CRYPTOCLK  -max 0.5  [get_ports {key_in[119]}]
set_input_delay -clock CRYPTOCLK  -min 0  [get_ports {key_in[119]}]
set_input_delay -clock CRYPTOCLK  -max 0.5  [get_ports {key_in[118]}]
set_input_delay -clock CRYPTOCLK  -min 0  [get_ports {key_in[118]}]
set_input_delay -clock CRYPTOCLK  -max 0.5  [get_ports {key_in[117]}]
set_input_delay -clock CRYPTOCLK  -min 0  [get_ports {key_in[117]}]
set_input_delay -clock CRYPTOCLK  -max 0.5  [get_ports {key_in[116]}]
set_input_delay -clock CRYPTOCLK  -min 0  [get_ports {key_in[116]}]
set_input_delay -clock CRYPTOCLK  -max 0.5  [get_ports {key_in[115]}]
set_input_delay -clock CRYPTOCLK  -min 0  [get_ports {key_in[115]}]
set_input_delay -clock CRYPTOCLK  -max 0.5  [get_ports {key_in[114]}]
set_input_delay -clock CRYPTOCLK  -min 0  [get_ports {key_in[114]}]
set_input_delay -clock CRYPTOCLK  -max 0.5  [get_ports {key_in[113]}]
set_input_delay -clock CRYPTOCLK  -min 0  [get_ports {key_in[113]}]
set_input_delay -clock CRYPTOCLK  -max 0.5  [get_ports {key_in[112]}]
set_input_delay -clock CRYPTOCLK  -min 0  [get_ports {key_in[112]}]
set_input_delay -clock CRYPTOCLK  -max 0.5  [get_ports {key_in[111]}]
set_input_delay -clock CRYPTOCLK  -min 0  [get_ports {key_in[111]}]
set_input_delay -clock CRYPTOCLK  -max 0.5  [get_ports {key_in[110]}]
set_input_delay -clock CRYPTOCLK  -min 0  [get_ports {key_in[110]}]
set_input_delay -clock CRYPTOCLK  -max 0.5  [get_ports {key_in[109]}]
set_input_delay -clock CRYPTOCLK  -min 0  [get_ports {key_in[109]}]
set_input_delay -clock CRYPTOCLK  -max 0.5  [get_ports {key_in[108]}]
set_input_delay -clock CRYPTOCLK  -min 0  [get_ports {key_in[108]}]
set_input_delay -clock CRYPTOCLK  -max 0.5  [get_ports {key_in[107]}]
set_input_delay -clock CRYPTOCLK  -min 0  [get_ports {key_in[107]}]
set_input_delay -clock CRYPTOCLK  -max 0.5  [get_ports {key_in[106]}]
set_input_delay -clock CRYPTOCLK  -min 0  [get_ports {key_in[106]}]
set_input_delay -clock CRYPTOCLK  -max 0.5  [get_ports {key_in[105]}]
set_input_delay -clock CRYPTOCLK  -min 0  [get_ports {key_in[105]}]
set_input_delay -clock CRYPTOCLK  -max 0.5  [get_ports {key_in[104]}]
set_input_delay -clock CRYPTOCLK  -min 0  [get_ports {key_in[104]}]
set_input_delay -clock CRYPTOCLK  -max 0.5  [get_ports {key_in[103]}]
set_input_delay -clock CRYPTOCLK  -min 0  [get_ports {key_in[103]}]
set_input_delay -clock CRYPTOCLK  -max 0.5  [get_ports {key_in[102]}]
set_input_delay -clock CRYPTOCLK  -min 0  [get_ports {key_in[102]}]
set_input_delay -clock CRYPTOCLK  -max 0.5  [get_ports {key_in[101]}]
set_input_delay -clock CRYPTOCLK  -min 0  [get_ports {key_in[101]}]
set_input_delay -clock CRYPTOCLK  -max 0.5  [get_ports {key_in[100]}]
set_input_delay -clock CRYPTOCLK  -min 0  [get_ports {key_in[100]}]
set_input_delay -clock CRYPTOCLK  -max 0.5  [get_ports {key_in[99]}]
set_input_delay -clock CRYPTOCLK  -min 0  [get_ports {key_in[99]}]
set_input_delay -clock CRYPTOCLK  -max 0.5  [get_ports {key_in[98]}]
set_input_delay -clock CRYPTOCLK  -min 0  [get_ports {key_in[98]}]
set_input_delay -clock CRYPTOCLK  -max 0.5  [get_ports {key_in[97]}]
set_input_delay -clock CRYPTOCLK  -min 0  [get_ports {key_in[97]}]
set_input_delay -clock CRYPTOCLK  -max 0.5  [get_ports {key_in[96]}]
set_input_delay -clock CRYPTOCLK  -min 0  [get_ports {key_in[96]}]
set_input_delay -clock CRYPTOCLK  -max 0.5  [get_ports {key_in[95]}]
set_input_delay -clock CRYPTOCLK  -min 0  [get_ports {key_in[95]}]
set_input_delay -clock CRYPTOCLK  -max 0.5  [get_ports {key_in[94]}]
set_input_delay -clock CRYPTOCLK  -min 0  [get_ports {key_in[94]}]
set_input_delay -clock CRYPTOCLK  -max 0.5  [get_ports {key_in[93]}]
set_input_delay -clock CRYPTOCLK  -min 0  [get_ports {key_in[93]}]
set_input_delay -clock CRYPTOCLK  -max 0.5  [get_ports {key_in[92]}]
set_input_delay -clock CRYPTOCLK  -min 0  [get_ports {key_in[92]}]
set_input_delay -clock CRYPTOCLK  -max 0.5  [get_ports {key_in[91]}]
set_input_delay -clock CRYPTOCLK  -min 0  [get_ports {key_in[91]}]
set_input_delay -clock CRYPTOCLK  -max 0.5  [get_ports {key_in[90]}]
set_input_delay -clock CRYPTOCLK  -min 0  [get_ports {key_in[90]}]
set_input_delay -clock CRYPTOCLK  -max 0.5  [get_ports {key_in[89]}]
set_input_delay -clock CRYPTOCLK  -min 0  [get_ports {key_in[89]}]
set_input_delay -clock CRYPTOCLK  -max 0.5  [get_ports {key_in[88]}]
set_input_delay -clock CRYPTOCLK  -min 0  [get_ports {key_in[88]}]
set_input_delay -clock CRYPTOCLK  -max 0.5  [get_ports {key_in[87]}]
set_input_delay -clock CRYPTOCLK  -min 0  [get_ports {key_in[87]}]
set_input_delay -clock CRYPTOCLK  -max 0.5  [get_ports {key_in[86]}]
set_input_delay -clock CRYPTOCLK  -min 0  [get_ports {key_in[86]}]
set_input_delay -clock CRYPTOCLK  -max 0.5  [get_ports {key_in[85]}]
set_input_delay -clock CRYPTOCLK  -min 0  [get_ports {key_in[85]}]
set_input_delay -clock CRYPTOCLK  -max 0.5  [get_ports {key_in[84]}]
set_input_delay -clock CRYPTOCLK  -min 0  [get_ports {key_in[84]}]
set_input_delay -clock CRYPTOCLK  -max 0.5  [get_ports {key_in[83]}]
set_input_delay -clock CRYPTOCLK  -min 0  [get_ports {key_in[83]}]
set_input_delay -clock CRYPTOCLK  -max 0.5  [get_ports {key_in[82]}]
set_input_delay -clock CRYPTOCLK  -min 0  [get_ports {key_in[82]}]
set_input_delay -clock CRYPTOCLK  -max 0.5  [get_ports {key_in[81]}]
set_input_delay -clock CRYPTOCLK  -min 0  [get_ports {key_in[81]}]
set_input_delay -clock CRYPTOCLK  -max 0.5  [get_ports {key_in[80]}]
set_input_delay -clock CRYPTOCLK  -min 0  [get_ports {key_in[80]}]
set_input_delay -clock CRYPTOCLK  -max 0.5  [get_ports {key_in[79]}]
set_input_delay -clock CRYPTOCLK  -min 0  [get_ports {key_in[79]}]
set_input_delay -clock CRYPTOCLK  -max 0.5  [get_ports {key_in[78]}]
set_input_delay -clock CRYPTOCLK  -min 0  [get_ports {key_in[78]}]
set_input_delay -clock CRYPTOCLK  -max 0.5  [get_ports {key_in[77]}]
set_input_delay -clock CRYPTOCLK  -min 0  [get_ports {key_in[77]}]
set_input_delay -clock CRYPTOCLK  -max 0.5  [get_ports {key_in[76]}]
set_input_delay -clock CRYPTOCLK  -min 0  [get_ports {key_in[76]}]
set_input_delay -clock CRYPTOCLK  -max 0.5  [get_ports {key_in[75]}]
set_input_delay -clock CRYPTOCLK  -min 0  [get_ports {key_in[75]}]
set_input_delay -clock CRYPTOCLK  -max 0.5  [get_ports {key_in[74]}]
set_input_delay -clock CRYPTOCLK  -min 0  [get_ports {key_in[74]}]
set_input_delay -clock CRYPTOCLK  -max 0.5  [get_ports {key_in[73]}]
set_input_delay -clock CRYPTOCLK  -min 0  [get_ports {key_in[73]}]
set_input_delay -clock CRYPTOCLK  -max 0.5  [get_ports {key_in[72]}]
set_input_delay -clock CRYPTOCLK  -min 0  [get_ports {key_in[72]}]
set_input_delay -clock CRYPTOCLK  -max 0.5  [get_ports {key_in[71]}]
set_input_delay -clock CRYPTOCLK  -min 0  [get_ports {key_in[71]}]
set_input_delay -clock CRYPTOCLK  -max 0.5  [get_ports {key_in[70]}]
set_input_delay -clock CRYPTOCLK  -min 0  [get_ports {key_in[70]}]
set_input_delay -clock CRYPTOCLK  -max 0.5  [get_ports {key_in[69]}]
set_input_delay -clock CRYPTOCLK  -min 0  [get_ports {key_in[69]}]
set_input_delay -clock CRYPTOCLK  -max 0.5  [get_ports {key_in[68]}]
set_input_delay -clock CRYPTOCLK  -min 0  [get_ports {key_in[68]}]
set_input_delay -clock CRYPTOCLK  -max 0.5  [get_ports {key_in[67]}]
set_input_delay -clock CRYPTOCLK  -min 0  [get_ports {key_in[67]}]
set_input_delay -clock CRYPTOCLK  -max 0.5  [get_ports {key_in[66]}]
set_input_delay -clock CRYPTOCLK  -min 0  [get_ports {key_in[66]}]
set_input_delay -clock CRYPTOCLK  -max 0.5  [get_ports {key_in[65]}]
set_input_delay -clock CRYPTOCLK  -min 0  [get_ports {key_in[65]}]
set_input_delay -clock CRYPTOCLK  -max 0.5  [get_ports {key_in[64]}]
set_input_delay -clock CRYPTOCLK  -min 0  [get_ports {key_in[64]}]
set_input_delay -clock CRYPTOCLK  -max 0.5  [get_ports {key_in[63]}]
set_input_delay -clock CRYPTOCLK  -min 0  [get_ports {key_in[63]}]
set_input_delay -clock CRYPTOCLK  -max 0.5  [get_ports {key_in[62]}]
set_input_delay -clock CRYPTOCLK  -min 0  [get_ports {key_in[62]}]
set_input_delay -clock CRYPTOCLK  -max 0.5  [get_ports {key_in[61]}]
set_input_delay -clock CRYPTOCLK  -min 0  [get_ports {key_in[61]}]
set_input_delay -clock CRYPTOCLK  -max 0.5  [get_ports {key_in[60]}]
set_input_delay -clock CRYPTOCLK  -min 0  [get_ports {key_in[60]}]
set_input_delay -clock CRYPTOCLK  -max 0.5  [get_ports {key_in[59]}]
set_input_delay -clock CRYPTOCLK  -min 0  [get_ports {key_in[59]}]
set_input_delay -clock CRYPTOCLK  -max 0.5  [get_ports {key_in[58]}]
set_input_delay -clock CRYPTOCLK  -min 0  [get_ports {key_in[58]}]
set_input_delay -clock CRYPTOCLK  -max 0.5  [get_ports {key_in[57]}]
set_input_delay -clock CRYPTOCLK  -min 0  [get_ports {key_in[57]}]
set_input_delay -clock CRYPTOCLK  -max 0.5  [get_ports {key_in[56]}]
set_input_delay -clock CRYPTOCLK  -min 0  [get_ports {key_in[56]}]
set_input_delay -clock CRYPTOCLK  -max 0.5  [get_ports {key_in[55]}]
set_input_delay -clock CRYPTOCLK  -min 0  [get_ports {key_in[55]}]
set_input_delay -clock CRYPTOCLK  -max 0.5  [get_ports {key_in[54]}]
set_input_delay -clock CRYPTOCLK  -min 0  [get_ports {key_in[54]}]
set_input_delay -clock CRYPTOCLK  -max 0.5  [get_ports {key_in[53]}]
set_input_delay -clock CRYPTOCLK  -min 0  [get_ports {key_in[53]}]
set_input_delay -clock CRYPTOCLK  -max 0.5  [get_ports {key_in[52]}]
set_input_delay -clock CRYPTOCLK  -min 0  [get_ports {key_in[52]}]
set_input_delay -clock CRYPTOCLK  -max 0.5  [get_ports {key_in[51]}]
set_input_delay -clock CRYPTOCLK  -min 0  [get_ports {key_in[51]}]
set_input_delay -clock CRYPTOCLK  -max 0.5  [get_ports {key_in[50]}]
set_input_delay -clock CRYPTOCLK  -min 0  [get_ports {key_in[50]}]
set_input_delay -clock CRYPTOCLK  -max 0.5  [get_ports {key_in[49]}]
set_input_delay -clock CRYPTOCLK  -min 0  [get_ports {key_in[49]}]
set_input_delay -clock CRYPTOCLK  -max 0.5  [get_ports {key_in[48]}]
set_input_delay -clock CRYPTOCLK  -min 0  [get_ports {key_in[48]}]
set_input_delay -clock CRYPTOCLK  -max 0.5  [get_ports {key_in[47]}]
set_input_delay -clock CRYPTOCLK  -min 0  [get_ports {key_in[47]}]
set_input_delay -clock CRYPTOCLK  -max 0.5  [get_ports {key_in[46]}]
set_input_delay -clock CRYPTOCLK  -min 0  [get_ports {key_in[46]}]
set_input_delay -clock CRYPTOCLK  -max 0.5  [get_ports {key_in[45]}]
set_input_delay -clock CRYPTOCLK  -min 0  [get_ports {key_in[45]}]
set_input_delay -clock CRYPTOCLK  -max 0.5  [get_ports {key_in[44]}]
set_input_delay -clock CRYPTOCLK  -min 0  [get_ports {key_in[44]}]
set_input_delay -clock CRYPTOCLK  -max 0.5  [get_ports {key_in[43]}]
set_input_delay -clock CRYPTOCLK  -min 0  [get_ports {key_in[43]}]
set_input_delay -clock CRYPTOCLK  -max 0.5  [get_ports {key_in[42]}]
set_input_delay -clock CRYPTOCLK  -min 0  [get_ports {key_in[42]}]
set_input_delay -clock CRYPTOCLK  -max 0.5  [get_ports {key_in[41]}]
set_input_delay -clock CRYPTOCLK  -min 0  [get_ports {key_in[41]}]
set_input_delay -clock CRYPTOCLK  -max 0.5  [get_ports {key_in[40]}]
set_input_delay -clock CRYPTOCLK  -min 0  [get_ports {key_in[40]}]
set_input_delay -clock CRYPTOCLK  -max 0.5  [get_ports {key_in[39]}]
set_input_delay -clock CRYPTOCLK  -min 0  [get_ports {key_in[39]}]
set_input_delay -clock CRYPTOCLK  -max 0.5  [get_ports {key_in[38]}]
set_input_delay -clock CRYPTOCLK  -min 0  [get_ports {key_in[38]}]
set_input_delay -clock CRYPTOCLK  -max 0.5  [get_ports {key_in[37]}]
set_input_delay -clock CRYPTOCLK  -min 0  [get_ports {key_in[37]}]
set_input_delay -clock CRYPTOCLK  -max 0.5  [get_ports {key_in[36]}]
set_input_delay -clock CRYPTOCLK  -min 0  [get_ports {key_in[36]}]
set_input_delay -clock CRYPTOCLK  -max 0.5  [get_ports {key_in[35]}]
set_input_delay -clock CRYPTOCLK  -min 0  [get_ports {key_in[35]}]
set_input_delay -clock CRYPTOCLK  -max 0.5  [get_ports {key_in[34]}]
set_input_delay -clock CRYPTOCLK  -min 0  [get_ports {key_in[34]}]
set_input_delay -clock CRYPTOCLK  -max 0.5  [get_ports {key_in[33]}]
set_input_delay -clock CRYPTOCLK  -min 0  [get_ports {key_in[33]}]
set_input_delay -clock CRYPTOCLK  -max 0.5  [get_ports {key_in[32]}]
set_input_delay -clock CRYPTOCLK  -min 0  [get_ports {key_in[32]}]
set_input_delay -clock CRYPTOCLK  -max 0.5  [get_ports {key_in[31]}]
set_input_delay -clock CRYPTOCLK  -min 0  [get_ports {key_in[31]}]
set_input_delay -clock CRYPTOCLK  -max 0.5  [get_ports {key_in[30]}]
set_input_delay -clock CRYPTOCLK  -min 0  [get_ports {key_in[30]}]
set_input_delay -clock CRYPTOCLK  -max 0.5  [get_ports {key_in[29]}]
set_input_delay -clock CRYPTOCLK  -min 0  [get_ports {key_in[29]}]
set_input_delay -clock CRYPTOCLK  -max 0.5  [get_ports {key_in[28]}]
set_input_delay -clock CRYPTOCLK  -min 0  [get_ports {key_in[28]}]
set_input_delay -clock CRYPTOCLK  -max 0.5  [get_ports {key_in[27]}]
set_input_delay -clock CRYPTOCLK  -min 0  [get_ports {key_in[27]}]
set_input_delay -clock CRYPTOCLK  -max 0.5  [get_ports {key_in[26]}]
set_input_delay -clock CRYPTOCLK  -min 0  [get_ports {key_in[26]}]
set_input_delay -clock CRYPTOCLK  -max 0.5  [get_ports {key_in[25]}]
set_input_delay -clock CRYPTOCLK  -min 0  [get_ports {key_in[25]}]
set_input_delay -clock CRYPTOCLK  -max 0.5  [get_ports {key_in[24]}]
set_input_delay -clock CRYPTOCLK  -min 0  [get_ports {key_in[24]}]
set_input_delay -clock CRYPTOCLK  -max 0.5  [get_ports {key_in[23]}]
set_input_delay -clock CRYPTOCLK  -min 0  [get_ports {key_in[23]}]
set_input_delay -clock CRYPTOCLK  -max 0.5  [get_ports {key_in[22]}]
set_input_delay -clock CRYPTOCLK  -min 0  [get_ports {key_in[22]}]
set_input_delay -clock CRYPTOCLK  -max 0.5  [get_ports {key_in[21]}]
set_input_delay -clock CRYPTOCLK  -min 0  [get_ports {key_in[21]}]
set_input_delay -clock CRYPTOCLK  -max 0.5  [get_ports {key_in[20]}]
set_input_delay -clock CRYPTOCLK  -min 0  [get_ports {key_in[20]}]
set_input_delay -clock CRYPTOCLK  -max 0.5  [get_ports {key_in[19]}]
set_input_delay -clock CRYPTOCLK  -min 0  [get_ports {key_in[19]}]
set_input_delay -clock CRYPTOCLK  -max 0.5  [get_ports {key_in[18]}]
set_input_delay -clock CRYPTOCLK  -min 0  [get_ports {key_in[18]}]
set_input_delay -clock CRYPTOCLK  -max 0.5  [get_ports {key_in[17]}]
set_input_delay -clock CRYPTOCLK  -min 0  [get_ports {key_in[17]}]
set_input_delay -clock CRYPTOCLK  -max 0.5  [get_ports {key_in[16]}]
set_input_delay -clock CRYPTOCLK  -min 0  [get_ports {key_in[16]}]
set_input_delay -clock CRYPTOCLK  -max 0.5  [get_ports {key_in[15]}]
set_input_delay -clock CRYPTOCLK  -min 0  [get_ports {key_in[15]}]
set_input_delay -clock CRYPTOCLK  -max 0.5  [get_ports {key_in[14]}]
set_input_delay -clock CRYPTOCLK  -min 0  [get_ports {key_in[14]}]
set_input_delay -clock CRYPTOCLK  -max 0.5  [get_ports {key_in[13]}]
set_input_delay -clock CRYPTOCLK  -min 0  [get_ports {key_in[13]}]
set_input_delay -clock CRYPTOCLK  -max 0.5  [get_ports {key_in[12]}]
set_input_delay -clock CRYPTOCLK  -min 0  [get_ports {key_in[12]}]
set_input_delay -clock CRYPTOCLK  -max 0.5  [get_ports {key_in[11]}]
set_input_delay -clock CRYPTOCLK  -min 0  [get_ports {key_in[11]}]
set_input_delay -clock CRYPTOCLK  -max 0.5  [get_ports {key_in[10]}]
set_input_delay -clock CRYPTOCLK  -min 0  [get_ports {key_in[10]}]
set_input_delay -clock CRYPTOCLK  -max 0.5  [get_ports {key_in[9]}]
set_input_delay -clock CRYPTOCLK  -min 0  [get_ports {key_in[9]}]
set_input_delay -clock CRYPTOCLK  -max 0.5  [get_ports {key_in[8]}]
set_input_delay -clock CRYPTOCLK  -min 0  [get_ports {key_in[8]}]
set_input_delay -clock CRYPTOCLK  -max 0.5  [get_ports {key_in[7]}]
set_input_delay -clock CRYPTOCLK  -min 0  [get_ports {key_in[7]}]
set_input_delay -clock CRYPTOCLK  -max 0.5  [get_ports {key_in[6]}]
set_input_delay -clock CRYPTOCLK  -min 0  [get_ports {key_in[6]}]
set_input_delay -clock CRYPTOCLK  -max 0.5  [get_ports {key_in[5]}]
set_input_delay -clock CRYPTOCLK  -min 0  [get_ports {key_in[5]}]
set_input_delay -clock CRYPTOCLK  -max 0.5  [get_ports {key_in[4]}]
set_input_delay -clock CRYPTOCLK  -min 0  [get_ports {key_in[4]}]
set_input_delay -clock CRYPTOCLK  -max 0.5  [get_ports {key_in[3]}]
set_input_delay -clock CRYPTOCLK  -min 0  [get_ports {key_in[3]}]
set_input_delay -clock CRYPTOCLK  -max 0.5  [get_ports {key_in[2]}]
set_input_delay -clock CRYPTOCLK  -min 0  [get_ports {key_in[2]}]
set_input_delay -clock CRYPTOCLK  -max 0.5  [get_ports {key_in[1]}]
set_input_delay -clock CRYPTOCLK  -min 0  [get_ports {key_in[1]}]
set_input_delay -clock CRYPTOCLK  -max 0.5  [get_ports {key_in[0]}]
set_input_delay -clock CRYPTOCLK  -min 0  [get_ports {key_in[0]}]
set_output_delay -clock CRYPTOCLK  0.5  [get_ports {text_out[127]}]
set_output_delay -clock CRYPTOCLK  0.5  [get_ports {text_out[126]}]
set_output_delay -clock CRYPTOCLK  0.5  [get_ports {text_out[125]}]
set_output_delay -clock CRYPTOCLK  0.5  [get_ports {text_out[124]}]
set_output_delay -clock CRYPTOCLK  0.5  [get_ports {text_out[123]}]
set_output_delay -clock CRYPTOCLK  0.5  [get_ports {text_out[122]}]
set_output_delay -clock CRYPTOCLK  0.5  [get_ports {text_out[121]}]
set_output_delay -clock CRYPTOCLK  0.5  [get_ports {text_out[120]}]
set_output_delay -clock CRYPTOCLK  0.5  [get_ports {text_out[119]}]
set_output_delay -clock CRYPTOCLK  0.5  [get_ports {text_out[118]}]
set_output_delay -clock CRYPTOCLK  0.5  [get_ports {text_out[117]}]
set_output_delay -clock CRYPTOCLK  0.5  [get_ports {text_out[116]}]
set_output_delay -clock CRYPTOCLK  0.5  [get_ports {text_out[115]}]
set_output_delay -clock CRYPTOCLK  0.5  [get_ports {text_out[114]}]
set_output_delay -clock CRYPTOCLK  0.5  [get_ports {text_out[113]}]
set_output_delay -clock CRYPTOCLK  0.5  [get_ports {text_out[112]}]
set_output_delay -clock CRYPTOCLK  0.5  [get_ports {text_out[111]}]
set_output_delay -clock CRYPTOCLK  0.5  [get_ports {text_out[110]}]
set_output_delay -clock CRYPTOCLK  0.5  [get_ports {text_out[109]}]
set_output_delay -clock CRYPTOCLK  0.5  [get_ports {text_out[108]}]
set_output_delay -clock CRYPTOCLK  0.5  [get_ports {text_out[107]}]
set_output_delay -clock CRYPTOCLK  0.5  [get_ports {text_out[106]}]
set_output_delay -clock CRYPTOCLK  0.5  [get_ports {text_out[105]}]
set_output_delay -clock CRYPTOCLK  0.5  [get_ports {text_out[104]}]
set_output_delay -clock CRYPTOCLK  0.5  [get_ports {text_out[103]}]
set_output_delay -clock CRYPTOCLK  0.5  [get_ports {text_out[102]}]
set_output_delay -clock CRYPTOCLK  0.5  [get_ports {text_out[101]}]
set_output_delay -clock CRYPTOCLK  0.5  [get_ports {text_out[100]}]
set_output_delay -clock CRYPTOCLK  0.5  [get_ports {text_out[99]}]
set_output_delay -clock CRYPTOCLK  0.5  [get_ports {text_out[98]}]
set_output_delay -clock CRYPTOCLK  0.5  [get_ports {text_out[97]}]
set_output_delay -clock CRYPTOCLK  0.5  [get_ports {text_out[96]}]
set_output_delay -clock CRYPTOCLK  0.5  [get_ports {text_out[95]}]
set_output_delay -clock CRYPTOCLK  0.5  [get_ports {text_out[94]}]
set_output_delay -clock CRYPTOCLK  0.5  [get_ports {text_out[93]}]
set_output_delay -clock CRYPTOCLK  0.5  [get_ports {text_out[92]}]
set_output_delay -clock CRYPTOCLK  0.5  [get_ports {text_out[91]}]
set_output_delay -clock CRYPTOCLK  0.5  [get_ports {text_out[90]}]
set_output_delay -clock CRYPTOCLK  0.5  [get_ports {text_out[89]}]
set_output_delay -clock CRYPTOCLK  0.5  [get_ports {text_out[88]}]
set_output_delay -clock CRYPTOCLK  0.5  [get_ports {text_out[87]}]
set_output_delay -clock CRYPTOCLK  0.5  [get_ports {text_out[86]}]
set_output_delay -clock CRYPTOCLK  0.5  [get_ports {text_out[85]}]
set_output_delay -clock CRYPTOCLK  0.5  [get_ports {text_out[84]}]
set_output_delay -clock CRYPTOCLK  0.5  [get_ports {text_out[83]}]
set_output_delay -clock CRYPTOCLK  0.5  [get_ports {text_out[82]}]
set_output_delay -clock CRYPTOCLK  0.5  [get_ports {text_out[81]}]
set_output_delay -clock CRYPTOCLK  0.5  [get_ports {text_out[80]}]
set_output_delay -clock CRYPTOCLK  0.5  [get_ports {text_out[79]}]
set_output_delay -clock CRYPTOCLK  0.5  [get_ports {text_out[78]}]
set_output_delay -clock CRYPTOCLK  0.5  [get_ports {text_out[77]}]
set_output_delay -clock CRYPTOCLK  0.5  [get_ports {text_out[76]}]
set_output_delay -clock CRYPTOCLK  0.5  [get_ports {text_out[75]}]
set_output_delay -clock CRYPTOCLK  0.5  [get_ports {text_out[74]}]
set_output_delay -clock CRYPTOCLK  0.5  [get_ports {text_out[73]}]
set_output_delay -clock CRYPTOCLK  0.5  [get_ports {text_out[72]}]
set_output_delay -clock CRYPTOCLK  0.5  [get_ports {text_out[71]}]
set_output_delay -clock CRYPTOCLK  0.5  [get_ports {text_out[70]}]
set_output_delay -clock CRYPTOCLK  0.5  [get_ports {text_out[69]}]
set_output_delay -clock CRYPTOCLK  0.5  [get_ports {text_out[68]}]
set_output_delay -clock CRYPTOCLK  0.5  [get_ports {text_out[67]}]
set_output_delay -clock CRYPTOCLK  0.5  [get_ports {text_out[66]}]
set_output_delay -clock CRYPTOCLK  0.5  [get_ports {text_out[65]}]
set_output_delay -clock CRYPTOCLK  0.5  [get_ports {text_out[64]}]
set_output_delay -clock CRYPTOCLK  0.5  [get_ports {text_out[63]}]
set_output_delay -clock CRYPTOCLK  0.5  [get_ports {text_out[62]}]
set_output_delay -clock CRYPTOCLK  0.5  [get_ports {text_out[61]}]
set_output_delay -clock CRYPTOCLK  0.5  [get_ports {text_out[60]}]
set_output_delay -clock CRYPTOCLK  0.5  [get_ports {text_out[59]}]
set_output_delay -clock CRYPTOCLK  0.5  [get_ports {text_out[58]}]
set_output_delay -clock CRYPTOCLK  0.5  [get_ports {text_out[57]}]
set_output_delay -clock CRYPTOCLK  0.5  [get_ports {text_out[56]}]
set_output_delay -clock CRYPTOCLK  0.5  [get_ports {text_out[55]}]
set_output_delay -clock CRYPTOCLK  0.5  [get_ports {text_out[54]}]
set_output_delay -clock CRYPTOCLK  0.5  [get_ports {text_out[53]}]
set_output_delay -clock CRYPTOCLK  0.5  [get_ports {text_out[52]}]
set_output_delay -clock CRYPTOCLK  0.5  [get_ports {text_out[51]}]
set_output_delay -clock CRYPTOCLK  0.5  [get_ports {text_out[50]}]
set_output_delay -clock CRYPTOCLK  0.5  [get_ports {text_out[49]}]
set_output_delay -clock CRYPTOCLK  0.5  [get_ports {text_out[48]}]
set_output_delay -clock CRYPTOCLK  0.5  [get_ports {text_out[47]}]
set_output_delay -clock CRYPTOCLK  0.5  [get_ports {text_out[46]}]
set_output_delay -clock CRYPTOCLK  0.5  [get_ports {text_out[45]}]
set_output_delay -clock CRYPTOCLK  0.5  [get_ports {text_out[44]}]
set_output_delay -clock CRYPTOCLK  0.5  [get_ports {text_out[43]}]
set_output_delay -clock CRYPTOCLK  0.5  [get_ports {text_out[42]}]
set_output_delay -clock CRYPTOCLK  0.5  [get_ports {text_out[41]}]
set_output_delay -clock CRYPTOCLK  0.5  [get_ports {text_out[40]}]
set_output_delay -clock CRYPTOCLK  0.5  [get_ports {text_out[39]}]
set_output_delay -clock CRYPTOCLK  0.5  [get_ports {text_out[38]}]
set_output_delay -clock CRYPTOCLK  0.5  [get_ports {text_out[37]}]
set_output_delay -clock CRYPTOCLK  0.5  [get_ports {text_out[36]}]
set_output_delay -clock CRYPTOCLK  0.5  [get_ports {text_out[35]}]
set_output_delay -clock CRYPTOCLK  0.5  [get_ports {text_out[34]}]
set_output_delay -clock CRYPTOCLK  0.5  [get_ports {text_out[33]}]
set_output_delay -clock CRYPTOCLK  0.5  [get_ports {text_out[32]}]
set_output_delay -clock CRYPTOCLK  0.5  [get_ports {text_out[31]}]
set_output_delay -clock CRYPTOCLK  0.5  [get_ports {text_out[30]}]
set_output_delay -clock CRYPTOCLK  0.5  [get_ports {text_out[29]}]
set_output_delay -clock CRYPTOCLK  0.5  [get_ports {text_out[28]}]
set_output_delay -clock CRYPTOCLK  0.5  [get_ports {text_out[27]}]
set_output_delay -clock CRYPTOCLK  0.5  [get_ports {text_out[26]}]
set_output_delay -clock CRYPTOCLK  0.5  [get_ports {text_out[25]}]
set_output_delay -clock CRYPTOCLK  0.5  [get_ports {text_out[24]}]
set_output_delay -clock CRYPTOCLK  0.5  [get_ports {text_out[23]}]
set_output_delay -clock CRYPTOCLK  0.5  [get_ports {text_out[22]}]
set_output_delay -clock CRYPTOCLK  0.5  [get_ports {text_out[21]}]
set_output_delay -clock CRYPTOCLK  0.5  [get_ports {text_out[20]}]
set_output_delay -clock CRYPTOCLK  0.5  [get_ports {text_out[19]}]
set_output_delay -clock CRYPTOCLK  0.5  [get_ports {text_out[18]}]
set_output_delay -clock CRYPTOCLK  0.5  [get_ports {text_out[17]}]
set_output_delay -clock CRYPTOCLK  0.5  [get_ports {text_out[16]}]
set_output_delay -clock CRYPTOCLK  0.5  [get_ports {text_out[15]}]
set_output_delay -clock CRYPTOCLK  0.5  [get_ports {text_out[14]}]
set_output_delay -clock CRYPTOCLK  0.5  [get_ports {text_out[13]}]
set_output_delay -clock CRYPTOCLK  0.5  [get_ports {text_out[12]}]
set_output_delay -clock CRYPTOCLK  0.5  [get_ports {text_out[11]}]
set_output_delay -clock CRYPTOCLK  0.5  [get_ports {text_out[10]}]
set_output_delay -clock CRYPTOCLK  0.5  [get_ports {text_out[9]}]
set_output_delay -clock CRYPTOCLK  0.5  [get_ports {text_out[8]}]
set_output_delay -clock CRYPTOCLK  0.5  [get_ports {text_out[7]}]
set_output_delay -clock CRYPTOCLK  0.5  [get_ports {text_out[6]}]
set_output_delay -clock CRYPTOCLK  0.5  [get_ports {text_out[5]}]
set_output_delay -clock CRYPTOCLK  0.5  [get_ports {text_out[4]}]
set_output_delay -clock CRYPTOCLK  0.5  [get_ports {text_out[3]}]
set_output_delay -clock CRYPTOCLK  0.5  [get_ports {text_out[2]}]
set_output_delay -clock CRYPTOCLK  0.5  [get_ports {text_out[1]}]
set_output_delay -clock CRYPTOCLK  0.5  [get_ports {text_out[0]}]
set_output_delay -clock CRYPTOCLK  0.5  [get_ports key_val]
set_output_delay -clock CRYPTOCLK  0.5  [get_ports text_val]
set_output_delay -clock CRYPTOCLK  0.5  [get_ports busy]
