###################################################################

# Created by write_sdc on Thu Jan 13 13:06:31 2022

###################################################################
set sdc_version 2.0

set_units -time ns -resistance MOhm -capacitance fF -voltage V -current mA
create_clock [get_ports clock]  -name CRYPTOCLK  -period 10  -waveform {0 5}
group_path -name input_group  -from [list [get_ports clock] [get_ports reset_n] [get_ports load] [get_ports \
{key[79]}] [get_ports {key[78]}] [get_ports {key[77]}] [get_ports {key[76]}]   \
[get_ports {key[75]}] [get_ports {key[74]}] [get_ports {key[73]}] [get_ports   \
{key[72]}] [get_ports {key[71]}] [get_ports {key[70]}] [get_ports {key[69]}]   \
[get_ports {key[68]}] [get_ports {key[67]}] [get_ports {key[66]}] [get_ports   \
{key[65]}] [get_ports {key[64]}] [get_ports {key[63]}] [get_ports {key[62]}]   \
[get_ports {key[61]}] [get_ports {key[60]}] [get_ports {key[59]}] [get_ports   \
{key[58]}] [get_ports {key[57]}] [get_ports {key[56]}] [get_ports {key[55]}]   \
[get_ports {key[54]}] [get_ports {key[53]}] [get_ports {key[52]}] [get_ports   \
{key[51]}] [get_ports {key[50]}] [get_ports {key[49]}] [get_ports {key[48]}]   \
[get_ports {key[47]}] [get_ports {key[46]}] [get_ports {key[45]}] [get_ports   \
{key[44]}] [get_ports {key[43]}] [get_ports {key[42]}] [get_ports {key[41]}]   \
[get_ports {key[40]}] [get_ports {key[39]}] [get_ports {key[38]}] [get_ports   \
{key[37]}] [get_ports {key[36]}] [get_ports {key[35]}] [get_ports {key[34]}]   \
[get_ports {key[33]}] [get_ports {key[32]}] [get_ports {key[31]}] [get_ports   \
{key[30]}] [get_ports {key[29]}] [get_ports {key[28]}] [get_ports {key[27]}]   \
[get_ports {key[26]}] [get_ports {key[25]}] [get_ports {key[24]}] [get_ports   \
{key[23]}] [get_ports {key[22]}] [get_ports {key[21]}] [get_ports {key[20]}]   \
[get_ports {key[19]}] [get_ports {key[18]}] [get_ports {key[17]}] [get_ports   \
{key[16]}] [get_ports {key[15]}] [get_ports {key[14]}] [get_ports {key[13]}]   \
[get_ports {key[12]}] [get_ports {key[11]}] [get_ports {key[10]}] [get_ports   \
{key[9]}] [get_ports {key[8]}] [get_ports {key[7]}] [get_ports {key[6]}]       \
[get_ports {key[5]}] [get_ports {key[4]}] [get_ports {key[3]}] [get_ports      \
{key[2]}] [get_ports {key[1]}] [get_ports {key[0]}] [get_ports {pt[63]}]       \
[get_ports {pt[62]}] [get_ports {pt[61]}] [get_ports {pt[60]}] [get_ports      \
{pt[59]}] [get_ports {pt[58]}] [get_ports {pt[57]}] [get_ports {pt[56]}]       \
[get_ports {pt[55]}] [get_ports {pt[54]}] [get_ports {pt[53]}] [get_ports      \
{pt[52]}] [get_ports {pt[51]}] [get_ports {pt[50]}] [get_ports {pt[49]}]       \
[get_ports {pt[48]}] [get_ports {pt[47]}] [get_ports {pt[46]}] [get_ports      \
{pt[45]}] [get_ports {pt[44]}] [get_ports {pt[43]}] [get_ports {pt[42]}]       \
[get_ports {pt[41]}] [get_ports {pt[40]}] [get_ports {pt[39]}] [get_ports      \
{pt[38]}] [get_ports {pt[37]}] [get_ports {pt[36]}] [get_ports {pt[35]}]       \
[get_ports {pt[34]}] [get_ports {pt[33]}] [get_ports {pt[32]}] [get_ports      \
{pt[31]}] [get_ports {pt[30]}] [get_ports {pt[29]}] [get_ports {pt[28]}]       \
[get_ports {pt[27]}] [get_ports {pt[26]}] [get_ports {pt[25]}] [get_ports      \
{pt[24]}] [get_ports {pt[23]}] [get_ports {pt[22]}] [get_ports {pt[21]}]       \
[get_ports {pt[20]}] [get_ports {pt[19]}] [get_ports {pt[18]}] [get_ports      \
{pt[17]}] [get_ports {pt[16]}] [get_ports {pt[15]}] [get_ports {pt[14]}]       \
[get_ports {pt[13]}] [get_ports {pt[12]}] [get_ports {pt[11]}] [get_ports      \
{pt[10]}] [get_ports {pt[9]}] [get_ports {pt[8]}] [get_ports {pt[7]}]          \
[get_ports {pt[6]}] [get_ports {pt[5]}] [get_ports {pt[4]}] [get_ports         \
{pt[3]}] [get_ports {pt[2]}] [get_ports {pt[1]}] [get_ports {pt[0]}]]
group_path -name output_group  -to [list [get_ports {ct[63]}] [get_ports {ct[62]}] [get_ports {ct[61]}]      \
[get_ports {ct[60]}] [get_ports {ct[59]}] [get_ports {ct[58]}] [get_ports      \
{ct[57]}] [get_ports {ct[56]}] [get_ports {ct[55]}] [get_ports {ct[54]}]       \
[get_ports {ct[53]}] [get_ports {ct[52]}] [get_ports {ct[51]}] [get_ports      \
{ct[50]}] [get_ports {ct[49]}] [get_ports {ct[48]}] [get_ports {ct[47]}]       \
[get_ports {ct[46]}] [get_ports {ct[45]}] [get_ports {ct[44]}] [get_ports      \
{ct[43]}] [get_ports {ct[42]}] [get_ports {ct[41]}] [get_ports {ct[40]}]       \
[get_ports {ct[39]}] [get_ports {ct[38]}] [get_ports {ct[37]}] [get_ports      \
{ct[36]}] [get_ports {ct[35]}] [get_ports {ct[34]}] [get_ports {ct[33]}]       \
[get_ports {ct[32]}] [get_ports {ct[31]}] [get_ports {ct[30]}] [get_ports      \
{ct[29]}] [get_ports {ct[28]}] [get_ports {ct[27]}] [get_ports {ct[26]}]       \
[get_ports {ct[25]}] [get_ports {ct[24]}] [get_ports {ct[23]}] [get_ports      \
{ct[22]}] [get_ports {ct[21]}] [get_ports {ct[20]}] [get_ports {ct[19]}]       \
[get_ports {ct[18]}] [get_ports {ct[17]}] [get_ports {ct[16]}] [get_ports      \
{ct[15]}] [get_ports {ct[14]}] [get_ports {ct[13]}] [get_ports {ct[12]}]       \
[get_ports {ct[11]}] [get_ports {ct[10]}] [get_ports {ct[9]}] [get_ports       \
{ct[8]}] [get_ports {ct[7]}] [get_ports {ct[6]}] [get_ports {ct[5]}]           \
[get_ports {ct[4]}] [get_ports {ct[3]}] [get_ports {ct[2]}] [get_ports         \
{ct[1]}] [get_ports {ct[0]}] [get_ports busy] [get_ports valid]]
set_input_delay -clock CRYPTOCLK  -max 0.5  [get_ports reset_n]
set_input_delay -clock CRYPTOCLK  -min 0  [get_ports reset_n]
set_input_delay -clock CRYPTOCLK  -max 0.5  [get_ports load]
set_input_delay -clock CRYPTOCLK  -min 0  [get_ports load]
set_input_delay -clock CRYPTOCLK  -max 0.5  [get_ports {key[79]}]
set_input_delay -clock CRYPTOCLK  -min 0  [get_ports {key[79]}]
set_input_delay -clock CRYPTOCLK  -max 0.5  [get_ports {key[78]}]
set_input_delay -clock CRYPTOCLK  -min 0  [get_ports {key[78]}]
set_input_delay -clock CRYPTOCLK  -max 0.5  [get_ports {key[77]}]
set_input_delay -clock CRYPTOCLK  -min 0  [get_ports {key[77]}]
set_input_delay -clock CRYPTOCLK  -max 0.5  [get_ports {key[76]}]
set_input_delay -clock CRYPTOCLK  -min 0  [get_ports {key[76]}]
set_input_delay -clock CRYPTOCLK  -max 0.5  [get_ports {key[75]}]
set_input_delay -clock CRYPTOCLK  -min 0  [get_ports {key[75]}]
set_input_delay -clock CRYPTOCLK  -max 0.5  [get_ports {key[74]}]
set_input_delay -clock CRYPTOCLK  -min 0  [get_ports {key[74]}]
set_input_delay -clock CRYPTOCLK  -max 0.5  [get_ports {key[73]}]
set_input_delay -clock CRYPTOCLK  -min 0  [get_ports {key[73]}]
set_input_delay -clock CRYPTOCLK  -max 0.5  [get_ports {key[72]}]
set_input_delay -clock CRYPTOCLK  -min 0  [get_ports {key[72]}]
set_input_delay -clock CRYPTOCLK  -max 0.5  [get_ports {key[71]}]
set_input_delay -clock CRYPTOCLK  -min 0  [get_ports {key[71]}]
set_input_delay -clock CRYPTOCLK  -max 0.5  [get_ports {key[70]}]
set_input_delay -clock CRYPTOCLK  -min 0  [get_ports {key[70]}]
set_input_delay -clock CRYPTOCLK  -max 0.5  [get_ports {key[69]}]
set_input_delay -clock CRYPTOCLK  -min 0  [get_ports {key[69]}]
set_input_delay -clock CRYPTOCLK  -max 0.5  [get_ports {key[68]}]
set_input_delay -clock CRYPTOCLK  -min 0  [get_ports {key[68]}]
set_input_delay -clock CRYPTOCLK  -max 0.5  [get_ports {key[67]}]
set_input_delay -clock CRYPTOCLK  -min 0  [get_ports {key[67]}]
set_input_delay -clock CRYPTOCLK  -max 0.5  [get_ports {key[66]}]
set_input_delay -clock CRYPTOCLK  -min 0  [get_ports {key[66]}]
set_input_delay -clock CRYPTOCLK  -max 0.5  [get_ports {key[65]}]
set_input_delay -clock CRYPTOCLK  -min 0  [get_ports {key[65]}]
set_input_delay -clock CRYPTOCLK  -max 0.5  [get_ports {key[64]}]
set_input_delay -clock CRYPTOCLK  -min 0  [get_ports {key[64]}]
set_input_delay -clock CRYPTOCLK  -max 0.5  [get_ports {key[63]}]
set_input_delay -clock CRYPTOCLK  -min 0  [get_ports {key[63]}]
set_input_delay -clock CRYPTOCLK  -max 0.5  [get_ports {key[62]}]
set_input_delay -clock CRYPTOCLK  -min 0  [get_ports {key[62]}]
set_input_delay -clock CRYPTOCLK  -max 0.5  [get_ports {key[61]}]
set_input_delay -clock CRYPTOCLK  -min 0  [get_ports {key[61]}]
set_input_delay -clock CRYPTOCLK  -max 0.5  [get_ports {key[60]}]
set_input_delay -clock CRYPTOCLK  -min 0  [get_ports {key[60]}]
set_input_delay -clock CRYPTOCLK  -max 0.5  [get_ports {key[59]}]
set_input_delay -clock CRYPTOCLK  -min 0  [get_ports {key[59]}]
set_input_delay -clock CRYPTOCLK  -max 0.5  [get_ports {key[58]}]
set_input_delay -clock CRYPTOCLK  -min 0  [get_ports {key[58]}]
set_input_delay -clock CRYPTOCLK  -max 0.5  [get_ports {key[57]}]
set_input_delay -clock CRYPTOCLK  -min 0  [get_ports {key[57]}]
set_input_delay -clock CRYPTOCLK  -max 0.5  [get_ports {key[56]}]
set_input_delay -clock CRYPTOCLK  -min 0  [get_ports {key[56]}]
set_input_delay -clock CRYPTOCLK  -max 0.5  [get_ports {key[55]}]
set_input_delay -clock CRYPTOCLK  -min 0  [get_ports {key[55]}]
set_input_delay -clock CRYPTOCLK  -max 0.5  [get_ports {key[54]}]
set_input_delay -clock CRYPTOCLK  -min 0  [get_ports {key[54]}]
set_input_delay -clock CRYPTOCLK  -max 0.5  [get_ports {key[53]}]
set_input_delay -clock CRYPTOCLK  -min 0  [get_ports {key[53]}]
set_input_delay -clock CRYPTOCLK  -max 0.5  [get_ports {key[52]}]
set_input_delay -clock CRYPTOCLK  -min 0  [get_ports {key[52]}]
set_input_delay -clock CRYPTOCLK  -max 0.5  [get_ports {key[51]}]
set_input_delay -clock CRYPTOCLK  -min 0  [get_ports {key[51]}]
set_input_delay -clock CRYPTOCLK  -max 0.5  [get_ports {key[50]}]
set_input_delay -clock CRYPTOCLK  -min 0  [get_ports {key[50]}]
set_input_delay -clock CRYPTOCLK  -max 0.5  [get_ports {key[49]}]
set_input_delay -clock CRYPTOCLK  -min 0  [get_ports {key[49]}]
set_input_delay -clock CRYPTOCLK  -max 0.5  [get_ports {key[48]}]
set_input_delay -clock CRYPTOCLK  -min 0  [get_ports {key[48]}]
set_input_delay -clock CRYPTOCLK  -max 0.5  [get_ports {key[47]}]
set_input_delay -clock CRYPTOCLK  -min 0  [get_ports {key[47]}]
set_input_delay -clock CRYPTOCLK  -max 0.5  [get_ports {key[46]}]
set_input_delay -clock CRYPTOCLK  -min 0  [get_ports {key[46]}]
set_input_delay -clock CRYPTOCLK  -max 0.5  [get_ports {key[45]}]
set_input_delay -clock CRYPTOCLK  -min 0  [get_ports {key[45]}]
set_input_delay -clock CRYPTOCLK  -max 0.5  [get_ports {key[44]}]
set_input_delay -clock CRYPTOCLK  -min 0  [get_ports {key[44]}]
set_input_delay -clock CRYPTOCLK  -max 0.5  [get_ports {key[43]}]
set_input_delay -clock CRYPTOCLK  -min 0  [get_ports {key[43]}]
set_input_delay -clock CRYPTOCLK  -max 0.5  [get_ports {key[42]}]
set_input_delay -clock CRYPTOCLK  -min 0  [get_ports {key[42]}]
set_input_delay -clock CRYPTOCLK  -max 0.5  [get_ports {key[41]}]
set_input_delay -clock CRYPTOCLK  -min 0  [get_ports {key[41]}]
set_input_delay -clock CRYPTOCLK  -max 0.5  [get_ports {key[40]}]
set_input_delay -clock CRYPTOCLK  -min 0  [get_ports {key[40]}]
set_input_delay -clock CRYPTOCLK  -max 0.5  [get_ports {key[39]}]
set_input_delay -clock CRYPTOCLK  -min 0  [get_ports {key[39]}]
set_input_delay -clock CRYPTOCLK  -max 0.5  [get_ports {key[38]}]
set_input_delay -clock CRYPTOCLK  -min 0  [get_ports {key[38]}]
set_input_delay -clock CRYPTOCLK  -max 0.5  [get_ports {key[37]}]
set_input_delay -clock CRYPTOCLK  -min 0  [get_ports {key[37]}]
set_input_delay -clock CRYPTOCLK  -max 0.5  [get_ports {key[36]}]
set_input_delay -clock CRYPTOCLK  -min 0  [get_ports {key[36]}]
set_input_delay -clock CRYPTOCLK  -max 0.5  [get_ports {key[35]}]
set_input_delay -clock CRYPTOCLK  -min 0  [get_ports {key[35]}]
set_input_delay -clock CRYPTOCLK  -max 0.5  [get_ports {key[34]}]
set_input_delay -clock CRYPTOCLK  -min 0  [get_ports {key[34]}]
set_input_delay -clock CRYPTOCLK  -max 0.5  [get_ports {key[33]}]
set_input_delay -clock CRYPTOCLK  -min 0  [get_ports {key[33]}]
set_input_delay -clock CRYPTOCLK  -max 0.5  [get_ports {key[32]}]
set_input_delay -clock CRYPTOCLK  -min 0  [get_ports {key[32]}]
set_input_delay -clock CRYPTOCLK  -max 0.5  [get_ports {key[31]}]
set_input_delay -clock CRYPTOCLK  -min 0  [get_ports {key[31]}]
set_input_delay -clock CRYPTOCLK  -max 0.5  [get_ports {key[30]}]
set_input_delay -clock CRYPTOCLK  -min 0  [get_ports {key[30]}]
set_input_delay -clock CRYPTOCLK  -max 0.5  [get_ports {key[29]}]
set_input_delay -clock CRYPTOCLK  -min 0  [get_ports {key[29]}]
set_input_delay -clock CRYPTOCLK  -max 0.5  [get_ports {key[28]}]
set_input_delay -clock CRYPTOCLK  -min 0  [get_ports {key[28]}]
set_input_delay -clock CRYPTOCLK  -max 0.5  [get_ports {key[27]}]
set_input_delay -clock CRYPTOCLK  -min 0  [get_ports {key[27]}]
set_input_delay -clock CRYPTOCLK  -max 0.5  [get_ports {key[26]}]
set_input_delay -clock CRYPTOCLK  -min 0  [get_ports {key[26]}]
set_input_delay -clock CRYPTOCLK  -max 0.5  [get_ports {key[25]}]
set_input_delay -clock CRYPTOCLK  -min 0  [get_ports {key[25]}]
set_input_delay -clock CRYPTOCLK  -max 0.5  [get_ports {key[24]}]
set_input_delay -clock CRYPTOCLK  -min 0  [get_ports {key[24]}]
set_input_delay -clock CRYPTOCLK  -max 0.5  [get_ports {key[23]}]
set_input_delay -clock CRYPTOCLK  -min 0  [get_ports {key[23]}]
set_input_delay -clock CRYPTOCLK  -max 0.5  [get_ports {key[22]}]
set_input_delay -clock CRYPTOCLK  -min 0  [get_ports {key[22]}]
set_input_delay -clock CRYPTOCLK  -max 0.5  [get_ports {key[21]}]
set_input_delay -clock CRYPTOCLK  -min 0  [get_ports {key[21]}]
set_input_delay -clock CRYPTOCLK  -max 0.5  [get_ports {key[20]}]
set_input_delay -clock CRYPTOCLK  -min 0  [get_ports {key[20]}]
set_input_delay -clock CRYPTOCLK  -max 0.5  [get_ports {key[19]}]
set_input_delay -clock CRYPTOCLK  -min 0  [get_ports {key[19]}]
set_input_delay -clock CRYPTOCLK  -max 0.5  [get_ports {key[18]}]
set_input_delay -clock CRYPTOCLK  -min 0  [get_ports {key[18]}]
set_input_delay -clock CRYPTOCLK  -max 0.5  [get_ports {key[17]}]
set_input_delay -clock CRYPTOCLK  -min 0  [get_ports {key[17]}]
set_input_delay -clock CRYPTOCLK  -max 0.5  [get_ports {key[16]}]
set_input_delay -clock CRYPTOCLK  -min 0  [get_ports {key[16]}]
set_input_delay -clock CRYPTOCLK  -max 0.5  [get_ports {key[15]}]
set_input_delay -clock CRYPTOCLK  -min 0  [get_ports {key[15]}]
set_input_delay -clock CRYPTOCLK  -max 0.5  [get_ports {key[14]}]
set_input_delay -clock CRYPTOCLK  -min 0  [get_ports {key[14]}]
set_input_delay -clock CRYPTOCLK  -max 0.5  [get_ports {key[13]}]
set_input_delay -clock CRYPTOCLK  -min 0  [get_ports {key[13]}]
set_input_delay -clock CRYPTOCLK  -max 0.5  [get_ports {key[12]}]
set_input_delay -clock CRYPTOCLK  -min 0  [get_ports {key[12]}]
set_input_delay -clock CRYPTOCLK  -max 0.5  [get_ports {key[11]}]
set_input_delay -clock CRYPTOCLK  -min 0  [get_ports {key[11]}]
set_input_delay -clock CRYPTOCLK  -max 0.5  [get_ports {key[10]}]
set_input_delay -clock CRYPTOCLK  -min 0  [get_ports {key[10]}]
set_input_delay -clock CRYPTOCLK  -max 0.5  [get_ports {key[9]}]
set_input_delay -clock CRYPTOCLK  -min 0  [get_ports {key[9]}]
set_input_delay -clock CRYPTOCLK  -max 0.5  [get_ports {key[8]}]
set_input_delay -clock CRYPTOCLK  -min 0  [get_ports {key[8]}]
set_input_delay -clock CRYPTOCLK  -max 0.5  [get_ports {key[7]}]
set_input_delay -clock CRYPTOCLK  -min 0  [get_ports {key[7]}]
set_input_delay -clock CRYPTOCLK  -max 0.5  [get_ports {key[6]}]
set_input_delay -clock CRYPTOCLK  -min 0  [get_ports {key[6]}]
set_input_delay -clock CRYPTOCLK  -max 0.5  [get_ports {key[5]}]
set_input_delay -clock CRYPTOCLK  -min 0  [get_ports {key[5]}]
set_input_delay -clock CRYPTOCLK  -max 0.5  [get_ports {key[4]}]
set_input_delay -clock CRYPTOCLK  -min 0  [get_ports {key[4]}]
set_input_delay -clock CRYPTOCLK  -max 0.5  [get_ports {key[3]}]
set_input_delay -clock CRYPTOCLK  -min 0  [get_ports {key[3]}]
set_input_delay -clock CRYPTOCLK  -max 0.5  [get_ports {key[2]}]
set_input_delay -clock CRYPTOCLK  -min 0  [get_ports {key[2]}]
set_input_delay -clock CRYPTOCLK  -max 0.5  [get_ports {key[1]}]
set_input_delay -clock CRYPTOCLK  -min 0  [get_ports {key[1]}]
set_input_delay -clock CRYPTOCLK  -max 0.5  [get_ports {key[0]}]
set_input_delay -clock CRYPTOCLK  -min 0  [get_ports {key[0]}]
set_input_delay -clock CRYPTOCLK  -max 0.5  [get_ports {pt[63]}]
set_input_delay -clock CRYPTOCLK  -min 0  [get_ports {pt[63]}]
set_input_delay -clock CRYPTOCLK  -max 0.5  [get_ports {pt[62]}]
set_input_delay -clock CRYPTOCLK  -min 0  [get_ports {pt[62]}]
set_input_delay -clock CRYPTOCLK  -max 0.5  [get_ports {pt[61]}]
set_input_delay -clock CRYPTOCLK  -min 0  [get_ports {pt[61]}]
set_input_delay -clock CRYPTOCLK  -max 0.5  [get_ports {pt[60]}]
set_input_delay -clock CRYPTOCLK  -min 0  [get_ports {pt[60]}]
set_input_delay -clock CRYPTOCLK  -max 0.5  [get_ports {pt[59]}]
set_input_delay -clock CRYPTOCLK  -min 0  [get_ports {pt[59]}]
set_input_delay -clock CRYPTOCLK  -max 0.5  [get_ports {pt[58]}]
set_input_delay -clock CRYPTOCLK  -min 0  [get_ports {pt[58]}]
set_input_delay -clock CRYPTOCLK  -max 0.5  [get_ports {pt[57]}]
set_input_delay -clock CRYPTOCLK  -min 0  [get_ports {pt[57]}]
set_input_delay -clock CRYPTOCLK  -max 0.5  [get_ports {pt[56]}]
set_input_delay -clock CRYPTOCLK  -min 0  [get_ports {pt[56]}]
set_input_delay -clock CRYPTOCLK  -max 0.5  [get_ports {pt[55]}]
set_input_delay -clock CRYPTOCLK  -min 0  [get_ports {pt[55]}]
set_input_delay -clock CRYPTOCLK  -max 0.5  [get_ports {pt[54]}]
set_input_delay -clock CRYPTOCLK  -min 0  [get_ports {pt[54]}]
set_input_delay -clock CRYPTOCLK  -max 0.5  [get_ports {pt[53]}]
set_input_delay -clock CRYPTOCLK  -min 0  [get_ports {pt[53]}]
set_input_delay -clock CRYPTOCLK  -max 0.5  [get_ports {pt[52]}]
set_input_delay -clock CRYPTOCLK  -min 0  [get_ports {pt[52]}]
set_input_delay -clock CRYPTOCLK  -max 0.5  [get_ports {pt[51]}]
set_input_delay -clock CRYPTOCLK  -min 0  [get_ports {pt[51]}]
set_input_delay -clock CRYPTOCLK  -max 0.5  [get_ports {pt[50]}]
set_input_delay -clock CRYPTOCLK  -min 0  [get_ports {pt[50]}]
set_input_delay -clock CRYPTOCLK  -max 0.5  [get_ports {pt[49]}]
set_input_delay -clock CRYPTOCLK  -min 0  [get_ports {pt[49]}]
set_input_delay -clock CRYPTOCLK  -max 0.5  [get_ports {pt[48]}]
set_input_delay -clock CRYPTOCLK  -min 0  [get_ports {pt[48]}]
set_input_delay -clock CRYPTOCLK  -max 0.5  [get_ports {pt[47]}]
set_input_delay -clock CRYPTOCLK  -min 0  [get_ports {pt[47]}]
set_input_delay -clock CRYPTOCLK  -max 0.5  [get_ports {pt[46]}]
set_input_delay -clock CRYPTOCLK  -min 0  [get_ports {pt[46]}]
set_input_delay -clock CRYPTOCLK  -max 0.5  [get_ports {pt[45]}]
set_input_delay -clock CRYPTOCLK  -min 0  [get_ports {pt[45]}]
set_input_delay -clock CRYPTOCLK  -max 0.5  [get_ports {pt[44]}]
set_input_delay -clock CRYPTOCLK  -min 0  [get_ports {pt[44]}]
set_input_delay -clock CRYPTOCLK  -max 0.5  [get_ports {pt[43]}]
set_input_delay -clock CRYPTOCLK  -min 0  [get_ports {pt[43]}]
set_input_delay -clock CRYPTOCLK  -max 0.5  [get_ports {pt[42]}]
set_input_delay -clock CRYPTOCLK  -min 0  [get_ports {pt[42]}]
set_input_delay -clock CRYPTOCLK  -max 0.5  [get_ports {pt[41]}]
set_input_delay -clock CRYPTOCLK  -min 0  [get_ports {pt[41]}]
set_input_delay -clock CRYPTOCLK  -max 0.5  [get_ports {pt[40]}]
set_input_delay -clock CRYPTOCLK  -min 0  [get_ports {pt[40]}]
set_input_delay -clock CRYPTOCLK  -max 0.5  [get_ports {pt[39]}]
set_input_delay -clock CRYPTOCLK  -min 0  [get_ports {pt[39]}]
set_input_delay -clock CRYPTOCLK  -max 0.5  [get_ports {pt[38]}]
set_input_delay -clock CRYPTOCLK  -min 0  [get_ports {pt[38]}]
set_input_delay -clock CRYPTOCLK  -max 0.5  [get_ports {pt[37]}]
set_input_delay -clock CRYPTOCLK  -min 0  [get_ports {pt[37]}]
set_input_delay -clock CRYPTOCLK  -max 0.5  [get_ports {pt[36]}]
set_input_delay -clock CRYPTOCLK  -min 0  [get_ports {pt[36]}]
set_input_delay -clock CRYPTOCLK  -max 0.5  [get_ports {pt[35]}]
set_input_delay -clock CRYPTOCLK  -min 0  [get_ports {pt[35]}]
set_input_delay -clock CRYPTOCLK  -max 0.5  [get_ports {pt[34]}]
set_input_delay -clock CRYPTOCLK  -min 0  [get_ports {pt[34]}]
set_input_delay -clock CRYPTOCLK  -max 0.5  [get_ports {pt[33]}]
set_input_delay -clock CRYPTOCLK  -min 0  [get_ports {pt[33]}]
set_input_delay -clock CRYPTOCLK  -max 0.5  [get_ports {pt[32]}]
set_input_delay -clock CRYPTOCLK  -min 0  [get_ports {pt[32]}]
set_input_delay -clock CRYPTOCLK  -max 0.5  [get_ports {pt[31]}]
set_input_delay -clock CRYPTOCLK  -min 0  [get_ports {pt[31]}]
set_input_delay -clock CRYPTOCLK  -max 0.5  [get_ports {pt[30]}]
set_input_delay -clock CRYPTOCLK  -min 0  [get_ports {pt[30]}]
set_input_delay -clock CRYPTOCLK  -max 0.5  [get_ports {pt[29]}]
set_input_delay -clock CRYPTOCLK  -min 0  [get_ports {pt[29]}]
set_input_delay -clock CRYPTOCLK  -max 0.5  [get_ports {pt[28]}]
set_input_delay -clock CRYPTOCLK  -min 0  [get_ports {pt[28]}]
set_input_delay -clock CRYPTOCLK  -max 0.5  [get_ports {pt[27]}]
set_input_delay -clock CRYPTOCLK  -min 0  [get_ports {pt[27]}]
set_input_delay -clock CRYPTOCLK  -max 0.5  [get_ports {pt[26]}]
set_input_delay -clock CRYPTOCLK  -min 0  [get_ports {pt[26]}]
set_input_delay -clock CRYPTOCLK  -max 0.5  [get_ports {pt[25]}]
set_input_delay -clock CRYPTOCLK  -min 0  [get_ports {pt[25]}]
set_input_delay -clock CRYPTOCLK  -max 0.5  [get_ports {pt[24]}]
set_input_delay -clock CRYPTOCLK  -min 0  [get_ports {pt[24]}]
set_input_delay -clock CRYPTOCLK  -max 0.5  [get_ports {pt[23]}]
set_input_delay -clock CRYPTOCLK  -min 0  [get_ports {pt[23]}]
set_input_delay -clock CRYPTOCLK  -max 0.5  [get_ports {pt[22]}]
set_input_delay -clock CRYPTOCLK  -min 0  [get_ports {pt[22]}]
set_input_delay -clock CRYPTOCLK  -max 0.5  [get_ports {pt[21]}]
set_input_delay -clock CRYPTOCLK  -min 0  [get_ports {pt[21]}]
set_input_delay -clock CRYPTOCLK  -max 0.5  [get_ports {pt[20]}]
set_input_delay -clock CRYPTOCLK  -min 0  [get_ports {pt[20]}]
set_input_delay -clock CRYPTOCLK  -max 0.5  [get_ports {pt[19]}]
set_input_delay -clock CRYPTOCLK  -min 0  [get_ports {pt[19]}]
set_input_delay -clock CRYPTOCLK  -max 0.5  [get_ports {pt[18]}]
set_input_delay -clock CRYPTOCLK  -min 0  [get_ports {pt[18]}]
set_input_delay -clock CRYPTOCLK  -max 0.5  [get_ports {pt[17]}]
set_input_delay -clock CRYPTOCLK  -min 0  [get_ports {pt[17]}]
set_input_delay -clock CRYPTOCLK  -max 0.5  [get_ports {pt[16]}]
set_input_delay -clock CRYPTOCLK  -min 0  [get_ports {pt[16]}]
set_input_delay -clock CRYPTOCLK  -max 0.5  [get_ports {pt[15]}]
set_input_delay -clock CRYPTOCLK  -min 0  [get_ports {pt[15]}]
set_input_delay -clock CRYPTOCLK  -max 0.5  [get_ports {pt[14]}]
set_input_delay -clock CRYPTOCLK  -min 0  [get_ports {pt[14]}]
set_input_delay -clock CRYPTOCLK  -max 0.5  [get_ports {pt[13]}]
set_input_delay -clock CRYPTOCLK  -min 0  [get_ports {pt[13]}]
set_input_delay -clock CRYPTOCLK  -max 0.5  [get_ports {pt[12]}]
set_input_delay -clock CRYPTOCLK  -min 0  [get_ports {pt[12]}]
set_input_delay -clock CRYPTOCLK  -max 0.5  [get_ports {pt[11]}]
set_input_delay -clock CRYPTOCLK  -min 0  [get_ports {pt[11]}]
set_input_delay -clock CRYPTOCLK  -max 0.5  [get_ports {pt[10]}]
set_input_delay -clock CRYPTOCLK  -min 0  [get_ports {pt[10]}]
set_input_delay -clock CRYPTOCLK  -max 0.5  [get_ports {pt[9]}]
set_input_delay -clock CRYPTOCLK  -min 0  [get_ports {pt[9]}]
set_input_delay -clock CRYPTOCLK  -max 0.5  [get_ports {pt[8]}]
set_input_delay -clock CRYPTOCLK  -min 0  [get_ports {pt[8]}]
set_input_delay -clock CRYPTOCLK  -max 0.5  [get_ports {pt[7]}]
set_input_delay -clock CRYPTOCLK  -min 0  [get_ports {pt[7]}]
set_input_delay -clock CRYPTOCLK  -max 0.5  [get_ports {pt[6]}]
set_input_delay -clock CRYPTOCLK  -min 0  [get_ports {pt[6]}]
set_input_delay -clock CRYPTOCLK  -max 0.5  [get_ports {pt[5]}]
set_input_delay -clock CRYPTOCLK  -min 0  [get_ports {pt[5]}]
set_input_delay -clock CRYPTOCLK  -max 0.5  [get_ports {pt[4]}]
set_input_delay -clock CRYPTOCLK  -min 0  [get_ports {pt[4]}]
set_input_delay -clock CRYPTOCLK  -max 0.5  [get_ports {pt[3]}]
set_input_delay -clock CRYPTOCLK  -min 0  [get_ports {pt[3]}]
set_input_delay -clock CRYPTOCLK  -max 0.5  [get_ports {pt[2]}]
set_input_delay -clock CRYPTOCLK  -min 0  [get_ports {pt[2]}]
set_input_delay -clock CRYPTOCLK  -max 0.5  [get_ports {pt[1]}]
set_input_delay -clock CRYPTOCLK  -min 0  [get_ports {pt[1]}]
set_input_delay -clock CRYPTOCLK  -max 0.5  [get_ports {pt[0]}]
set_input_delay -clock CRYPTOCLK  -min 0  [get_ports {pt[0]}]
set_output_delay -clock CRYPTOCLK  0.5  [get_ports {ct[63]}]
set_output_delay -clock CRYPTOCLK  0.5  [get_ports {ct[62]}]
set_output_delay -clock CRYPTOCLK  0.5  [get_ports {ct[61]}]
set_output_delay -clock CRYPTOCLK  0.5  [get_ports {ct[60]}]
set_output_delay -clock CRYPTOCLK  0.5  [get_ports {ct[59]}]
set_output_delay -clock CRYPTOCLK  0.5  [get_ports {ct[58]}]
set_output_delay -clock CRYPTOCLK  0.5  [get_ports {ct[57]}]
set_output_delay -clock CRYPTOCLK  0.5  [get_ports {ct[56]}]
set_output_delay -clock CRYPTOCLK  0.5  [get_ports {ct[55]}]
set_output_delay -clock CRYPTOCLK  0.5  [get_ports {ct[54]}]
set_output_delay -clock CRYPTOCLK  0.5  [get_ports {ct[53]}]
set_output_delay -clock CRYPTOCLK  0.5  [get_ports {ct[52]}]
set_output_delay -clock CRYPTOCLK  0.5  [get_ports {ct[51]}]
set_output_delay -clock CRYPTOCLK  0.5  [get_ports {ct[50]}]
set_output_delay -clock CRYPTOCLK  0.5  [get_ports {ct[49]}]
set_output_delay -clock CRYPTOCLK  0.5  [get_ports {ct[48]}]
set_output_delay -clock CRYPTOCLK  0.5  [get_ports {ct[47]}]
set_output_delay -clock CRYPTOCLK  0.5  [get_ports {ct[46]}]
set_output_delay -clock CRYPTOCLK  0.5  [get_ports {ct[45]}]
set_output_delay -clock CRYPTOCLK  0.5  [get_ports {ct[44]}]
set_output_delay -clock CRYPTOCLK  0.5  [get_ports {ct[43]}]
set_output_delay -clock CRYPTOCLK  0.5  [get_ports {ct[42]}]
set_output_delay -clock CRYPTOCLK  0.5  [get_ports {ct[41]}]
set_output_delay -clock CRYPTOCLK  0.5  [get_ports {ct[40]}]
set_output_delay -clock CRYPTOCLK  0.5  [get_ports {ct[39]}]
set_output_delay -clock CRYPTOCLK  0.5  [get_ports {ct[38]}]
set_output_delay -clock CRYPTOCLK  0.5  [get_ports {ct[37]}]
set_output_delay -clock CRYPTOCLK  0.5  [get_ports {ct[36]}]
set_output_delay -clock CRYPTOCLK  0.5  [get_ports {ct[35]}]
set_output_delay -clock CRYPTOCLK  0.5  [get_ports {ct[34]}]
set_output_delay -clock CRYPTOCLK  0.5  [get_ports {ct[33]}]
set_output_delay -clock CRYPTOCLK  0.5  [get_ports {ct[32]}]
set_output_delay -clock CRYPTOCLK  0.5  [get_ports {ct[31]}]
set_output_delay -clock CRYPTOCLK  0.5  [get_ports {ct[30]}]
set_output_delay -clock CRYPTOCLK  0.5  [get_ports {ct[29]}]
set_output_delay -clock CRYPTOCLK  0.5  [get_ports {ct[28]}]
set_output_delay -clock CRYPTOCLK  0.5  [get_ports {ct[27]}]
set_output_delay -clock CRYPTOCLK  0.5  [get_ports {ct[26]}]
set_output_delay -clock CRYPTOCLK  0.5  [get_ports {ct[25]}]
set_output_delay -clock CRYPTOCLK  0.5  [get_ports {ct[24]}]
set_output_delay -clock CRYPTOCLK  0.5  [get_ports {ct[23]}]
set_output_delay -clock CRYPTOCLK  0.5  [get_ports {ct[22]}]
set_output_delay -clock CRYPTOCLK  0.5  [get_ports {ct[21]}]
set_output_delay -clock CRYPTOCLK  0.5  [get_ports {ct[20]}]
set_output_delay -clock CRYPTOCLK  0.5  [get_ports {ct[19]}]
set_output_delay -clock CRYPTOCLK  0.5  [get_ports {ct[18]}]
set_output_delay -clock CRYPTOCLK  0.5  [get_ports {ct[17]}]
set_output_delay -clock CRYPTOCLK  0.5  [get_ports {ct[16]}]
set_output_delay -clock CRYPTOCLK  0.5  [get_ports {ct[15]}]
set_output_delay -clock CRYPTOCLK  0.5  [get_ports {ct[14]}]
set_output_delay -clock CRYPTOCLK  0.5  [get_ports {ct[13]}]
set_output_delay -clock CRYPTOCLK  0.5  [get_ports {ct[12]}]
set_output_delay -clock CRYPTOCLK  0.5  [get_ports {ct[11]}]
set_output_delay -clock CRYPTOCLK  0.5  [get_ports {ct[10]}]
set_output_delay -clock CRYPTOCLK  0.5  [get_ports {ct[9]}]
set_output_delay -clock CRYPTOCLK  0.5  [get_ports {ct[8]}]
set_output_delay -clock CRYPTOCLK  0.5  [get_ports {ct[7]}]
set_output_delay -clock CRYPTOCLK  0.5  [get_ports {ct[6]}]
set_output_delay -clock CRYPTOCLK  0.5  [get_ports {ct[5]}]
set_output_delay -clock CRYPTOCLK  0.5  [get_ports {ct[4]}]
set_output_delay -clock CRYPTOCLK  0.5  [get_ports {ct[3]}]
set_output_delay -clock CRYPTOCLK  0.5  [get_ports {ct[2]}]
set_output_delay -clock CRYPTOCLK  0.5  [get_ports {ct[1]}]
set_output_delay -clock CRYPTOCLK  0.5  [get_ports {ct[0]}]
set_output_delay -clock CRYPTOCLK  0.5  [get_ports busy]
set_output_delay -clock CRYPTOCLK  0.5  [get_ports valid]
