/*
###############################################################
#  Generated by:      Cadence Innovus 16.15-s078_1
#  OS:                Linux x86_64(Host ID aduae260-lap)
#  Generated on:      Thu Jan 13 13:42:28 2022
#  Design:            present_encryption
#  Command:           saveNetlist -excludeLeafCell outputs/design_original.v
###############################################################
*/
/////////////////////////////////////////////////////////////
// Created by: Synopsys DC Ultra(TM) in wire load mode
// Version   : M-2016.12-SP2
// Date      : Thu Jan 13 13:06:31 2022
/////////////////////////////////////////////////////////////
module present_encryption (
	clock, 
	reset_n, 
	load, 
	key, 
	pt, 
	ct, 
	busy, 
	valid);
   input clock;
   input reset_n;
   input load;
   input [79:0] key;
   input [63:0] pt;
   output [63:0] ct;
   output busy;
   output valid;

   // Internal wires
   wire CTS_24;
   wire CTS_23;
   wire CTS_22;
   wire CTS_21;
   wire CTS_20;
   wire CTS_19;
   wire TIE_CELL_LTIELO_NET;
   wire TIE_CELL_LTIEHI_NET;
   wire FE_OFN582_n;
   wire FE_OFN8_FE_DBTN1_n502;
   wire FE_OFN7_n502;
   wire FE_OFN6_FE_DBTN0_n560;
   wire FE_OFN5_FE_DBTN0_n560;
   wire FE_OFN4_n560;
   wire FE_OFN3_n581;
   wire FE_OFN2_n581;
   wire FE_OFN1_reset_n;
   wire FE_OFN0_reset_n;
   wire FE_DBTN1_n502;
   wire FE_DBTN0_n560;
   wire next_round_key_79;
   wire next_round_key_78;
   wire next_round_key_77;
   wire next_round_key_76;
   wire n241;
   wire n242;
   wire n243;
   wire n244;
   wire n245;
   wire n247;
   wire n248;
   wire n249;
   wire n250;
   wire n251;
   wire n252;
   wire n253;
   wire n254;
   wire n255;
   wire n256;
   wire n257;
   wire n258;
   wire n260;
   wire n261;
   wire n262;
   wire n263;
   wire n264;
   wire n265;
   wire n266;
   wire n267;
   wire n268;
   wire n269;
   wire n270;
   wire n271;
   wire n272;
   wire n273;
   wire n274;
   wire n275;
   wire n276;
   wire n277;
   wire n278;
   wire n279;
   wire n280;
   wire n281;
   wire n282;
   wire n283;
   wire n284;
   wire n285;
   wire n286;
   wire n287;
   wire n288;
   wire n289;
   wire n290;
   wire n291;
   wire n292;
   wire n293;
   wire n294;
   wire n295;
   wire n296;
   wire n297;
   wire n298;
   wire n299;
   wire n300;
   wire n301;
   wire n302;
   wire n303;
   wire n304;
   wire n305;
   wire n306;
   wire n307;
   wire n308;
   wire n309;
   wire n310;
   wire n311;
   wire n312;
   wire n313;
   wire n314;
   wire n315;
   wire n316;
   wire n317;
   wire n318;
   wire n319;
   wire n320;
   wire n321;
   wire n322;
   wire n323;
   wire n324;
   wire n325;
   wire n326;
   wire n327;
   wire n328;
   wire n329;
   wire n330;
   wire n331;
   wire n332;
   wire n333;
   wire n334;
   wire n335;
   wire n336;
   wire n337;
   wire n338;
   wire n339;
   wire n340;
   wire n341;
   wire n342;
   wire n343;
   wire n344;
   wire n345;
   wire n346;
   wire n347;
   wire n348;
   wire n349;
   wire n350;
   wire n351;
   wire n352;
   wire n353;
   wire n354;
   wire n355;
   wire n356;
   wire n357;
   wire n358;
   wire n359;
   wire n360;
   wire n361;
   wire n362;
   wire n363;
   wire n364;
   wire n365;
   wire n366;
   wire n367;
   wire n368;
   wire n369;
   wire n370;
   wire n371;
   wire n372;
   wire n373;
   wire n374;
   wire n375;
   wire n376;
   wire n377;
   wire n378;
   wire n379;
   wire n380;
   wire n381;
   wire n382;
   wire n383;
   wire n384;
   wire n385;
   wire n386;
   wire n387;
   wire n388;
   wire n389;
   wire n391;
   wire n392;
   wire n393;
   wire n394;
   wire n395;
   wire n396;
   wire n397;
   wire n398;
   wire n399;
   wire n400;
   wire n401;
   wire n402;
   wire n403;
   wire n404;
   wire n405;
   wire n406;
   wire n408;
   wire n409;
   wire n410;
   wire n411;
   wire n412;
   wire n413;
   wire n414;
   wire n415;
   wire n416;
   wire n417;
   wire n418;
   wire n419;
   wire n420;
   wire n421;
   wire n422;
   wire n423;
   wire n424;
   wire n425;
   wire n426;
   wire n427;
   wire n428;
   wire n429;
   wire n430;
   wire n431;
   wire n432;
   wire n433;
   wire n434;
   wire n435;
   wire n436;
   wire n437;
   wire n438;
   wire n440;
   wire n441;
   wire n442;
   wire n443;
   wire n444;
   wire n445;
   wire n446;
   wire n447;
   wire n448;
   wire n449;
   wire n450;
   wire n451;
   wire n452;
   wire n453;
   wire n454;
   wire n455;
   wire n457;
   wire n458;
   wire n459;
   wire n460;
   wire n461;
   wire n462;
   wire n463;
   wire n464;
   wire n465;
   wire n466;
   wire n467;
   wire n468;
   wire n469;
   wire n470;
   wire n471;
   wire n472;
   wire n473;
   wire n474;
   wire n475;
   wire n476;
   wire n477;
   wire n478;
   wire n479;
   wire n480;
   wire n481;
   wire n482;
   wire n483;
   wire n484;
   wire n485;
   wire n486;
   wire n487;
   wire n489;
   wire n490;
   wire n491;
   wire n492;
   wire n493;
   wire n495;
   wire n496;
   wire n497;
   wire n498;
   wire n499;
   wire n500;
   wire n501;
   wire n502;
   wire n503;
   wire n504;
   wire n505;
   wire n506;
   wire n508;
   wire n509;
   wire n510;
   wire n511;
   wire n512;
   wire n513;
   wire n515;
   wire n516;
   wire n517;
   wire n518;
   wire n519;
   wire n520;
   wire n521;
   wire n522;
   wire n523;
   wire n524;
   wire n525;
   wire n526;
   wire n528;
   wire n529;
   wire n530;
   wire n531;
   wire n533;
   wire n534;
   wire n535;
   wire n536;
   wire n537;
   wire n538;
   wire n539;
   wire n540;
   wire n541;
   wire n542;
   wire n543;
   wire n544;
   wire n547;
   wire n548;
   wire n549;
   wire n550;
   wire n551;
   wire n552;
   wire n553;
   wire n554;
   wire n555;
   wire n557;
   wire n559;
   wire n560;
   wire n561;
   wire n563;
   wire n564;
   wire n565;
   wire n566;
   wire n567;
   wire n568;
   wire n569;
   wire n570;
   wire n571;
   wire n572;
   wire n574;
   wire n575;
   wire n577;
   wire n579;
   wire n581;
   wire n583;
   wire n584;
   wire n585;
   wire n586;
   wire n587;
   wire n588;
   wire n589;
   wire n590;
   wire n591;
   wire n592;
   wire n593;
   wire n594;
   wire n595;
   wire n596;
   wire n597;
   wire n598;
   wire n599;
   wire n600;
   wire n601;
   wire n602;
   wire n603;
   wire n604;
   wire n605;
   wire n606;
   wire n607;
   wire n608;
   wire n609;
   wire n610;
   wire n611;
   wire n612;
   wire n613;
   wire n614;
   wire n615;
   wire n616;
   wire n617;
   wire n618;
   wire n619;
   wire n620;
   wire n621;
   wire n622;
   wire n623;
   wire n624;
   wire n625;
   wire n626;
   wire n627;
   wire n628;
   wire n629;
   wire n630;
   wire n631;
   wire n632;
   wire n633;
   wire n634;
   wire \s1/n14 ;
   wire \s1/n13 ;
   wire \s1/n12 ;
   wire \s1/n11 ;
   wire \s1/n10 ;
   wire \s1/n9 ;
   wire \s1/n8 ;
   wire \s1/n7 ;
   wire \s1/n6 ;
   wire \s1/n5 ;
   wire \s1/n4 ;
   wire \s1/n3 ;
   wire \s1/n2 ;
   wire \s1/n1 ;
   wire \s2/n14 ;
   wire \s2/n13 ;
   wire \s2/n12 ;
   wire \s2/n11 ;
   wire \s2/n10 ;
   wire \s2/n9 ;
   wire \s2/n8 ;
   wire \s2/n7 ;
   wire \s2/n6 ;
   wire \s2/n5 ;
   wire \s2/n4 ;
   wire \s2/n3 ;
   wire \s2/n2 ;
   wire \s2/n1 ;
   wire \s3/n14 ;
   wire \s3/n13 ;
   wire \s3/n12 ;
   wire \s3/n11 ;
   wire \s3/n10 ;
   wire \s3/n9 ;
   wire \s3/n8 ;
   wire \s3/n7 ;
   wire \s3/n6 ;
   wire \s3/n5 ;
   wire \s3/n4 ;
   wire \s3/n3 ;
   wire \s3/n2 ;
   wire \s3/n1 ;
   wire \s4/n14 ;
   wire \s4/n13 ;
   wire \s4/n12 ;
   wire \s4/n11 ;
   wire \s4/n10 ;
   wire \s4/n9 ;
   wire \s4/n8 ;
   wire \s4/n7 ;
   wire \s4/n6 ;
   wire \s4/n5 ;
   wire \s4/n4 ;
   wire \s4/n3 ;
   wire \s4/n2 ;
   wire \s4/n1 ;
   wire \s5/n14 ;
   wire \s5/n13 ;
   wire \s5/n12 ;
   wire \s5/n11 ;
   wire \s5/n10 ;
   wire \s5/n9 ;
   wire \s5/n8 ;
   wire \s5/n7 ;
   wire \s5/n6 ;
   wire \s5/n5 ;
   wire \s5/n4 ;
   wire \s5/n3 ;
   wire \s5/n2 ;
   wire \s5/n1 ;
   wire \s6/n14 ;
   wire \s6/n13 ;
   wire \s6/n12 ;
   wire \s6/n11 ;
   wire \s6/n10 ;
   wire \s6/n9 ;
   wire \s6/n8 ;
   wire \s6/n7 ;
   wire \s6/n6 ;
   wire \s6/n5 ;
   wire \s6/n4 ;
   wire \s6/n3 ;
   wire \s6/n2 ;
   wire \s6/n1 ;
   wire \s7/n14 ;
   wire \s7/n13 ;
   wire \s7/n12 ;
   wire \s7/n11 ;
   wire \s7/n10 ;
   wire \s7/n9 ;
   wire \s7/n8 ;
   wire \s7/n7 ;
   wire \s7/n6 ;
   wire \s7/n5 ;
   wire \s7/n4 ;
   wire \s7/n3 ;
   wire \s7/n2 ;
   wire \s7/n1 ;
   wire \s8/n14 ;
   wire \s8/n13 ;
   wire \s8/n12 ;
   wire \s8/n11 ;
   wire \s8/n10 ;
   wire \s8/n9 ;
   wire \s8/n8 ;
   wire \s8/n7 ;
   wire \s8/n6 ;
   wire \s8/n5 ;
   wire \s8/n4 ;
   wire \s8/n3 ;
   wire \s8/n2 ;
   wire \s8/n1 ;
   wire \s9/n14 ;
   wire \s9/n13 ;
   wire \s9/n12 ;
   wire \s9/n11 ;
   wire \s9/n10 ;
   wire \s9/n9 ;
   wire \s9/n8 ;
   wire \s9/n7 ;
   wire \s9/n6 ;
   wire \s9/n5 ;
   wire \s9/n4 ;
   wire \s9/n3 ;
   wire \s9/n2 ;
   wire \s9/n1 ;
   wire \s10/n14 ;
   wire \s10/n13 ;
   wire \s10/n12 ;
   wire \s10/n11 ;
   wire \s10/n10 ;
   wire \s10/n9 ;
   wire \s10/n8 ;
   wire \s10/n7 ;
   wire \s10/n6 ;
   wire \s10/n5 ;
   wire \s10/n4 ;
   wire \s10/n3 ;
   wire \s10/n2 ;
   wire \s10/n1 ;
   wire \s11/n14 ;
   wire \s11/n13 ;
   wire \s11/n12 ;
   wire \s11/n11 ;
   wire \s11/n10 ;
   wire \s11/n9 ;
   wire \s11/n8 ;
   wire \s11/n7 ;
   wire \s11/n6 ;
   wire \s11/n5 ;
   wire \s11/n4 ;
   wire \s11/n3 ;
   wire \s11/n2 ;
   wire \s11/n1 ;
   wire \s12/n14 ;
   wire \s12/n13 ;
   wire \s12/n12 ;
   wire \s12/n11 ;
   wire \s12/n10 ;
   wire \s12/n9 ;
   wire \s12/n8 ;
   wire \s12/n7 ;
   wire \s12/n6 ;
   wire \s12/n5 ;
   wire \s12/n4 ;
   wire \s12/n3 ;
   wire \s12/n2 ;
   wire \s12/n1 ;
   wire \s13/n14 ;
   wire \s13/n13 ;
   wire \s13/n12 ;
   wire \s13/n11 ;
   wire \s13/n10 ;
   wire \s13/n9 ;
   wire \s13/n8 ;
   wire \s13/n7 ;
   wire \s13/n6 ;
   wire \s13/n5 ;
   wire \s13/n4 ;
   wire \s13/n3 ;
   wire \s13/n2 ;
   wire \s13/n1 ;
   wire \s14/n14 ;
   wire \s14/n13 ;
   wire \s14/n12 ;
   wire \s14/n11 ;
   wire \s14/n10 ;
   wire \s14/n9 ;
   wire \s14/n8 ;
   wire \s14/n7 ;
   wire \s14/n6 ;
   wire \s14/n5 ;
   wire \s14/n4 ;
   wire \s14/n3 ;
   wire \s14/n2 ;
   wire \s14/n1 ;
   wire \s15/n14 ;
   wire \s15/n13 ;
   wire \s15/n12 ;
   wire \s15/n11 ;
   wire \s15/n10 ;
   wire \s15/n9 ;
   wire \s15/n8 ;
   wire \s15/n7 ;
   wire \s15/n6 ;
   wire \s15/n5 ;
   wire \s15/n4 ;
   wire \s15/n3 ;
   wire \s15/n2 ;
   wire \s15/n1 ;
   wire \s16/n14 ;
   wire \s16/n13 ;
   wire \s16/n12 ;
   wire \s16/n11 ;
   wire \s16/n10 ;
   wire \s16/n9 ;
   wire \s16/n8 ;
   wire \s16/n7 ;
   wire \s16/n6 ;
   wire \s16/n5 ;
   wire \s16/n4 ;
   wire \s16/n3 ;
   wire \s16/n2 ;
   wire \s16/n1 ;
   wire \key_sbox/n14 ;
   wire \key_sbox/n13 ;
   wire \key_sbox/n12 ;
   wire \key_sbox/n11 ;
   wire \key_sbox/n10 ;
   wire \key_sbox/n9 ;
   wire \key_sbox/n8 ;
   wire \key_sbox/n7 ;
   wire \key_sbox/n6 ;
   wire \key_sbox/n5 ;
   wire \key_sbox/n4 ;
   wire \key_sbox/n3 ;
   wire \key_sbox/n2 ;
   wire \key_sbox/n1 ;
   wire [1:0] fsm_state;
   wire [60:0] current_key;
   wire [5:0] round;
   wire [63:0] state;
   wire [63:0] perm_state;

   CLKBUF_X3 CTS_ccl_BUF_CRYPTOCLK_G0_L1_6 (.A(clock),
	.Z(CTS_24));
   CLKBUF_X3 CTS_ccl_BUF_CRYPTOCLK_G0_L1_5 (.A(clock),
	.Z(CTS_23));
   CLKBUF_X3 CTS_ccl_BUF_CRYPTOCLK_G0_L1_4 (.A(clock),
	.Z(CTS_22));
   CLKBUF_X3 CTS_ccl_BUF_CRYPTOCLK_G0_L1_3 (.A(clock),
	.Z(CTS_21));
   CLKBUF_X3 CTS_ccl_BUF_CRYPTOCLK_G0_L1_2 (.A(clock),
	.Z(CTS_20));
   CLKBUF_X3 CTS_ccl_BUF_CRYPTOCLK_G0_L1_1 (.A(clock),
	.Z(CTS_19));
   LOGIC0_X1 TIE_CELL_LTIELO (.Z(TIE_CELL_LTIELO_NET));
   LOGIC1_X1 TIE_CELL_LTIEHI (.Z(TIE_CELL_LTIEHI_NET));
   BUF_X16 FE_OFC9_n581 (.A(FE_OFN2_n581),
	.Z(FE_OFN582_n));
   CLKBUF_X3 FE_OFC8_FE_DBTN1_n502 (.A(FE_DBTN1_n502),
	.Z(FE_OFN8_FE_DBTN1_n502));
   CLKBUF_X3 FE_OFC7_n502 (.A(n502),
	.Z(FE_OFN7_n502));
   BUF_X4 FE_OFC6_FE_DBTN0_n560 (.A(FE_OFN5_FE_DBTN0_n560),
	.Z(FE_OFN6_FE_DBTN0_n560));
   CLKBUF_X3 FE_OFC5_FE_DBTN0_n560 (.A(FE_DBTN0_n560),
	.Z(FE_OFN5_FE_DBTN0_n560));
   CLKBUF_X3 FE_OFC4_n560 (.A(n560),
	.Z(FE_OFN4_n560));
   CLKBUF_X3 FE_OFC3_n581 (.A(FE_OFN582_n),
	.Z(FE_OFN3_n581));
   CLKBUF_X3 FE_OFC2_n581 (.A(n581),
	.Z(FE_OFN2_n581));
   CLKBUF_X3 FE_OFC1_reset_n (.A(FE_OFN0_reset_n),
	.Z(FE_OFN1_reset_n));
   BUF_X4 FE_OFC0_reset_n (.A(reset_n),
	.Z(FE_OFN0_reset_n));
   INV_X4 FE_DBTC1_n502 (.A(n502),
	.ZN(FE_DBTN1_n502));
   INV_X1 FE_DBTC0_n560 (.A(FE_OFN4_n560),
	.ZN(FE_DBTN0_n560));
   DFFR_X1 fsm_state_reg_0_ (.D(n391),
	.RN(reset_n),
	.CK(CTS_19),
	.Q(fsm_state[0]),
	.QN(n592));
   DFFR_X1 round_reg_5_ (.D(n389),
	.RN(reset_n),
	.CK(CTS_19),
	.Q(round[5]));
   DFFR_X1 round_reg_4_ (.D(n385),
	.RN(reset_n),
	.CK(CTS_19),
	.Q(round[4]),
	.QN(n589));
   DFFR_X1 round_reg_3_ (.D(n386),
	.RN(reset_n),
	.CK(CTS_19),
	.Q(round[3]),
	.QN(n634));
   DFFR_X1 round_reg_2_ (.D(n387),
	.RN(reset_n),
	.CK(CTS_19),
	.Q(round[2]),
	.QN(n590));
   DFFR_X1 round_reg_1_ (.D(n388),
	.RN(reset_n),
	.CK(CTS_19),
	.Q(round[1]),
	.QN(n588));
   DFFR_X1 round_reg_0_ (.D(n392),
	.RN(reset_n),
	.CK(CTS_19),
	.Q(round[0]),
	.QN(n393));
   DFFR_X1 current_key_reg_15_ (.D(n241),
	.RN(reset_n),
	.CK(CTS_19),
	.Q(current_key[15]));
   DFFR_X1 current_key_reg_76_ (.D(n367),
	.RN(reset_n),
	.CK(CTS_19),
	.QN(n608));
   DFFR_X1 current_key_reg_57_ (.D(n366),
	.RN(reset_n),
	.CK(CTS_19),
	.Q(current_key[57]));
   DFFR_X1 current_key_reg_38_ (.D(n365),
	.RN(reset_n),
	.CK(CTS_19),
	.Q(current_key[38]),
	.QN(n628));
   DFFR_X1 current_key_reg_19_ (.D(n364),
	.RN(reset_n),
	.CK(CTS_19),
	.Q(current_key[19]),
	.QN(n603));
   DFFR_X1 current_key_reg_0_ (.D(n384),
	.RN(reset_n),
	.CK(CTS_23),
	.Q(current_key[0]));
   DFFR_X1 current_key_reg_61_ (.D(n383),
	.RN(FE_OFN1_reset_n),
	.CK(CTS_23),
	.QN(n604));
   DFFR_X1 current_key_reg_42_ (.D(n382),
	.RN(FE_OFN0_reset_n),
	.CK(CTS_20),
	.Q(current_key[42]));
   DFFR_X1 current_key_reg_23_ (.D(n381),
	.RN(FE_OFN0_reset_n),
	.CK(CTS_20),
	.QN(n593));
   DFFR_X1 current_key_reg_4_ (.D(n380),
	.RN(FE_OFN0_reset_n),
	.CK(CTS_20),
	.Q(current_key[4]));
   DFFR_X1 current_key_reg_65_ (.D(n379),
	.RN(FE_OFN0_reset_n),
	.CK(CTS_20),
	.QN(n605));
   DFFR_X1 current_key_reg_46_ (.D(n378),
	.RN(FE_OFN1_reset_n),
	.CK(CTS_24),
	.Q(current_key[46]));
   DFFR_X1 current_key_reg_27_ (.D(n377),
	.RN(FE_OFN1_reset_n),
	.CK(CTS_24),
	.QN(n594));
   DFFR_X1 current_key_reg_8_ (.D(n376),
	.RN(FE_OFN1_reset_n),
	.CK(CTS_24),
	.Q(current_key[8]));
   DFFR_X1 current_key_reg_69_ (.D(n375),
	.RN(FE_OFN1_reset_n),
	.CK(CTS_24),
	.QN(n606));
   DFFR_X1 current_key_reg_50_ (.D(n374),
	.RN(reset_n),
	.CK(CTS_23),
	.Q(current_key[50]));
   DFFR_X1 current_key_reg_31_ (.D(n373),
	.RN(reset_n),
	.CK(CTS_23),
	.QN(n595));
   DFFR_X1 current_key_reg_12_ (.D(n372),
	.RN(reset_n),
	.CK(CTS_23),
	.Q(current_key[12]));
   DFFR_X1 current_key_reg_73_ (.D(n371),
	.RN(FE_OFN0_reset_n),
	.CK(CTS_22),
	.QN(n607));
   DFFR_X1 current_key_reg_54_ (.D(n370),
	.RN(FE_OFN0_reset_n),
	.CK(CTS_22),
	.Q(current_key[54]));
   DFFR_X1 current_key_reg_35_ (.D(n369),
	.RN(reset_n),
	.CK(CTS_19),
	.Q(current_key[35]),
	.QN(n602));
   DFFR_X1 current_key_reg_16_ (.D(n368),
	.RN(reset_n),
	.CK(CTS_19),
	.Q(current_key[16]));
   DFFR_X1 current_key_reg_77_ (.D(n363),
	.RN(reset_n),
	.CK(CTS_19),
	.QN(n609));
   DFFR_X1 current_key_reg_58_ (.D(n362),
	.RN(reset_n),
	.CK(CTS_23),
	.Q(current_key[58]));
   DFFR_X1 current_key_reg_39_ (.D(n361),
	.RN(FE_OFN0_reset_n),
	.CK(CTS_22),
	.QN(n596));
   DFFR_X1 current_key_reg_20_ (.D(n360),
	.RN(FE_OFN0_reset_n),
	.CK(CTS_22),
	.Q(current_key[20]),
	.QN(n631));
   DFFR_X1 current_key_reg_1_ (.D(n359),
	.RN(FE_OFN0_reset_n),
	.CK(CTS_20),
	.Q(current_key[1]));
   DFFR_X1 current_key_reg_62_ (.D(n358),
	.RN(FE_OFN0_reset_n),
	.CK(CTS_20),
	.QN(n610));
   DFFR_X1 current_key_reg_43_ (.D(n357),
	.RN(FE_OFN0_reset_n),
	.CK(CTS_20),
	.Q(current_key[43]));
   DFFR_X1 current_key_reg_24_ (.D(n356),
	.RN(FE_OFN1_reset_n),
	.CK(CTS_24),
	.QN(n611));
   DFFR_X1 current_key_reg_5_ (.D(n355),
	.RN(FE_OFN1_reset_n),
	.CK(CTS_24),
	.Q(current_key[5]));
   DFFR_X1 current_key_reg_66_ (.D(n354),
	.RN(FE_OFN1_reset_n),
	.CK(CTS_24),
	.QN(n612));
   DFFR_X1 current_key_reg_47_ (.D(n353),
	.RN(FE_OFN1_reset_n),
	.CK(CTS_21),
	.Q(current_key[47]));
   DFFR_X1 current_key_reg_28_ (.D(n352),
	.RN(FE_OFN1_reset_n),
	.CK(CTS_21),
	.QN(n613));
   DFFR_X1 current_key_reg_9_ (.D(n351),
	.RN(FE_OFN1_reset_n),
	.CK(CTS_21),
	.Q(current_key[9]));
   DFFR_X1 current_key_reg_70_ (.D(n350),
	.RN(reset_n),
	.CK(CTS_21),
	.QN(n614));
   DFFR_X1 current_key_reg_51_ (.D(n349),
	.RN(reset_n),
	.CK(CTS_23),
	.Q(current_key[51]));
   DFFR_X1 current_key_reg_32_ (.D(n348),
	.RN(reset_n),
	.CK(CTS_23),
	.QN(n615));
   DFFR_X1 current_key_reg_13_ (.D(n347),
	.RN(reset_n),
	.CK(CTS_23),
	.Q(current_key[13]));
   DFFR_X1 current_key_reg_74_ (.D(n346),
	.RN(FE_OFN0_reset_n),
	.CK(CTS_23),
	.QN(n616));
   DFFR_X1 current_key_reg_55_ (.D(n345),
	.RN(FE_OFN0_reset_n),
	.CK(CTS_23),
	.Q(current_key[55]));
   DFFR_X1 current_key_reg_36_ (.D(n344),
	.RN(reset_n),
	.CK(CTS_19),
	.Q(current_key[36]),
	.QN(n629));
   DFFR_X1 current_key_reg_17_ (.D(n343),
	.RN(reset_n),
	.CK(CTS_19),
	.Q(current_key[17]));
   DFFR_X1 current_key_reg_78_ (.D(n342),
	.RN(reset_n),
	.CK(CTS_23),
	.QN(n617));
   DFFR_X1 current_key_reg_59_ (.D(n341),
	.RN(FE_OFN1_reset_n),
	.CK(CTS_24),
	.Q(current_key[59]));
   DFFR_X1 current_key_reg_40_ (.D(n340),
	.RN(FE_OFN0_reset_n),
	.CK(CTS_20),
	.QN(n618));
   DFFR_X1 current_key_reg_21_ (.D(n339),
	.RN(FE_OFN0_reset_n),
	.CK(CTS_20),
	.Q(current_key[21]),
	.QN(n632));
   DFFR_X1 current_key_reg_2_ (.D(n338),
	.RN(FE_OFN0_reset_n),
	.CK(CTS_20),
	.Q(current_key[2]));
   DFFR_X1 current_key_reg_63_ (.D(n337),
	.RN(FE_OFN1_reset_n),
	.CK(CTS_24),
	.QN(n597));
   DFFR_X1 current_key_reg_44_ (.D(n336),
	.RN(FE_OFN1_reset_n),
	.CK(CTS_24),
	.Q(current_key[44]));
   DFFR_X1 current_key_reg_25_ (.D(n335),
	.RN(FE_OFN1_reset_n),
	.CK(CTS_24),
	.QN(n619));
   DFFR_X1 current_key_reg_6_ (.D(n334),
	.RN(FE_OFN1_reset_n),
	.CK(CTS_21),
	.Q(current_key[6]));
   DFFR_X1 current_key_reg_67_ (.D(n333),
	.RN(FE_OFN1_reset_n),
	.CK(CTS_21),
	.QN(n598));
   DFFR_X1 current_key_reg_48_ (.D(n332),
	.RN(FE_OFN1_reset_n),
	.CK(CTS_21),
	.Q(current_key[48]));
   DFFR_X1 current_key_reg_29_ (.D(n331),
	.RN(reset_n),
	.CK(CTS_21),
	.QN(n620));
   DFFR_X1 current_key_reg_10_ (.D(n330),
	.RN(reset_n),
	.CK(CTS_21),
	.Q(current_key[10]));
   DFFR_X1 current_key_reg_71_ (.D(n329),
	.RN(reset_n),
	.CK(CTS_23),
	.QN(n599));
   DFFR_X1 current_key_reg_52_ (.D(n328),
	.RN(reset_n),
	.CK(CTS_23),
	.Q(current_key[52]));
   DFFR_X1 current_key_reg_33_ (.D(n327),
	.RN(FE_OFN0_reset_n),
	.CK(CTS_22),
	.QN(n621));
   DFFR_X1 current_key_reg_14_ (.D(n326),
	.RN(FE_OFN0_reset_n),
	.CK(CTS_22),
	.Q(current_key[14]));
   DFFR_X1 current_key_reg_75_ (.D(n325),
	.RN(FE_OFN0_reset_n),
	.CK(CTS_22),
	.QN(n600));
   DFFR_X1 current_key_reg_56_ (.D(n324),
	.RN(FE_OFN0_reset_n),
	.CK(CTS_22),
	.Q(current_key[56]));
   DFFR_X1 current_key_reg_37_ (.D(n323),
	.RN(reset_n),
	.CK(CTS_19),
	.Q(current_key[37]),
	.QN(n591));
   DFFR_X1 current_key_reg_18_ (.D(n322),
	.RN(reset_n),
	.CK(CTS_19),
	.Q(current_key[18]));
   DFFR_X1 current_key_reg_79_ (.D(n321),
	.RN(FE_OFN1_reset_n),
	.CK(CTS_21),
	.QN(n601));
   DFFR_X1 current_key_reg_60_ (.D(n320),
	.RN(FE_OFN1_reset_n),
	.CK(CTS_21),
	.Q(current_key[60]));
   DFFR_X1 current_key_reg_41_ (.D(n319),
	.RN(FE_OFN0_reset_n),
	.CK(CTS_20),
	.QN(n622));
   DFFR_X1 current_key_reg_22_ (.D(n318),
	.RN(FE_OFN0_reset_n),
	.CK(CTS_20),
	.Q(current_key[22]),
	.QN(n633));
   DFFR_X1 current_key_reg_3_ (.D(n317),
	.RN(FE_OFN0_reset_n),
	.CK(CTS_20),
	.Q(current_key[3]));
   DFFR_X1 current_key_reg_64_ (.D(n316),
	.RN(FE_OFN1_reset_n),
	.CK(CTS_24),
	.QN(n623));
   DFFR_X1 current_key_reg_45_ (.D(n315),
	.RN(FE_OFN1_reset_n),
	.CK(CTS_24),
	.Q(current_key[45]));
   DFFR_X1 current_key_reg_26_ (.D(n314),
	.RN(FE_OFN1_reset_n),
	.CK(CTS_24),
	.QN(n624));
   DFFR_X1 current_key_reg_7_ (.D(n313),
	.RN(FE_OFN0_reset_n),
	.CK(CTS_24),
	.Q(current_key[7]));
   DFFR_X1 current_key_reg_68_ (.D(n312),
	.RN(FE_OFN0_reset_n),
	.CK(CTS_23),
	.QN(n625));
   DFFR_X1 current_key_reg_49_ (.D(n311),
	.RN(FE_OFN0_reset_n),
	.CK(CTS_20),
	.Q(current_key[49]));
   DFFR_X1 current_key_reg_30_ (.D(n310),
	.RN(FE_OFN0_reset_n),
	.CK(CTS_22),
	.QN(n626));
   DFFR_X1 current_key_reg_11_ (.D(n309),
	.RN(FE_OFN0_reset_n),
	.CK(CTS_22),
	.Q(current_key[11]));
   DFFR_X1 current_key_reg_72_ (.D(n308),
	.RN(FE_OFN0_reset_n),
	.CK(CTS_22),
	.QN(n627));
   DFFR_X1 current_key_reg_53_ (.D(n307),
	.RN(FE_OFN0_reset_n),
	.CK(CTS_22),
	.Q(current_key[53]));
   DFFR_X1 current_key_reg_34_ (.D(n306),
	.RN(reset_n),
	.CK(CTS_19),
	.Q(current_key[34]),
	.QN(n630));
   DFFR_X1 state_reg_0_ (.D(n305),
	.RN(reset_n),
	.CK(CTS_19),
	.Q(state[0]));
   DFFR_X1 state_reg_1_ (.D(n304),
	.RN(reset_n),
	.CK(CTS_23),
	.Q(state[1]));
   DFFR_X1 state_reg_2_ (.D(n303),
	.RN(reset_n),
	.CK(CTS_23),
	.Q(state[2]));
   DFFR_X1 state_reg_3_ (.D(n302),
	.RN(reset_n),
	.CK(CTS_21),
	.Q(state[3]));
   DFFR_X1 state_reg_4_ (.D(n301),
	.RN(FE_OFN0_reset_n),
	.CK(CTS_22),
	.Q(state[4]));
   DFFR_X1 state_reg_5_ (.D(n300),
	.RN(FE_OFN0_reset_n),
	.CK(CTS_22),
	.Q(state[5]));
   DFFR_X1 state_reg_6_ (.D(n299),
	.RN(FE_OFN0_reset_n),
	.CK(CTS_20),
	.Q(state[6]));
   DFFR_X1 state_reg_7_ (.D(n298),
	.RN(FE_OFN0_reset_n),
	.CK(CTS_20),
	.Q(state[7]));
   DFFR_X1 state_reg_8_ (.D(n297),
	.RN(FE_OFN1_reset_n),
	.CK(CTS_23),
	.Q(state[8]));
   DFFR_X1 state_reg_9_ (.D(n296),
	.RN(reset_n),
	.CK(CTS_23),
	.Q(state[9]));
   DFFR_X1 state_reg_10_ (.D(n295),
	.RN(FE_OFN0_reset_n),
	.CK(CTS_23),
	.Q(state[10]));
   DFFR_X1 state_reg_11_ (.D(n294),
	.RN(FE_OFN1_reset_n),
	.CK(CTS_24),
	.Q(state[11]));
   DFFR_X1 state_reg_12_ (.D(n293),
	.RN(FE_OFN1_reset_n),
	.CK(CTS_21),
	.Q(state[12]));
   DFFR_X1 state_reg_13_ (.D(n292),
	.RN(reset_n),
	.CK(CTS_21),
	.Q(state[13]));
   DFFR_X1 state_reg_14_ (.D(n291),
	.RN(FE_OFN0_reset_n),
	.CK(CTS_20),
	.Q(state[14]));
   DFFR_X1 state_reg_15_ (.D(n290),
	.RN(FE_OFN1_reset_n),
	.CK(CTS_21),
	.Q(state[15]));
   DFFR_X1 state_reg_16_ (.D(n289),
	.RN(reset_n),
	.CK(CTS_19),
	.Q(state[16]));
   DFFR_X1 state_reg_17_ (.D(n288),
	.RN(FE_OFN0_reset_n),
	.CK(CTS_22),
	.Q(state[17]));
   DFFR_X1 state_reg_18_ (.D(n287),
	.RN(reset_n),
	.CK(CTS_23),
	.Q(state[18]));
   DFFR_X1 state_reg_19_ (.D(n286),
	.RN(reset_n),
	.CK(CTS_23),
	.Q(state[19]));
   DFFR_X1 state_reg_20_ (.D(n285),
	.RN(reset_n),
	.CK(CTS_19),
	.Q(state[20]));
   DFFR_X1 state_reg_21_ (.D(n284),
	.RN(reset_n),
	.CK(CTS_19),
	.Q(state[21]));
   DFFR_X1 state_reg_22_ (.D(n283),
	.RN(FE_OFN0_reset_n),
	.CK(CTS_22),
	.Q(state[22]));
   DFFR_X1 state_reg_23_ (.D(n282),
	.RN(FE_OFN1_reset_n),
	.CK(CTS_24),
	.Q(state[23]));
   DFFR_X1 state_reg_24_ (.D(n281),
	.RN(FE_OFN0_reset_n),
	.CK(CTS_20),
	.Q(state[24]));
   DFFR_X1 state_reg_25_ (.D(n280),
	.RN(FE_OFN0_reset_n),
	.CK(CTS_22),
	.Q(state[25]));
   DFFR_X1 state_reg_26_ (.D(n279),
	.RN(FE_OFN0_reset_n),
	.CK(CTS_22),
	.Q(state[26]));
   DFFR_X1 state_reg_27_ (.D(n278),
	.RN(FE_OFN0_reset_n),
	.CK(CTS_20),
	.Q(state[27]));
   DFFR_X1 state_reg_28_ (.D(n277),
	.RN(FE_OFN1_reset_n),
	.CK(CTS_24),
	.Q(state[28]));
   DFFR_X1 state_reg_29_ (.D(n276),
	.RN(FE_OFN1_reset_n),
	.CK(CTS_24),
	.Q(state[29]));
   DFFR_X1 state_reg_30_ (.D(n275),
	.RN(FE_OFN0_reset_n),
	.CK(CTS_20),
	.Q(state[30]));
   DFFR_X1 state_reg_31_ (.D(n274),
	.RN(FE_OFN1_reset_n),
	.CK(CTS_21),
	.Q(state[31]));
   DFFR_X1 state_reg_32_ (.D(n273),
	.RN(reset_n),
	.CK(CTS_21),
	.Q(state[32]));
   DFFR_X1 state_reg_33_ (.D(n272),
	.RN(FE_OFN0_reset_n),
	.CK(CTS_20),
	.Q(state[33]));
   DFFR_X1 state_reg_34_ (.D(n271),
	.RN(reset_n),
	.CK(CTS_23),
	.Q(state[34]));
   DFFR_X1 state_reg_35_ (.D(n270),
	.RN(reset_n),
	.CK(CTS_21),
	.Q(state[35]));
   DFFR_X1 state_reg_36_ (.D(n269),
	.RN(FE_OFN0_reset_n),
	.CK(CTS_22),
	.Q(state[36]));
   DFFR_X1 state_reg_37_ (.D(n268),
	.RN(FE_OFN0_reset_n),
	.CK(CTS_22),
	.Q(state[37]));
   DFFR_X1 state_reg_38_ (.D(n267),
	.RN(FE_OFN0_reset_n),
	.CK(CTS_22),
	.Q(state[38]));
   DFFR_X1 state_reg_39_ (.D(n266),
	.RN(FE_OFN0_reset_n),
	.CK(CTS_23),
	.Q(state[39]));
   DFFR_X1 state_reg_40_ (.D(n265),
	.RN(FE_OFN0_reset_n),
	.CK(CTS_22),
	.Q(state[40]));
   DFFR_X1 state_reg_41_ (.D(n264),
	.RN(FE_OFN0_reset_n),
	.CK(CTS_22),
	.Q(state[41]));
   DFFR_X1 state_reg_42_ (.D(n263),
	.RN(FE_OFN0_reset_n),
	.CK(CTS_22),
	.Q(state[42]));
   DFFR_X1 state_reg_43_ (.D(n262),
	.RN(FE_OFN0_reset_n),
	.CK(CTS_20),
	.Q(state[43]));
   DFFR_X1 state_reg_44_ (.D(n261),
	.RN(FE_OFN1_reset_n),
	.CK(CTS_24),
	.Q(state[44]));
   DFFR_X1 state_reg_45_ (.D(n260),
	.RN(FE_OFN1_reset_n),
	.CK(CTS_24),
	.Q(state[45]));
   DFFR_X1 state_reg_47_ (.D(n258),
	.RN(FE_OFN1_reset_n),
	.CK(CTS_24),
	.Q(state[47]));
   DFFR_X1 state_reg_48_ (.D(n257),
	.RN(FE_OFN1_reset_n),
	.CK(CTS_21),
	.Q(state[48]));
   DFFR_X1 state_reg_49_ (.D(n256),
	.RN(FE_OFN0_reset_n),
	.CK(CTS_20),
	.Q(state[49]));
   DFFR_X1 state_reg_50_ (.D(n255),
	.RN(FE_OFN1_reset_n),
	.CK(CTS_21),
	.Q(state[50]));
   DFFR_X1 state_reg_51_ (.D(n254),
	.RN(FE_OFN1_reset_n),
	.CK(CTS_21),
	.Q(state[51]));
   DFFR_X1 state_reg_52_ (.D(n253),
	.RN(reset_n),
	.CK(CTS_23),
	.Q(state[52]));
   DFFR_X1 state_reg_53_ (.D(n252),
	.RN(FE_OFN0_reset_n),
	.CK(CTS_23),
	.Q(state[53]));
   DFFR_X1 state_reg_54_ (.D(n251),
	.RN(FE_OFN1_reset_n),
	.CK(CTS_20),
	.Q(state[54]));
   DFFR_X1 state_reg_55_ (.D(n250),
	.RN(FE_OFN1_reset_n),
	.CK(CTS_24),
	.Q(state[55]));
   DFFR_X1 state_reg_56_ (.D(n249),
	.RN(FE_OFN0_reset_n),
	.CK(CTS_22),
	.Q(state[56]));
   DFFR_X1 state_reg_57_ (.D(n248),
	.RN(FE_OFN0_reset_n),
	.CK(CTS_22),
	.Q(state[57]));
   DFFR_X1 state_reg_58_ (.D(n247),
	.RN(FE_OFN0_reset_n),
	.CK(CTS_22),
	.Q(state[58]));
   DFFR_X1 state_reg_60_ (.D(n245),
	.RN(FE_OFN1_reset_n),
	.CK(CTS_21),
	.Q(state[60]));
   DFFR_X1 state_reg_61_ (.D(n244),
	.RN(reset_n),
	.CK(CTS_21),
	.Q(state[61]));
   DFFR_X1 state_reg_62_ (.D(n243),
	.RN(FE_OFN0_reset_n),
	.CK(CTS_23),
	.Q(state[62]));
   DFFR_X1 state_reg_63_ (.D(n242),
	.RN(FE_OFN1_reset_n),
	.CK(CTS_21),
	.Q(state[63]));
   NOR2_X2 U463 (.A1(fsm_state[1]),
	.A2(n592),
	.ZN(n414));
   NAND2_X1 U464 (.A1(round[0]),
	.A2(round[1]),
	.ZN(n404));
   NOR2_X1 U465 (.A1(n590),
	.A2(n404),
	.ZN(n397));
   NAND3_X1 U466 (.A1(round[3]),
	.A2(n414),
	.A3(n397),
	.ZN(n411));
   NOR3_X1 U467 (.A1(round[5]),
	.A2(n589),
	.A3(n411),
	.ZN(busy));
   XNOR2_X1 U468 (.A(state[63]),
	.B(n601),
	.ZN(ct[63]));
   XNOR2_X1 U469 (.A(state[62]),
	.B(n617),
	.ZN(ct[62]));
   XNOR2_X1 U470 (.A(state[61]),
	.B(n609),
	.ZN(ct[61]));
   XNOR2_X1 U471 (.A(state[60]),
	.B(n608),
	.ZN(ct[60]));
   XNOR2_X1 U472 (.A(state[59]),
	.B(n600),
	.ZN(ct[59]));
   XNOR2_X1 U473 (.A(state[58]),
	.B(n616),
	.ZN(ct[58]));
   XNOR2_X1 U474 (.A(state[57]),
	.B(n607),
	.ZN(ct[57]));
   XNOR2_X1 U475 (.A(state[56]),
	.B(n627),
	.ZN(ct[56]));
   XNOR2_X1 U476 (.A(state[55]),
	.B(n599),
	.ZN(ct[55]));
   XNOR2_X1 U477 (.A(state[54]),
	.B(n614),
	.ZN(ct[54]));
   XNOR2_X1 U478 (.A(state[53]),
	.B(n606),
	.ZN(ct[53]));
   XNOR2_X1 U479 (.A(state[52]),
	.B(n625),
	.ZN(ct[52]));
   XNOR2_X1 U480 (.A(state[51]),
	.B(n598),
	.ZN(ct[51]));
   XNOR2_X1 U481 (.A(state[50]),
	.B(n612),
	.ZN(ct[50]));
   XNOR2_X1 U482 (.A(state[49]),
	.B(n605),
	.ZN(ct[49]));
   XNOR2_X1 U483 (.A(state[48]),
	.B(n623),
	.ZN(ct[48]));
   XNOR2_X1 U484 (.A(state[47]),
	.B(n597),
	.ZN(ct[47]));
   XNOR2_X1 U485 (.A(state[46]),
	.B(n610),
	.ZN(ct[46]));
   XNOR2_X1 U486 (.A(state[45]),
	.B(n604),
	.ZN(ct[45]));
   XOR2_X1 U487 (.A(current_key[60]),
	.B(state[44]),
	.Z(ct[44]));
   XOR2_X1 U488 (.A(current_key[59]),
	.B(state[43]),
	.Z(ct[43]));
   XOR2_X1 U489 (.A(current_key[58]),
	.B(state[42]),
	.Z(ct[42]));
   XOR2_X1 U490 (.A(current_key[57]),
	.B(state[41]),
	.Z(ct[41]));
   XOR2_X1 U491 (.A(current_key[56]),
	.B(state[40]),
	.Z(ct[40]));
   XOR2_X1 U492 (.A(current_key[55]),
	.B(state[39]),
	.Z(ct[39]));
   XOR2_X1 U493 (.A(current_key[54]),
	.B(state[38]),
	.Z(ct[38]));
   XOR2_X1 U494 (.A(current_key[53]),
	.B(state[37]),
	.Z(ct[37]));
   XOR2_X1 U495 (.A(current_key[52]),
	.B(state[36]),
	.Z(ct[36]));
   XOR2_X1 U496 (.A(current_key[51]),
	.B(state[35]),
	.Z(ct[35]));
   XOR2_X1 U497 (.A(current_key[50]),
	.B(state[34]),
	.Z(ct[34]));
   XOR2_X1 U498 (.A(current_key[49]),
	.B(state[33]),
	.Z(ct[33]));
   XOR2_X2 U499 (.A(current_key[48]),
	.B(state[32]),
	.Z(ct[32]));
   XOR2_X1 U500 (.A(current_key[47]),
	.B(state[31]),
	.Z(ct[31]));
   XOR2_X1 U501 (.A(current_key[46]),
	.B(state[30]),
	.Z(ct[30]));
   XOR2_X1 U502 (.A(current_key[45]),
	.B(state[29]),
	.Z(ct[29]));
   XOR2_X1 U503 (.A(current_key[44]),
	.B(state[28]),
	.Z(ct[28]));
   XOR2_X1 U504 (.A(current_key[43]),
	.B(state[27]),
	.Z(ct[27]));
   XOR2_X1 U505 (.A(current_key[42]),
	.B(state[26]),
	.Z(ct[26]));
   XNOR2_X1 U506 (.A(state[25]),
	.B(n622),
	.ZN(ct[25]));
   XNOR2_X1 U507 (.A(state[24]),
	.B(n618),
	.ZN(ct[24]));
   XNOR2_X1 U508 (.A(state[23]),
	.B(n596),
	.ZN(ct[23]));
   XNOR2_X1 U509 (.A(state[22]),
	.B(n628),
	.ZN(ct[22]));
   XNOR2_X1 U510 (.A(state[21]),
	.B(n591),
	.ZN(ct[21]));
   XNOR2_X1 U511 (.A(state[20]),
	.B(n629),
	.ZN(ct[20]));
   XNOR2_X1 U512 (.A(state[19]),
	.B(n602),
	.ZN(ct[19]));
   XNOR2_X1 U513 (.A(state[18]),
	.B(n630),
	.ZN(ct[18]));
   XNOR2_X1 U514 (.A(state[17]),
	.B(n621),
	.ZN(ct[17]));
   XNOR2_X1 U515 (.A(state[16]),
	.B(n615),
	.ZN(ct[16]));
   XNOR2_X1 U516 (.A(state[15]),
	.B(n595),
	.ZN(ct[15]));
   XNOR2_X1 U517 (.A(state[14]),
	.B(n626),
	.ZN(ct[14]));
   XNOR2_X1 U518 (.A(state[13]),
	.B(n620),
	.ZN(ct[13]));
   XNOR2_X1 U519 (.A(state[12]),
	.B(n613),
	.ZN(ct[12]));
   XNOR2_X1 U520 (.A(state[11]),
	.B(n594),
	.ZN(ct[11]));
   XNOR2_X1 U521 (.A(state[10]),
	.B(n624),
	.ZN(ct[10]));
   XNOR2_X1 U522 (.A(state[9]),
	.B(n619),
	.ZN(ct[9]));
   XNOR2_X1 U523 (.A(state[8]),
	.B(n611),
	.ZN(ct[8]));
   XNOR2_X1 U524 (.A(state[7]),
	.B(n593),
	.ZN(ct[7]));
   XNOR2_X1 U525 (.A(state[6]),
	.B(n633),
	.ZN(ct[6]));
   XNOR2_X1 U526 (.A(state[5]),
	.B(n632),
	.ZN(ct[5]));
   XNOR2_X1 U527 (.A(state[4]),
	.B(n631),
	.ZN(ct[4]));
   XNOR2_X1 U528 (.A(state[3]),
	.B(n603),
	.ZN(ct[3]));
   XOR2_X1 U529 (.A(current_key[18]),
	.B(state[2]),
	.Z(ct[2]));
   XOR2_X1 U530 (.A(current_key[17]),
	.B(state[1]),
	.Z(ct[1]));
   XOR2_X1 U531 (.A(current_key[16]),
	.B(state[0]),
	.Z(ct[0]));
   NOR2_X1 U535 (.A1(n414),
	.A2(n581),
	.ZN(n403));
   NOR2_X1 U536 (.A1(n393),
	.A2(n403),
	.ZN(n394));
   AOI22_X1 U537 (.A1(n393),
	.A2(n403),
	.B1(fsm_state[0]),
	.B2(n394),
	.ZN(n392));
   INV_X1 U538 (.A(n414),
	.ZN(n405));
   NAND4_X1 U539 (.A1(n590),
	.A2(n393),
	.A3(n588),
	.A4(n589),
	.ZN(n395));
   OAI21_X1 U540 (.A(round[5]),
	.B1(round[3]),
	.B2(n395),
	.ZN(n413));
   NOR2_X1 U541 (.A1(n405),
	.A2(n413),
	.ZN(n585));
   OAI21_X1 U542 (.A(n586),
	.B1(n585),
	.B2(n592),
	.ZN(n391));
   AOI21_X1 U543 (.A(n585),
	.B1(n586),
	.B2(fsm_state[1]),
	.ZN(n396));
   INV_X1 U545 (.A(n397),
	.ZN(n408));
   AOI21_X1 U546 (.A(n403),
	.B1(n414),
	.B2(n408),
	.ZN(n410));
   OAI21_X1 U547 (.A(n410),
	.B1(round[3]),
	.B2(n405),
	.ZN(n398));
   INV_X1 U548 (.A(n398),
	.ZN(n412));
   OAI21_X1 U549 (.A(n412),
	.B1(n405),
	.B2(round[4]),
	.ZN(n399));
   AOI21_X1 U550 (.A(busy),
	.B1(n399),
	.B2(round[5]),
	.ZN(n400));
   INV_X1 U551 (.A(n400),
	.ZN(n389));
   AOI21_X1 U552 (.A(n403),
	.B1(n414),
	.B2(n393),
	.ZN(n402));
   NAND2_X1 U553 (.A1(n414),
	.A2(n588),
	.ZN(n401));
   OAI22_X1 U554 (.A1(n402),
	.A2(n588),
	.B1(n393),
	.B2(n401),
	.ZN(n388));
   AOI221_X1 U556 (.A(n403),
	.B1(n393),
	.B2(n414),
	.C1(n588),
	.C2(n414),
	.ZN(n406));
   NAND2_X1 U558 (.A1(n414),
	.A2(n634),
	.ZN(n409));
   OAI22_X1 U559 (.A1(n410),
	.A2(n634),
	.B1(n409),
	.B2(n408),
	.ZN(n386));
   AOI22_X1 U560 (.A1(round[4]),
	.A2(n412),
	.B1(n411),
	.B2(n589),
	.ZN(n385));
   AOI22_X1 U565 (.A1(n581),
	.A2(key[0]),
	.B1(FE_DBTN1_n502),
	.B2(current_key[0]),
	.ZN(n415));
   OAI21_X1 U566 (.A(n415),
	.B1(FE_OFN4_n560),
	.B2(n603),
	.ZN(n384));
   AOI22_X1 U567 (.A1(FE_OFN2_n581),
	.A2(key[61]),
	.B1(FE_OFN6_FE_DBTN0_n560),
	.B2(current_key[0]),
	.ZN(n416));
   OAI21_X1 U568 (.A(n416),
	.B1(FE_OFN7_n502),
	.B2(n604),
	.ZN(n383));
   AOI22_X1 U569 (.A1(FE_OFN582_n),
	.A2(key[42]),
	.B1(FE_OFN8_FE_DBTN1_n502),
	.B2(current_key[42]),
	.ZN(n417));
   OAI21_X1 U570 (.A(n417),
	.B1(FE_OFN4_n560),
	.B2(n604),
	.ZN(n382));
   AOI22_X1 U571 (.A1(FE_OFN582_n),
	.A2(key[23]),
	.B1(FE_OFN6_FE_DBTN0_n560),
	.B2(current_key[42]),
	.ZN(n418));
   OAI21_X1 U572 (.A(n418),
	.B1(FE_OFN7_n502),
	.B2(n593),
	.ZN(n381));
   AOI22_X1 U573 (.A1(FE_OFN582_n),
	.A2(key[4]),
	.B1(FE_OFN8_FE_DBTN1_n502),
	.B2(current_key[4]),
	.ZN(n419));
   OAI21_X1 U574 (.A(n419),
	.B1(FE_OFN4_n560),
	.B2(n593),
	.ZN(n380));
   AOI22_X1 U575 (.A1(FE_OFN582_n),
	.A2(key[65]),
	.B1(FE_OFN6_FE_DBTN0_n560),
	.B2(current_key[4]),
	.ZN(n420));
   OAI21_X1 U576 (.A(n420),
	.B1(FE_OFN7_n502),
	.B2(n605),
	.ZN(n379));
   AOI22_X1 U577 (.A1(FE_OFN582_n),
	.A2(key[46]),
	.B1(FE_OFN8_FE_DBTN1_n502),
	.B2(current_key[46]),
	.ZN(n421));
   OAI21_X1 U578 (.A(n421),
	.B1(FE_OFN4_n560),
	.B2(n605),
	.ZN(n378));
   AOI22_X1 U579 (.A1(FE_OFN582_n),
	.A2(key[27]),
	.B1(FE_OFN6_FE_DBTN0_n560),
	.B2(current_key[46]),
	.ZN(n422));
   OAI21_X1 U580 (.A(n422),
	.B1(FE_OFN7_n502),
	.B2(n594),
	.ZN(n377));
   AOI22_X1 U581 (.A1(FE_OFN2_n581),
	.A2(key[8]),
	.B1(FE_OFN8_FE_DBTN1_n502),
	.B2(current_key[8]),
	.ZN(n423));
   OAI21_X1 U582 (.A(n423),
	.B1(FE_OFN4_n560),
	.B2(n594),
	.ZN(n376));
   AOI22_X1 U584 (.A1(FE_OFN2_n581),
	.A2(key[69]),
	.B1(FE_OFN6_FE_DBTN0_n560),
	.B2(current_key[8]),
	.ZN(n424));
   OAI21_X1 U585 (.A(n424),
	.B1(FE_OFN7_n502),
	.B2(n606),
	.ZN(n375));
   AOI22_X1 U586 (.A1(FE_OFN2_n581),
	.A2(key[50]),
	.B1(FE_DBTN1_n502),
	.B2(current_key[50]),
	.ZN(n425));
   OAI21_X1 U587 (.A(n425),
	.B1(FE_OFN4_n560),
	.B2(n606),
	.ZN(n374));
   AOI22_X1 U590 (.A1(FE_OFN2_n581),
	.A2(key[31]),
	.B1(FE_OFN6_FE_DBTN0_n560),
	.B2(current_key[50]),
	.ZN(n426));
   OAI21_X1 U591 (.A(n426),
	.B1(FE_OFN7_n502),
	.B2(n595),
	.ZN(n373));
   AOI22_X1 U593 (.A1(FE_OFN3_n581),
	.A2(key[12]),
	.B1(FE_DBTN1_n502),
	.B2(current_key[12]),
	.ZN(n427));
   OAI21_X1 U594 (.A(n427),
	.B1(FE_OFN4_n560),
	.B2(n595),
	.ZN(n372));
   AOI22_X1 U595 (.A1(FE_OFN3_n581),
	.A2(key[73]),
	.B1(FE_OFN5_FE_DBTN0_n560),
	.B2(current_key[12]),
	.ZN(n428));
   OAI21_X1 U596 (.A(n428),
	.B1(FE_OFN7_n502),
	.B2(n607),
	.ZN(n371));
   AOI22_X1 U598 (.A1(FE_OFN3_n581),
	.A2(key[54]),
	.B1(FE_DBTN1_n502),
	.B2(current_key[54]),
	.ZN(n429));
   OAI21_X1 U599 (.A(n429),
	.B1(FE_OFN4_n560),
	.B2(n607),
	.ZN(n370));
   AOI22_X1 U600 (.A1(FE_OFN3_n581),
	.A2(key[35]),
	.B1(FE_OFN6_FE_DBTN0_n560),
	.B2(current_key[54]),
	.ZN(n430));
   OAI21_X1 U601 (.A(n430),
	.B1(FE_OFN7_n502),
	.B2(n602),
	.ZN(n369));
   AOI22_X1 U602 (.A1(n581),
	.A2(key[16]),
	.B1(FE_DBTN1_n502),
	.B2(current_key[16]),
	.ZN(n432));
   OAI221_X1 U603 (.A(FE_OFN6_FE_DBTN0_n560),
	.B1(round[1]),
	.B2(current_key[35]),
	.C1(n588),
	.C2(n602),
	.ZN(n431));
   NAND2_X1 U604 (.A1(n432),
	.A2(n431),
	.ZN(n368));
   AOI22_X1 U605 (.A1(n581),
	.A2(key[76]),
	.B1(FE_OFN6_FE_DBTN0_n560),
	.B2(next_round_key_76),
	.ZN(n433));
   OAI21_X1 U606 (.A(n433),
	.B1(FE_OFN7_n502),
	.B2(n608),
	.ZN(n367));
   AOI22_X1 U607 (.A1(FE_OFN3_n581),
	.A2(key[57]),
	.B1(FE_DBTN1_n502),
	.B2(current_key[57]),
	.ZN(n434));
   OAI21_X1 U608 (.A(n434),
	.B1(n560),
	.B2(n608),
	.ZN(n366));
   AOI22_X1 U609 (.A1(FE_OFN3_n581),
	.A2(key[38]),
	.B1(FE_OFN6_FE_DBTN0_n560),
	.B2(current_key[57]),
	.ZN(n435));
   OAI21_X1 U610 (.A(n435),
	.B1(FE_OFN7_n502),
	.B2(n628),
	.ZN(n365));
   AOI22_X1 U611 (.A1(n581),
	.A2(key[19]),
	.B1(FE_DBTN1_n502),
	.B2(current_key[19]),
	.ZN(n437));
   OAI221_X1 U612 (.A(FE_OFN6_FE_DBTN0_n560),
	.B1(round[4]),
	.B2(current_key[38]),
	.C1(n589),
	.C2(n628),
	.ZN(n436));
   NAND2_X1 U613 (.A1(n437),
	.A2(n436),
	.ZN(n364));
   AOI22_X1 U614 (.A1(n581),
	.A2(key[77]),
	.B1(FE_OFN6_FE_DBTN0_n560),
	.B2(next_round_key_77),
	.ZN(n438));
   OAI21_X1 U615 (.A(n438),
	.B1(FE_OFN7_n502),
	.B2(n609),
	.ZN(n363));
   AOI22_X1 U616 (.A1(FE_OFN3_n581),
	.A2(key[58]),
	.B1(FE_DBTN1_n502),
	.B2(current_key[58]),
	.ZN(n440));
   OAI21_X1 U617 (.A(n440),
	.B1(FE_OFN4_n560),
	.B2(n609),
	.ZN(n362));
   AOI22_X1 U618 (.A1(FE_OFN3_n581),
	.A2(key[39]),
	.B1(FE_OFN5_FE_DBTN0_n560),
	.B2(current_key[58]),
	.ZN(n441));
   OAI21_X1 U619 (.A(n441),
	.B1(FE_OFN7_n502),
	.B2(n596),
	.ZN(n361));
   AOI22_X1 U620 (.A1(FE_OFN3_n581),
	.A2(key[20]),
	.B1(FE_DBTN1_n502),
	.B2(current_key[20]),
	.ZN(n442));
   OAI21_X1 U621 (.A(n442),
	.B1(FE_OFN4_n560),
	.B2(n596),
	.ZN(n360));
   AOI22_X1 U622 (.A1(FE_OFN582_n),
	.A2(key[1]),
	.B1(FE_OFN8_FE_DBTN1_n502),
	.B2(current_key[1]),
	.ZN(n443));
   OAI21_X1 U623 (.A(n443),
	.B1(FE_OFN4_n560),
	.B2(n631),
	.ZN(n359));
   AOI22_X1 U624 (.A1(FE_OFN582_n),
	.A2(key[62]),
	.B1(FE_OFN5_FE_DBTN0_n560),
	.B2(current_key[1]),
	.ZN(n444));
   OAI21_X1 U625 (.A(n444),
	.B1(FE_OFN7_n502),
	.B2(n610),
	.ZN(n358));
   AOI22_X1 U626 (.A1(FE_OFN582_n),
	.A2(key[43]),
	.B1(FE_OFN8_FE_DBTN1_n502),
	.B2(current_key[43]),
	.ZN(n445));
   OAI21_X1 U627 (.A(n445),
	.B1(FE_OFN4_n560),
	.B2(n610),
	.ZN(n357));
   AOI22_X1 U628 (.A1(FE_OFN582_n),
	.A2(key[24]),
	.B1(FE_OFN6_FE_DBTN0_n560),
	.B2(current_key[43]),
	.ZN(n446));
   OAI21_X1 U629 (.A(n446),
	.B1(FE_OFN7_n502),
	.B2(n611),
	.ZN(n356));
   AOI22_X1 U630 (.A1(FE_OFN2_n581),
	.A2(key[5]),
	.B1(FE_OFN8_FE_DBTN1_n502),
	.B2(current_key[5]),
	.ZN(n447));
   OAI21_X1 U631 (.A(n447),
	.B1(FE_OFN4_n560),
	.B2(n611),
	.ZN(n355));
   AOI22_X1 U632 (.A1(FE_OFN2_n581),
	.A2(key[66]),
	.B1(FE_OFN6_FE_DBTN0_n560),
	.B2(current_key[5]),
	.ZN(n448));
   OAI21_X1 U633 (.A(n448),
	.B1(FE_OFN7_n502),
	.B2(n612),
	.ZN(n354));
   AOI22_X1 U634 (.A1(FE_OFN2_n581),
	.A2(key[47]),
	.B1(FE_OFN8_FE_DBTN1_n502),
	.B2(current_key[47]),
	.ZN(n449));
   OAI21_X1 U635 (.A(n449),
	.B1(FE_OFN4_n560),
	.B2(n612),
	.ZN(n353));
   AOI22_X1 U636 (.A1(FE_OFN2_n581),
	.A2(key[28]),
	.B1(FE_OFN6_FE_DBTN0_n560),
	.B2(current_key[47]),
	.ZN(n450));
   OAI21_X1 U637 (.A(n450),
	.B1(FE_OFN7_n502),
	.B2(n613),
	.ZN(n352));
   AOI22_X1 U638 (.A1(FE_OFN2_n581),
	.A2(key[9]),
	.B1(FE_OFN8_FE_DBTN1_n502),
	.B2(current_key[9]),
	.ZN(n451));
   OAI21_X1 U639 (.A(n451),
	.B1(FE_OFN4_n560),
	.B2(n613),
	.ZN(n351));
   AOI22_X1 U640 (.A1(FE_OFN2_n581),
	.A2(key[70]),
	.B1(FE_OFN6_FE_DBTN0_n560),
	.B2(current_key[9]),
	.ZN(n452));
   OAI21_X1 U641 (.A(n452),
	.B1(FE_OFN7_n502),
	.B2(n614),
	.ZN(n350));
   AOI22_X1 U642 (.A1(n581),
	.A2(key[51]),
	.B1(FE_DBTN1_n502),
	.B2(current_key[51]),
	.ZN(n453));
   OAI21_X1 U643 (.A(n453),
	.B1(FE_OFN4_n560),
	.B2(n614),
	.ZN(n349));
   AOI22_X1 U644 (.A1(n581),
	.A2(key[32]),
	.B1(FE_OFN6_FE_DBTN0_n560),
	.B2(current_key[51]),
	.ZN(n454));
   OAI21_X1 U645 (.A(n454),
	.B1(FE_OFN7_n502),
	.B2(n615),
	.ZN(n348));
   AOI22_X1 U646 (.A1(FE_OFN3_n581),
	.A2(key[13]),
	.B1(FE_DBTN1_n502),
	.B2(current_key[13]),
	.ZN(n455));
   OAI21_X1 U647 (.A(n455),
	.B1(FE_OFN4_n560),
	.B2(n615),
	.ZN(n347));
   AOI22_X1 U648 (.A1(FE_OFN3_n581),
	.A2(key[74]),
	.B1(FE_OFN5_FE_DBTN0_n560),
	.B2(current_key[13]),
	.ZN(n457));
   OAI21_X1 U649 (.A(n457),
	.B1(FE_OFN7_n502),
	.B2(n616),
	.ZN(n346));
   AOI22_X1 U650 (.A1(FE_OFN3_n581),
	.A2(key[55]),
	.B1(FE_DBTN1_n502),
	.B2(current_key[55]),
	.ZN(n458));
   OAI21_X1 U651 (.A(n458),
	.B1(FE_OFN4_n560),
	.B2(n616),
	.ZN(n345));
   AOI22_X1 U652 (.A1(FE_OFN3_n581),
	.A2(key[36]),
	.B1(FE_OFN5_FE_DBTN0_n560),
	.B2(current_key[55]),
	.ZN(n459));
   OAI21_X1 U653 (.A(n459),
	.B1(FE_OFN7_n502),
	.B2(n629),
	.ZN(n344));
   AOI22_X1 U654 (.A1(n581),
	.A2(key[17]),
	.B1(FE_DBTN1_n502),
	.B2(current_key[17]),
	.ZN(n461));
   OAI221_X1 U655 (.A(FE_OFN6_FE_DBTN0_n560),
	.B1(round[2]),
	.B2(current_key[36]),
	.C1(n590),
	.C2(n629),
	.ZN(n460));
   NAND2_X1 U656 (.A1(n461),
	.A2(n460),
	.ZN(n343));
   AOI22_X1 U657 (.A1(n581),
	.A2(key[78]),
	.B1(FE_OFN6_FE_DBTN0_n560),
	.B2(next_round_key_78),
	.ZN(n462));
   OAI21_X1 U658 (.A(n462),
	.B1(FE_OFN7_n502),
	.B2(n617),
	.ZN(n342));
   AOI22_X1 U659 (.A1(FE_OFN582_n),
	.A2(key[59]),
	.B1(FE_DBTN1_n502),
	.B2(current_key[59]),
	.ZN(n463));
   OAI21_X1 U660 (.A(n463),
	.B1(FE_OFN4_n560),
	.B2(n617),
	.ZN(n341));
   AOI22_X1 U661 (.A1(FE_OFN582_n),
	.A2(key[40]),
	.B1(FE_OFN5_FE_DBTN0_n560),
	.B2(current_key[59]),
	.ZN(n464));
   OAI21_X1 U662 (.A(n464),
	.B1(FE_OFN7_n502),
	.B2(n618),
	.ZN(n340));
   AOI22_X1 U663 (.A1(FE_OFN582_n),
	.A2(key[21]),
	.B1(FE_OFN8_FE_DBTN1_n502),
	.B2(current_key[21]),
	.ZN(n465));
   OAI21_X1 U664 (.A(n465),
	.B1(FE_OFN4_n560),
	.B2(n618),
	.ZN(n339));
   AOI22_X1 U666 (.A1(FE_OFN582_n),
	.A2(key[2]),
	.B1(FE_OFN8_FE_DBTN1_n502),
	.B2(current_key[2]),
	.ZN(n466));
   OAI21_X1 U667 (.A(n466),
	.B1(FE_OFN4_n560),
	.B2(n632),
	.ZN(n338));
   AOI22_X1 U668 (.A1(FE_OFN582_n),
	.A2(key[63]),
	.B1(FE_OFN6_FE_DBTN0_n560),
	.B2(current_key[2]),
	.ZN(n467));
   OAI21_X1 U669 (.A(n467),
	.B1(FE_OFN7_n502),
	.B2(n597),
	.ZN(n337));
   AOI22_X1 U670 (.A1(FE_OFN2_n581),
	.A2(key[44]),
	.B1(FE_OFN8_FE_DBTN1_n502),
	.B2(current_key[44]),
	.ZN(n468));
   OAI21_X1 U671 (.A(n468),
	.B1(FE_OFN4_n560),
	.B2(n597),
	.ZN(n336));
   AOI22_X1 U672 (.A1(FE_OFN2_n581),
	.A2(key[25]),
	.B1(FE_OFN6_FE_DBTN0_n560),
	.B2(current_key[44]),
	.ZN(n469));
   OAI21_X1 U673 (.A(n469),
	.B1(FE_OFN7_n502),
	.B2(n619),
	.ZN(n335));
   AOI22_X1 U674 (.A1(FE_OFN2_n581),
	.A2(key[6]),
	.B1(FE_OFN8_FE_DBTN1_n502),
	.B2(current_key[6]),
	.ZN(n470));
   OAI21_X1 U675 (.A(n470),
	.B1(FE_OFN4_n560),
	.B2(n619),
	.ZN(n334));
   AOI22_X1 U676 (.A1(FE_OFN2_n581),
	.A2(key[67]),
	.B1(FE_OFN6_FE_DBTN0_n560),
	.B2(current_key[6]),
	.ZN(n471));
   OAI21_X1 U677 (.A(n471),
	.B1(FE_OFN7_n502),
	.B2(n598),
	.ZN(n333));
   AOI22_X1 U678 (.A1(FE_OFN2_n581),
	.A2(key[48]),
	.B1(FE_OFN8_FE_DBTN1_n502),
	.B2(current_key[48]),
	.ZN(n472));
   OAI21_X1 U679 (.A(n472),
	.B1(FE_OFN4_n560),
	.B2(n598),
	.ZN(n332));
   AOI22_X1 U680 (.A1(n581),
	.A2(key[29]),
	.B1(FE_OFN6_FE_DBTN0_n560),
	.B2(current_key[48]),
	.ZN(n473));
   OAI21_X1 U681 (.A(n473),
	.B1(FE_OFN7_n502),
	.B2(n620),
	.ZN(n331));
   AOI22_X1 U682 (.A1(n581),
	.A2(key[10]),
	.B1(FE_DBTN1_n502),
	.B2(current_key[10]),
	.ZN(n474));
   OAI21_X1 U683 (.A(n474),
	.B1(FE_OFN4_n560),
	.B2(n620),
	.ZN(n330));
   AOI22_X1 U684 (.A1(FE_OFN2_n581),
	.A2(key[71]),
	.B1(FE_OFN6_FE_DBTN0_n560),
	.B2(current_key[10]),
	.ZN(n475));
   OAI21_X1 U685 (.A(n475),
	.B1(FE_OFN7_n502),
	.B2(n599),
	.ZN(n329));
   AOI22_X1 U686 (.A1(FE_OFN3_n581),
	.A2(key[52]),
	.B1(FE_DBTN1_n502),
	.B2(current_key[52]),
	.ZN(n476));
   OAI21_X1 U687 (.A(n476),
	.B1(FE_OFN4_n560),
	.B2(n599),
	.ZN(n328));
   AOI22_X1 U688 (.A1(FE_OFN3_n581),
	.A2(key[33]),
	.B1(FE_OFN5_FE_DBTN0_n560),
	.B2(current_key[52]),
	.ZN(n477));
   OAI21_X1 U689 (.A(n477),
	.B1(n502),
	.B2(n621),
	.ZN(n327));
   AOI22_X1 U690 (.A1(FE_OFN3_n581),
	.A2(key[14]),
	.B1(FE_DBTN1_n502),
	.B2(current_key[14]),
	.ZN(n478));
   OAI21_X1 U691 (.A(n478),
	.B1(FE_OFN4_n560),
	.B2(n621),
	.ZN(n326));
   AOI22_X1 U692 (.A1(FE_OFN3_n581),
	.A2(key[75]),
	.B1(FE_OFN5_FE_DBTN0_n560),
	.B2(current_key[14]),
	.ZN(n479));
   OAI21_X1 U693 (.A(n479),
	.B1(n502),
	.B2(n600),
	.ZN(n325));
   AOI22_X1 U694 (.A1(FE_OFN3_n581),
	.A2(key[56]),
	.B1(FE_DBTN1_n502),
	.B2(current_key[56]),
	.ZN(n480));
   OAI21_X1 U695 (.A(n480),
	.B1(FE_OFN4_n560),
	.B2(n600),
	.ZN(n324));
   AOI22_X1 U696 (.A1(FE_OFN3_n581),
	.A2(key[37]),
	.B1(FE_OFN5_FE_DBTN0_n560),
	.B2(current_key[56]),
	.ZN(n481));
   OAI21_X1 U697 (.A(n481),
	.B1(FE_OFN7_n502),
	.B2(n591),
	.ZN(n323));
   AOI22_X1 U698 (.A1(n581),
	.A2(key[18]),
	.B1(FE_DBTN1_n502),
	.B2(current_key[18]),
	.ZN(n483));
   OAI221_X1 U699 (.A(FE_OFN6_FE_DBTN0_n560),
	.B1(round[3]),
	.B2(current_key[37]),
	.C1(n634),
	.C2(n591),
	.ZN(n482));
   NAND2_X1 U700 (.A1(n483),
	.A2(n482),
	.ZN(n322));
   AOI22_X1 U701 (.A1(n581),
	.A2(key[79]),
	.B1(FE_OFN6_FE_DBTN0_n560),
	.B2(next_round_key_79),
	.ZN(n484));
   OAI21_X1 U702 (.A(n484),
	.B1(FE_OFN7_n502),
	.B2(n601),
	.ZN(n321));
   AOI22_X1 U703 (.A1(FE_OFN2_n581),
	.A2(key[60]),
	.B1(FE_OFN8_FE_DBTN1_n502),
	.B2(current_key[60]),
	.ZN(n485));
   OAI21_X1 U704 (.A(n485),
	.B1(FE_OFN4_n560),
	.B2(n601),
	.ZN(n320));
   AOI22_X1 U705 (.A1(FE_OFN2_n581),
	.A2(key[41]),
	.B1(FE_OFN6_FE_DBTN0_n560),
	.B2(current_key[60]),
	.ZN(n486));
   OAI21_X1 U706 (.A(n486),
	.B1(FE_OFN7_n502),
	.B2(n622),
	.ZN(n319));
   AOI22_X1 U707 (.A1(FE_OFN582_n),
	.A2(key[22]),
	.B1(FE_OFN8_FE_DBTN1_n502),
	.B2(current_key[22]),
	.ZN(n487));
   OAI21_X1 U708 (.A(n487),
	.B1(FE_OFN4_n560),
	.B2(n622),
	.ZN(n318));
   AOI22_X1 U709 (.A1(FE_OFN582_n),
	.A2(key[3]),
	.B1(FE_OFN8_FE_DBTN1_n502),
	.B2(current_key[3]),
	.ZN(n489));
   OAI21_X1 U710 (.A(n489),
	.B1(FE_OFN4_n560),
	.B2(n633),
	.ZN(n317));
   AOI22_X1 U711 (.A1(FE_OFN582_n),
	.A2(key[64]),
	.B1(FE_OFN6_FE_DBTN0_n560),
	.B2(current_key[3]),
	.ZN(n490));
   OAI21_X1 U712 (.A(n490),
	.B1(FE_OFN7_n502),
	.B2(n623),
	.ZN(n316));
   AOI22_X1 U714 (.A1(FE_OFN2_n581),
	.A2(key[45]),
	.B1(FE_OFN8_FE_DBTN1_n502),
	.B2(current_key[45]),
	.ZN(n491));
   OAI21_X1 U715 (.A(n491),
	.B1(FE_OFN4_n560),
	.B2(n623),
	.ZN(n315));
   AOI22_X1 U716 (.A1(FE_OFN2_n581),
	.A2(key[26]),
	.B1(FE_OFN6_FE_DBTN0_n560),
	.B2(current_key[45]),
	.ZN(n492));
   OAI21_X1 U717 (.A(n492),
	.B1(FE_OFN7_n502),
	.B2(n624),
	.ZN(n314));
   AOI22_X1 U718 (.A1(FE_OFN2_n581),
	.A2(key[7]),
	.B1(FE_OFN8_FE_DBTN1_n502),
	.B2(current_key[7]),
	.ZN(n493));
   OAI21_X1 U719 (.A(n493),
	.B1(FE_OFN4_n560),
	.B2(n624),
	.ZN(n313));
   AOI22_X1 U720 (.A1(FE_OFN2_n581),
	.A2(key[68]),
	.B1(FE_OFN6_FE_DBTN0_n560),
	.B2(current_key[7]),
	.ZN(n495));
   OAI21_X1 U721 (.A(n495),
	.B1(FE_OFN7_n502),
	.B2(n625),
	.ZN(n312));
   AOI22_X1 U722 (.A1(FE_OFN582_n),
	.A2(key[49]),
	.B1(FE_DBTN1_n502),
	.B2(current_key[49]),
	.ZN(n496));
   OAI21_X1 U723 (.A(n496),
	.B1(FE_OFN4_n560),
	.B2(n625),
	.ZN(n311));
   AOI22_X1 U724 (.A1(FE_OFN582_n),
	.A2(key[30]),
	.B1(FE_OFN5_FE_DBTN0_n560),
	.B2(current_key[49]),
	.ZN(n497));
   OAI21_X1 U725 (.A(n497),
	.B1(FE_OFN7_n502),
	.B2(n626),
	.ZN(n310));
   AOI22_X1 U726 (.A1(FE_OFN3_n581),
	.A2(key[11]),
	.B1(FE_DBTN1_n502),
	.B2(current_key[11]),
	.ZN(n498));
   OAI21_X1 U727 (.A(n498),
	.B1(FE_OFN4_n560),
	.B2(n626),
	.ZN(n309));
   AOI22_X1 U728 (.A1(FE_OFN3_n581),
	.A2(key[72]),
	.B1(FE_OFN5_FE_DBTN0_n560),
	.B2(current_key[11]),
	.ZN(n499));
   OAI21_X1 U729 (.A(n499),
	.B1(FE_OFN7_n502),
	.B2(n627),
	.ZN(n308));
   AOI22_X1 U730 (.A1(FE_OFN3_n581),
	.A2(key[53]),
	.B1(FE_DBTN1_n502),
	.B2(current_key[53]),
	.ZN(n500));
   OAI21_X1 U731 (.A(n500),
	.B1(FE_OFN4_n560),
	.B2(n627),
	.ZN(n307));
   AOI22_X1 U732 (.A1(FE_OFN3_n581),
	.A2(key[34]),
	.B1(FE_OFN5_FE_DBTN0_n560),
	.B2(current_key[53]),
	.ZN(n501));
   OAI21_X1 U733 (.A(n501),
	.B1(FE_OFN7_n502),
	.B2(n630),
	.ZN(n306));
   AOI222_X1 U734 (.A1(n581),
	.A2(pt[0]),
	.B1(FE_OFN6_FE_DBTN0_n560),
	.B2(perm_state[0]),
	.C1(FE_DBTN1_n502),
	.C2(state[0]),
	.ZN(n503));
   INV_X1 U735 (.A(n503),
	.ZN(n305));
   AOI222_X1 U737 (.A1(n581),
	.A2(pt[1]),
	.B1(FE_OFN6_FE_DBTN0_n560),
	.B2(perm_state[1]),
	.C1(FE_DBTN1_n502),
	.C2(state[1]),
	.ZN(n504));
   INV_X1 U738 (.A(n504),
	.ZN(n304));
   AOI222_X1 U739 (.A1(n581),
	.A2(pt[2]),
	.B1(FE_OFN6_FE_DBTN0_n560),
	.B2(perm_state[2]),
	.C1(FE_DBTN1_n502),
	.C2(state[2]),
	.ZN(n505));
   INV_X1 U740 (.A(n505),
	.ZN(n303));
   AOI222_X1 U741 (.A1(n581),
	.A2(pt[3]),
	.B1(FE_OFN6_FE_DBTN0_n560),
	.B2(perm_state[3]),
	.C1(FE_DBTN1_n502),
	.C2(state[3]),
	.ZN(n506));
   INV_X1 U742 (.A(n506),
	.ZN(n302));
   AOI222_X1 U743 (.A1(FE_OFN3_n581),
	.A2(pt[4]),
	.B1(FE_OFN5_FE_DBTN0_n560),
	.B2(perm_state[4]),
	.C1(FE_DBTN1_n502),
	.C2(state[4]),
	.ZN(n508));
   INV_X1 U744 (.A(n508),
	.ZN(n301));
   AOI222_X1 U745 (.A1(FE_OFN3_n581),
	.A2(pt[5]),
	.B1(FE_OFN5_FE_DBTN0_n560),
	.B2(perm_state[5]),
	.C1(FE_DBTN1_n502),
	.C2(state[5]),
	.ZN(n509));
   INV_X1 U746 (.A(n509),
	.ZN(n300));
   AOI222_X1 U747 (.A1(FE_OFN582_n),
	.A2(pt[6]),
	.B1(FE_OFN5_FE_DBTN0_n560),
	.B2(perm_state[6]),
	.C1(FE_OFN8_FE_DBTN1_n502),
	.C2(state[6]),
	.ZN(n510));
   INV_X1 U748 (.A(n510),
	.ZN(n299));
   AOI222_X1 U749 (.A1(FE_OFN582_n),
	.A2(pt[7]),
	.B1(FE_OFN6_FE_DBTN0_n560),
	.B2(perm_state[7]),
	.C1(FE_OFN8_FE_DBTN1_n502),
	.C2(state[7]),
	.ZN(n511));
   INV_X1 U750 (.A(n511),
	.ZN(n298));
   AOI222_X1 U751 (.A1(FE_OFN2_n581),
	.A2(pt[8]),
	.B1(FE_OFN6_FE_DBTN0_n560),
	.B2(perm_state[8]),
	.C1(FE_OFN8_FE_DBTN1_n502),
	.C2(state[8]),
	.ZN(n512));
   INV_X1 U752 (.A(n512),
	.ZN(n297));
   AOI222_X1 U753 (.A1(FE_OFN3_n581),
	.A2(pt[9]),
	.B1(FE_OFN5_FE_DBTN0_n560),
	.B2(perm_state[9]),
	.C1(FE_DBTN1_n502),
	.C2(state[9]),
	.ZN(n513));
   INV_X1 U754 (.A(n513),
	.ZN(n296));
   AOI222_X1 U755 (.A1(FE_OFN3_n581),
	.A2(pt[10]),
	.B1(FE_OFN5_FE_DBTN0_n560),
	.B2(perm_state[10]),
	.C1(FE_DBTN1_n502),
	.C2(state[10]),
	.ZN(n515));
   INV_X1 U756 (.A(n515),
	.ZN(n295));
   AOI222_X1 U758 (.A1(FE_OFN582_n),
	.A2(pt[11]),
	.B1(FE_OFN6_FE_DBTN0_n560),
	.B2(perm_state[11]),
	.C1(FE_OFN8_FE_DBTN1_n502),
	.C2(state[11]),
	.ZN(n516));
   INV_X1 U759 (.A(n516),
	.ZN(n294));
   AOI222_X1 U760 (.A1(FE_OFN2_n581),
	.A2(pt[12]),
	.B1(FE_OFN6_FE_DBTN0_n560),
	.B2(perm_state[12]),
	.C1(FE_OFN8_FE_DBTN1_n502),
	.C2(state[12]),
	.ZN(n517));
   INV_X1 U761 (.A(n517),
	.ZN(n293));
   AOI222_X1 U762 (.A1(FE_OFN2_n581),
	.A2(pt[13]),
	.B1(FE_OFN6_FE_DBTN0_n560),
	.B2(perm_state[13]),
	.C1(FE_DBTN1_n502),
	.C2(state[13]),
	.ZN(n518));
   INV_X1 U763 (.A(n518),
	.ZN(n292));
   AOI222_X1 U764 (.A1(FE_OFN3_n581),
	.A2(pt[14]),
	.B1(FE_OFN5_FE_DBTN0_n560),
	.B2(perm_state[14]),
	.C1(FE_DBTN1_n502),
	.C2(state[14]),
	.ZN(n519));
   INV_X1 U765 (.A(n519),
	.ZN(n291));
   AOI222_X1 U766 (.A1(n581),
	.A2(pt[15]),
	.B1(FE_OFN6_FE_DBTN0_n560),
	.B2(perm_state[15]),
	.C1(FE_DBTN1_n502),
	.C2(state[15]),
	.ZN(n520));
   INV_X1 U767 (.A(n520),
	.ZN(n290));
   AOI222_X1 U768 (.A1(n581),
	.A2(pt[16]),
	.B1(FE_OFN6_FE_DBTN0_n560),
	.B2(perm_state[16]),
	.C1(FE_DBTN1_n502),
	.C2(state[16]),
	.ZN(n521));
   INV_X1 U769 (.A(n521),
	.ZN(n289));
   AOI222_X1 U770 (.A1(FE_OFN3_n581),
	.A2(pt[17]),
	.B1(FE_OFN5_FE_DBTN0_n560),
	.B2(perm_state[17]),
	.C1(FE_DBTN1_n502),
	.C2(state[17]),
	.ZN(n522));
   INV_X1 U771 (.A(n522),
	.ZN(n288));
   AOI222_X1 U772 (.A1(FE_OFN3_n581),
	.A2(pt[18]),
	.B1(FE_OFN5_FE_DBTN0_n560),
	.B2(perm_state[18]),
	.C1(FE_DBTN1_n502),
	.C2(state[18]),
	.ZN(n523));
   INV_X1 U773 (.A(n523),
	.ZN(n287));
   AOI222_X1 U774 (.A1(n581),
	.A2(pt[19]),
	.B1(FE_OFN6_FE_DBTN0_n560),
	.B2(perm_state[19]),
	.C1(FE_DBTN1_n502),
	.C2(state[19]),
	.ZN(n524));
   INV_X1 U775 (.A(n524),
	.ZN(n286));
   AOI222_X1 U776 (.A1(FE_OFN3_n581),
	.A2(pt[20]),
	.B1(FE_OFN6_FE_DBTN0_n560),
	.B2(perm_state[20]),
	.C1(FE_DBTN1_n502),
	.C2(state[20]),
	.ZN(n525));
   INV_X1 U777 (.A(n525),
	.ZN(n285));
   AOI222_X1 U778 (.A1(FE_OFN3_n581),
	.A2(pt[21]),
	.B1(FE_OFN5_FE_DBTN0_n560),
	.B2(perm_state[21]),
	.C1(FE_DBTN1_n502),
	.C2(state[21]),
	.ZN(n526));
   INV_X1 U779 (.A(n526),
	.ZN(n284));
   AOI222_X1 U780 (.A1(FE_OFN3_n581),
	.A2(pt[22]),
	.B1(FE_OFN5_FE_DBTN0_n560),
	.B2(perm_state[22]),
	.C1(FE_DBTN1_n502),
	.C2(state[22]),
	.ZN(n528));
   INV_X1 U781 (.A(n528),
	.ZN(n283));
   AOI222_X1 U782 (.A1(FE_OFN2_n581),
	.A2(pt[23]),
	.B1(FE_OFN6_FE_DBTN0_n560),
	.B2(perm_state[23]),
	.C1(FE_OFN8_FE_DBTN1_n502),
	.C2(state[23]),
	.ZN(n529));
   INV_X1 U783 (.A(n529),
	.ZN(n282));
   AOI222_X1 U784 (.A1(FE_OFN582_n),
	.A2(pt[24]),
	.B1(FE_OFN5_FE_DBTN0_n560),
	.B2(perm_state[24]),
	.C1(FE_DBTN1_n502),
	.C2(state[24]),
	.ZN(n530));
   INV_X1 U785 (.A(n530),
	.ZN(n281));
   AOI222_X1 U787 (.A1(FE_OFN3_n581),
	.A2(pt[25]),
	.B1(FE_OFN5_FE_DBTN0_n560),
	.B2(perm_state[25]),
	.C1(FE_DBTN1_n502),
	.C2(state[25]),
	.ZN(n531));
   INV_X1 U788 (.A(n531),
	.ZN(n280));
   AOI222_X1 U789 (.A1(FE_OFN3_n581),
	.A2(pt[26]),
	.B1(FE_OFN5_FE_DBTN0_n560),
	.B2(perm_state[26]),
	.C1(FE_OFN8_FE_DBTN1_n502),
	.C2(state[26]),
	.ZN(n533));
   INV_X1 U790 (.A(n533),
	.ZN(n279));
   AOI222_X1 U791 (.A1(FE_OFN582_n),
	.A2(pt[27]),
	.B1(FE_OFN6_FE_DBTN0_n560),
	.B2(perm_state[27]),
	.C1(FE_OFN8_FE_DBTN1_n502),
	.C2(state[27]),
	.ZN(n534));
   INV_X1 U792 (.A(n534),
	.ZN(n278));
   AOI222_X1 U793 (.A1(FE_OFN2_n581),
	.A2(pt[28]),
	.B1(FE_OFN6_FE_DBTN0_n560),
	.B2(perm_state[28]),
	.C1(FE_OFN8_FE_DBTN1_n502),
	.C2(state[28]),
	.ZN(n535));
   INV_X1 U794 (.A(n535),
	.ZN(n277));
   AOI222_X1 U795 (.A1(FE_OFN2_n581),
	.A2(pt[29]),
	.B1(FE_OFN6_FE_DBTN0_n560),
	.B2(perm_state[29]),
	.C1(FE_OFN8_FE_DBTN1_n502),
	.C2(state[29]),
	.ZN(n536));
   INV_X1 U796 (.A(n536),
	.ZN(n276));
   AOI222_X1 U797 (.A1(FE_OFN582_n),
	.A2(pt[30]),
	.B1(FE_OFN6_FE_DBTN0_n560),
	.B2(perm_state[30]),
	.C1(FE_OFN8_FE_DBTN1_n502),
	.C2(state[30]),
	.ZN(n537));
   INV_X1 U798 (.A(n537),
	.ZN(n275));
   AOI222_X1 U799 (.A1(FE_OFN2_n581),
	.A2(pt[31]),
	.B1(FE_OFN6_FE_DBTN0_n560),
	.B2(perm_state[31]),
	.C1(FE_OFN8_FE_DBTN1_n502),
	.C2(state[31]),
	.ZN(n538));
   INV_X1 U800 (.A(n538),
	.ZN(n274));
   AOI222_X1 U801 (.A1(n581),
	.A2(pt[32]),
	.B1(FE_OFN6_FE_DBTN0_n560),
	.B2(perm_state[32]),
	.C1(FE_DBTN1_n502),
	.C2(state[32]),
	.ZN(n539));
   INV_X1 U802 (.A(n539),
	.ZN(n273));
   AOI222_X1 U803 (.A1(FE_OFN582_n),
	.A2(pt[33]),
	.B1(FE_OFN5_FE_DBTN0_n560),
	.B2(perm_state[33]),
	.C1(FE_DBTN1_n502),
	.C2(state[33]),
	.ZN(n540));
   INV_X1 U804 (.A(n540),
	.ZN(n272));
   AOI222_X1 U805 (.A1(FE_OFN2_n581),
	.A2(pt[34]),
	.B1(FE_OFN6_FE_DBTN0_n560),
	.B2(perm_state[34]),
	.C1(FE_DBTN1_n502),
	.C2(state[34]),
	.ZN(n541));
   INV_X1 U806 (.A(n541),
	.ZN(n271));
   AOI222_X1 U807 (.A1(n581),
	.A2(pt[35]),
	.B1(FE_OFN6_FE_DBTN0_n560),
	.B2(perm_state[35]),
	.C1(FE_DBTN1_n502),
	.C2(state[35]),
	.ZN(n542));
   INV_X1 U808 (.A(n542),
	.ZN(n270));
   AOI222_X1 U810 (.A1(FE_OFN3_n581),
	.A2(pt[36]),
	.B1(FE_OFN5_FE_DBTN0_n560),
	.B2(perm_state[36]),
	.C1(FE_DBTN1_n502),
	.C2(state[36]),
	.ZN(n543));
   INV_X1 U811 (.A(n543),
	.ZN(n269));
   AOI222_X1 U812 (.A1(FE_OFN3_n581),
	.A2(pt[37]),
	.B1(FE_OFN5_FE_DBTN0_n560),
	.B2(perm_state[37]),
	.C1(FE_DBTN1_n502),
	.C2(state[37]),
	.ZN(n544));
   INV_X1 U813 (.A(n544),
	.ZN(n268));
   AOI222_X1 U814 (.A1(FE_OFN3_n581),
	.A2(pt[38]),
	.B1(FE_OFN5_FE_DBTN0_n560),
	.B2(perm_state[38]),
	.C1(FE_DBTN1_n502),
	.C2(state[38]),
	.ZN(n547));
   INV_X1 U815 (.A(n547),
	.ZN(n267));
   AOI222_X1 U816 (.A1(FE_OFN3_n581),
	.A2(pt[39]),
	.B1(FE_OFN5_FE_DBTN0_n560),
	.B2(perm_state[39]),
	.C1(FE_DBTN1_n502),
	.C2(state[39]),
	.ZN(n548));
   INV_X1 U817 (.A(n548),
	.ZN(n266));
   AOI222_X1 U818 (.A1(FE_OFN3_n581),
	.A2(pt[40]),
	.B1(FE_OFN5_FE_DBTN0_n560),
	.B2(perm_state[40]),
	.C1(FE_DBTN1_n502),
	.C2(state[40]),
	.ZN(n549));
   INV_X1 U819 (.A(n549),
	.ZN(n265));
   AOI222_X1 U820 (.A1(FE_OFN3_n581),
	.A2(pt[41]),
	.B1(FE_OFN5_FE_DBTN0_n560),
	.B2(perm_state[41]),
	.C1(FE_DBTN1_n502),
	.C2(state[41]),
	.ZN(n550));
   INV_X1 U821 (.A(n550),
	.ZN(n264));
   AOI222_X1 U822 (.A1(FE_OFN3_n581),
	.A2(pt[42]),
	.B1(FE_OFN5_FE_DBTN0_n560),
	.B2(perm_state[42]),
	.C1(FE_DBTN1_n502),
	.C2(state[42]),
	.ZN(n551));
   INV_X1 U823 (.A(n551),
	.ZN(n263));
   AOI222_X1 U824 (.A1(FE_OFN582_n),
	.A2(pt[43]),
	.B1(FE_OFN6_FE_DBTN0_n560),
	.B2(perm_state[43]),
	.C1(FE_OFN8_FE_DBTN1_n502),
	.C2(state[43]),
	.ZN(n552));
   INV_X1 U825 (.A(n552),
	.ZN(n262));
   AOI222_X1 U826 (.A1(FE_OFN2_n581),
	.A2(pt[44]),
	.B1(FE_OFN6_FE_DBTN0_n560),
	.B2(perm_state[44]),
	.C1(FE_OFN8_FE_DBTN1_n502),
	.C2(state[44]),
	.ZN(n553));
   INV_X1 U827 (.A(n553),
	.ZN(n261));
   AOI222_X1 U828 (.A1(FE_OFN2_n581),
	.A2(pt[45]),
	.B1(FE_OFN6_FE_DBTN0_n560),
	.B2(perm_state[45]),
	.C1(FE_OFN8_FE_DBTN1_n502),
	.C2(state[45]),
	.ZN(n554));
   INV_X1 U829 (.A(n554),
	.ZN(n260));
   AOI222_X1 U830 (.A1(FE_OFN582_n),
	.A2(pt[46]),
	.B1(FE_OFN5_FE_DBTN0_n560),
	.B2(perm_state[46]),
	.C1(FE_OFN8_FE_DBTN1_n502),
	.C2(state[46]),
	.ZN(n555));
   AOI222_X1 U832 (.A1(FE_OFN2_n581),
	.A2(pt[47]),
	.B1(FE_OFN6_FE_DBTN0_n560),
	.B2(perm_state[47]),
	.C1(FE_OFN8_FE_DBTN1_n502),
	.C2(state[47]),
	.ZN(n557));
   INV_X1 U833 (.A(n557),
	.ZN(n258));
   AOI222_X1 U834 (.A1(FE_OFN2_n581),
	.A2(pt[48]),
	.B1(FE_OFN6_FE_DBTN0_n560),
	.B2(perm_state[48]),
	.C1(FE_OFN8_FE_DBTN1_n502),
	.C2(state[48]),
	.ZN(n559));
   INV_X1 U835 (.A(n559),
	.ZN(n257));
   AOI222_X1 U837 (.A1(FE_OFN582_n),
	.A2(pt[49]),
	.B1(FE_OFN6_FE_DBTN0_n560),
	.B2(perm_state[49]),
	.C1(FE_OFN8_FE_DBTN1_n502),
	.C2(state[49]),
	.ZN(n561));
   INV_X1 U838 (.A(n561),
	.ZN(n256));
   AOI222_X1 U839 (.A1(FE_OFN2_n581),
	.A2(pt[50]),
	.B1(FE_OFN6_FE_DBTN0_n560),
	.B2(perm_state[50]),
	.C1(FE_OFN8_FE_DBTN1_n502),
	.C2(state[50]),
	.ZN(n563));
   INV_X1 U840 (.A(n563),
	.ZN(n255));
   AOI222_X1 U841 (.A1(FE_OFN2_n581),
	.A2(pt[51]),
	.B1(FE_OFN6_FE_DBTN0_n560),
	.B2(perm_state[51]),
	.C1(FE_OFN8_FE_DBTN1_n502),
	.C2(state[51]),
	.ZN(n564));
   INV_X1 U842 (.A(n564),
	.ZN(n254));
   AOI222_X1 U843 (.A1(FE_OFN3_n581),
	.A2(pt[52]),
	.B1(FE_OFN5_FE_DBTN0_n560),
	.B2(perm_state[52]),
	.C1(FE_DBTN1_n502),
	.C2(state[52]),
	.ZN(n565));
   INV_X1 U844 (.A(n565),
	.ZN(n253));
   AOI222_X1 U845 (.A1(FE_OFN3_n581),
	.A2(pt[53]),
	.B1(FE_OFN5_FE_DBTN0_n560),
	.B2(perm_state[53]),
	.C1(FE_DBTN1_n502),
	.C2(state[53]),
	.ZN(n566));
   INV_X1 U846 (.A(n566),
	.ZN(n252));
   AOI222_X1 U847 (.A1(FE_OFN582_n),
	.A2(pt[54]),
	.B1(FE_OFN5_FE_DBTN0_n560),
	.B2(perm_state[54]),
	.C1(FE_DBTN1_n502),
	.C2(state[54]),
	.ZN(n567));
   INV_X1 U848 (.A(n567),
	.ZN(n251));
   AOI222_X1 U849 (.A1(FE_OFN2_n581),
	.A2(pt[55]),
	.B1(FE_OFN6_FE_DBTN0_n560),
	.B2(perm_state[55]),
	.C1(FE_OFN8_FE_DBTN1_n502),
	.C2(state[55]),
	.ZN(n568));
   INV_X1 U850 (.A(n568),
	.ZN(n250));
   AOI222_X1 U851 (.A1(FE_OFN3_n581),
	.A2(pt[56]),
	.B1(FE_OFN5_FE_DBTN0_n560),
	.B2(perm_state[56]),
	.C1(FE_DBTN1_n502),
	.C2(state[56]),
	.ZN(n569));
   INV_X1 U852 (.A(n569),
	.ZN(n249));
   AOI222_X1 U853 (.A1(FE_OFN3_n581),
	.A2(pt[57]),
	.B1(FE_OFN5_FE_DBTN0_n560),
	.B2(perm_state[57]),
	.C1(FE_DBTN1_n502),
	.C2(state[57]),
	.ZN(n570));
   INV_X1 U854 (.A(n570),
	.ZN(n248));
   AOI222_X1 U855 (.A1(FE_OFN3_n581),
	.A2(pt[58]),
	.B1(FE_OFN5_FE_DBTN0_n560),
	.B2(perm_state[58]),
	.C1(FE_DBTN1_n502),
	.C2(state[58]),
	.ZN(n571));
   INV_X1 U856 (.A(n571),
	.ZN(n247));
   AOI222_X1 U857 (.A1(FE_OFN582_n),
	.A2(pt[59]),
	.B1(FE_OFN6_FE_DBTN0_n560),
	.B2(perm_state[59]),
	.C1(FE_OFN8_FE_DBTN1_n502),
	.C2(state[59]),
	.ZN(n572));
   AOI222_X1 U859 (.A1(FE_OFN2_n581),
	.A2(pt[60]),
	.B1(FE_OFN6_FE_DBTN0_n560),
	.B2(perm_state[60]),
	.C1(FE_OFN8_FE_DBTN1_n502),
	.C2(state[60]),
	.ZN(n574));
   INV_X1 U860 (.A(n574),
	.ZN(n245));
   AOI222_X1 U861 (.A1(FE_OFN2_n581),
	.A2(pt[61]),
	.B1(FE_OFN6_FE_DBTN0_n560),
	.B2(perm_state[61]),
	.C1(FE_DBTN1_n502),
	.C2(state[61]),
	.ZN(n575));
   INV_X1 U862 (.A(n575),
	.ZN(n244));
   AOI222_X1 U863 (.A1(FE_OFN582_n),
	.A2(pt[62]),
	.B1(FE_OFN5_FE_DBTN0_n560),
	.B2(perm_state[62]),
	.C1(FE_DBTN1_n502),
	.C2(state[62]),
	.ZN(n577));
   INV_X1 U864 (.A(n577),
	.ZN(n243));
   AOI222_X1 U865 (.A1(FE_OFN2_n581),
	.A2(pt[63]),
	.B1(FE_OFN6_FE_DBTN0_n560),
	.B2(perm_state[63]),
	.C1(FE_OFN8_FE_DBTN1_n502),
	.C2(state[63]),
	.ZN(n579));
   INV_X1 U866 (.A(n579),
	.ZN(n242));
   AOI22_X1 U867 (.A1(n581),
	.A2(key[15]),
	.B1(FE_DBTN1_n502),
	.B2(current_key[15]),
	.ZN(n584));
   OAI221_X1 U868 (.A(FE_OFN6_FE_DBTN0_n560),
	.B1(round[0]),
	.B2(current_key[34]),
	.C1(n393),
	.C2(n630),
	.ZN(n583));
   NAND2_X1 U869 (.A1(n584),
	.A2(n583),
	.ZN(n241));
   AOI21_X1 U870 (.A(n585),
	.B1(n586),
	.B2(valid),
	.ZN(n587));
   OR2_X1 U460 (.A1(FE_OFN5_FE_DBTN0_n560),
	.A2(FE_OFN3_n581),
	.ZN(n502));
   NAND2_X1 U462 (.A1(n413),
	.A2(n414),
	.ZN(n560));
   INV_X2 U532 (.A(n586),
	.ZN(n581));
   NAND2_X1 U533 (.A1(n592),
	.A2(load),
	.ZN(n586));
   SDFFR_X1 valid_reg (.D(TIE_CELL_LTIEHI_NET),
	.RN(reset_n),
	.SE(n587),
	.SI(TIE_CELL_LTIELO_NET),
	.CK(CTS_19),
	.Q(valid));
   SDFFR_X1 state_reg_59_ (.D(TIE_CELL_LTIEHI_NET),
	.RN(FE_OFN0_reset_n),
	.SE(n572),
	.SI(TIE_CELL_LTIELO_NET),
	.CK(CTS_20),
	.Q(state[59]));
   SDFFR_X1 fsm_state_reg_1_ (.D(TIE_CELL_LTIEHI_NET),
	.RN(reset_n),
	.SE(n396),
	.SI(TIE_CELL_LTIELO_NET),
	.CK(CTS_19),
	.Q(fsm_state[1]));
   SDFFR_X1 state_reg_46_ (.D(TIE_CELL_LTIEHI_NET),
	.RN(FE_OFN0_reset_n),
	.SE(n555),
	.SI(TIE_CELL_LTIELO_NET),
	.CK(CTS_20),
	.Q(state[46]));
   OAI33_X1 U557 (.A1(TIE_CELL_LTIELO_NET),
	.A2(n406),
	.A3(n590),
	.B1(round[2]),
	.B2(n405),
	.B3(n404),
	.ZN(n387));
   OAI221_X1 \s1/U20  (.A(\s1/n10 ),
	.B1(\s1/n14 ),
	.B2(\s1/n13 ),
	.C1(\s1/n12 ),
	.C2(\s1/n11 ),
	.ZN(perm_state[32]));
   OAI221_X1 \s1/U19  (.A(ct[2]),
	.B1(\s1/n14 ),
	.B2(ct[0]),
	.C1(\s1/n14 ),
	.C2(\s1/n9 ),
	.ZN(\s1/n10 ));
   INV_X1 \s1/U18  (.A(\s1/n14 ),
	.ZN(\s1/n12 ));
   OAI21_X1 \s1/U17  (.A(\s1/n7 ),
	.B1(\s1/n8 ),
	.B2(\s1/n11 ),
	.ZN(\s1/n13 ));
   AOI22_X1 \s1/U16  (.A1(ct[0]),
	.A2(\s1/n6 ),
	.B1(\s1/n5 ),
	.B2(\s1/n11 ),
	.ZN(perm_state[48]));
   INV_X1 \s1/U15  (.A(\s1/n4 ),
	.ZN(\s1/n5 ));
   AOI22_X1 \s1/U14  (.A1(ct[0]),
	.A2(\s1/n4 ),
	.B1(\s1/n6 ),
	.B2(\s1/n11 ),
	.ZN(perm_state[16]));
   AOI21_X1 \s1/U13  (.A(\s1/n9 ),
	.B1(ct[3]),
	.B2(\s1/n7 ),
	.ZN(\s1/n6 ));
   AOI221_X1 \s1/U12  (.A(\s1/n14 ),
	.B1(ct[3]),
	.B2(ct[2]),
	.C1(\s1/n9 ),
	.C2(\s1/n7 ),
	.ZN(\s1/n4 ));
   NOR2_X1 \s1/U11  (.A1(ct[1]),
	.A2(\s1/n3 ),
	.ZN(\s1/n14 ));
   INV_X1 \s1/U10  (.A(ct[2]),
	.ZN(\s1/n7 ));
   NOR2_X1 \s1/U9  (.A1(ct[3]),
	.A2(\s1/n8 ),
	.ZN(\s1/n9 ));
   XNOR2_X1 \s1/U8  (.A(\s1/n2 ),
	.B(\s1/n1 ),
	.ZN(perm_state[0]));
   AOI22_X1 \s1/U7  (.A1(ct[0]),
	.A2(ct[3]),
	.B1(\s1/n3 ),
	.B2(\s1/n11 ),
	.ZN(\s1/n1 ));
   INV_X1 \s1/U6  (.A(ct[0]),
	.ZN(\s1/n11 ));
   INV_X1 \s1/U5  (.A(ct[3]),
	.ZN(\s1/n3 ));
   NAND2_X1 \s1/U4  (.A1(\s1/n8 ),
	.A2(ct[2]),
	.ZN(\s1/n2 ));
   INV_X1 \s1/U3  (.A(ct[1]),
	.ZN(\s1/n8 ));
   OAI221_X1 \s2/U20  (.A(\s2/n10 ),
	.B1(\s2/n14 ),
	.B2(\s2/n13 ),
	.C1(\s2/n12 ),
	.C2(\s2/n11 ),
	.ZN(perm_state[33]));
   OAI221_X1 \s2/U19  (.A(ct[6]),
	.B1(\s2/n14 ),
	.B2(ct[4]),
	.C1(\s2/n14 ),
	.C2(\s2/n9 ),
	.ZN(\s2/n10 ));
   INV_X1 \s2/U18  (.A(\s2/n14 ),
	.ZN(\s2/n12 ));
   OAI21_X1 \s2/U17  (.A(\s2/n7 ),
	.B1(\s2/n8 ),
	.B2(\s2/n11 ),
	.ZN(\s2/n13 ));
   AOI22_X1 \s2/U16  (.A1(ct[4]),
	.A2(\s2/n6 ),
	.B1(\s2/n5 ),
	.B2(\s2/n11 ),
	.ZN(perm_state[49]));
   INV_X1 \s2/U15  (.A(\s2/n4 ),
	.ZN(\s2/n5 ));
   AOI22_X1 \s2/U14  (.A1(ct[4]),
	.A2(\s2/n4 ),
	.B1(\s2/n6 ),
	.B2(\s2/n11 ),
	.ZN(perm_state[17]));
   AOI21_X1 \s2/U13  (.A(\s2/n9 ),
	.B1(ct[7]),
	.B2(\s2/n7 ),
	.ZN(\s2/n6 ));
   AOI221_X1 \s2/U12  (.A(\s2/n14 ),
	.B1(ct[7]),
	.B2(ct[6]),
	.C1(\s2/n9 ),
	.C2(\s2/n7 ),
	.ZN(\s2/n4 ));
   NOR2_X1 \s2/U11  (.A1(ct[5]),
	.A2(\s2/n3 ),
	.ZN(\s2/n14 ));
   INV_X1 \s2/U10  (.A(ct[6]),
	.ZN(\s2/n7 ));
   NOR2_X1 \s2/U9  (.A1(ct[7]),
	.A2(\s2/n8 ),
	.ZN(\s2/n9 ));
   XNOR2_X1 \s2/U8  (.A(\s2/n2 ),
	.B(\s2/n1 ),
	.ZN(perm_state[1]));
   AOI22_X1 \s2/U7  (.A1(ct[4]),
	.A2(ct[7]),
	.B1(\s2/n3 ),
	.B2(\s2/n11 ),
	.ZN(\s2/n1 ));
   INV_X1 \s2/U6  (.A(ct[4]),
	.ZN(\s2/n11 ));
   INV_X1 \s2/U5  (.A(ct[7]),
	.ZN(\s2/n3 ));
   NAND2_X1 \s2/U4  (.A1(\s2/n8 ),
	.A2(ct[6]),
	.ZN(\s2/n2 ));
   INV_X1 \s2/U3  (.A(ct[5]),
	.ZN(\s2/n8 ));
   OAI221_X1 \s3/U20  (.A(\s3/n10 ),
	.B1(\s3/n14 ),
	.B2(\s3/n13 ),
	.C1(\s3/n12 ),
	.C2(\s3/n11 ),
	.ZN(perm_state[34]));
   OAI221_X1 \s3/U19  (.A(ct[10]),
	.B1(\s3/n14 ),
	.B2(ct[8]),
	.C1(\s3/n14 ),
	.C2(\s3/n9 ),
	.ZN(\s3/n10 ));
   INV_X1 \s3/U18  (.A(\s3/n14 ),
	.ZN(\s3/n12 ));
   OAI21_X1 \s3/U17  (.A(\s3/n7 ),
	.B1(\s3/n8 ),
	.B2(\s3/n11 ),
	.ZN(\s3/n13 ));
   AOI22_X1 \s3/U16  (.A1(ct[8]),
	.A2(\s3/n6 ),
	.B1(\s3/n5 ),
	.B2(\s3/n11 ),
	.ZN(perm_state[50]));
   INV_X1 \s3/U15  (.A(\s3/n4 ),
	.ZN(\s3/n5 ));
   AOI22_X1 \s3/U14  (.A1(ct[8]),
	.A2(\s3/n4 ),
	.B1(\s3/n6 ),
	.B2(\s3/n11 ),
	.ZN(perm_state[18]));
   AOI21_X1 \s3/U13  (.A(\s3/n9 ),
	.B1(ct[11]),
	.B2(\s3/n7 ),
	.ZN(\s3/n6 ));
   AOI221_X1 \s3/U12  (.A(\s3/n14 ),
	.B1(ct[11]),
	.B2(ct[10]),
	.C1(\s3/n9 ),
	.C2(\s3/n7 ),
	.ZN(\s3/n4 ));
   NOR2_X1 \s3/U11  (.A1(ct[9]),
	.A2(\s3/n3 ),
	.ZN(\s3/n14 ));
   INV_X1 \s3/U10  (.A(ct[10]),
	.ZN(\s3/n7 ));
   NOR2_X1 \s3/U9  (.A1(ct[11]),
	.A2(\s3/n8 ),
	.ZN(\s3/n9 ));
   XNOR2_X1 \s3/U8  (.A(\s3/n2 ),
	.B(\s3/n1 ),
	.ZN(perm_state[2]));
   AOI22_X1 \s3/U7  (.A1(ct[8]),
	.A2(ct[11]),
	.B1(\s3/n3 ),
	.B2(\s3/n11 ),
	.ZN(\s3/n1 ));
   INV_X1 \s3/U6  (.A(ct[8]),
	.ZN(\s3/n11 ));
   INV_X1 \s3/U5  (.A(ct[11]),
	.ZN(\s3/n3 ));
   NAND2_X1 \s3/U4  (.A1(\s3/n8 ),
	.A2(ct[10]),
	.ZN(\s3/n2 ));
   INV_X1 \s3/U3  (.A(ct[9]),
	.ZN(\s3/n8 ));
   OAI221_X1 \s4/U20  (.A(\s4/n10 ),
	.B1(\s4/n14 ),
	.B2(\s4/n13 ),
	.C1(\s4/n12 ),
	.C2(\s4/n11 ),
	.ZN(perm_state[35]));
   OAI221_X1 \s4/U19  (.A(ct[14]),
	.B1(\s4/n14 ),
	.B2(ct[12]),
	.C1(\s4/n14 ),
	.C2(\s4/n9 ),
	.ZN(\s4/n10 ));
   INV_X1 \s4/U18  (.A(\s4/n14 ),
	.ZN(\s4/n12 ));
   OAI21_X1 \s4/U17  (.A(\s4/n7 ),
	.B1(\s4/n8 ),
	.B2(\s4/n11 ),
	.ZN(\s4/n13 ));
   AOI22_X1 \s4/U16  (.A1(ct[12]),
	.A2(\s4/n6 ),
	.B1(\s4/n5 ),
	.B2(\s4/n11 ),
	.ZN(perm_state[51]));
   INV_X1 \s4/U15  (.A(\s4/n4 ),
	.ZN(\s4/n5 ));
   AOI22_X1 \s4/U14  (.A1(ct[12]),
	.A2(\s4/n4 ),
	.B1(\s4/n6 ),
	.B2(\s4/n11 ),
	.ZN(perm_state[19]));
   AOI21_X1 \s4/U13  (.A(\s4/n9 ),
	.B1(ct[15]),
	.B2(\s4/n7 ),
	.ZN(\s4/n6 ));
   AOI221_X1 \s4/U12  (.A(\s4/n14 ),
	.B1(ct[15]),
	.B2(ct[14]),
	.C1(\s4/n9 ),
	.C2(\s4/n7 ),
	.ZN(\s4/n4 ));
   NOR2_X1 \s4/U11  (.A1(ct[13]),
	.A2(\s4/n3 ),
	.ZN(\s4/n14 ));
   INV_X1 \s4/U10  (.A(ct[14]),
	.ZN(\s4/n7 ));
   NOR2_X1 \s4/U9  (.A1(ct[15]),
	.A2(\s4/n8 ),
	.ZN(\s4/n9 ));
   XNOR2_X1 \s4/U8  (.A(\s4/n2 ),
	.B(\s4/n1 ),
	.ZN(perm_state[3]));
   AOI22_X1 \s4/U7  (.A1(ct[12]),
	.A2(ct[15]),
	.B1(\s4/n3 ),
	.B2(\s4/n11 ),
	.ZN(\s4/n1 ));
   INV_X1 \s4/U6  (.A(ct[12]),
	.ZN(\s4/n11 ));
   INV_X1 \s4/U5  (.A(ct[15]),
	.ZN(\s4/n3 ));
   NAND2_X1 \s4/U4  (.A1(\s4/n8 ),
	.A2(ct[14]),
	.ZN(\s4/n2 ));
   INV_X1 \s4/U3  (.A(ct[13]),
	.ZN(\s4/n8 ));
   OAI221_X1 \s5/U20  (.A(\s5/n10 ),
	.B1(\s5/n14 ),
	.B2(\s5/n13 ),
	.C1(\s5/n12 ),
	.C2(\s5/n11 ),
	.ZN(perm_state[36]));
   OAI221_X1 \s5/U19  (.A(ct[18]),
	.B1(\s5/n14 ),
	.B2(ct[16]),
	.C1(\s5/n14 ),
	.C2(\s5/n9 ),
	.ZN(\s5/n10 ));
   INV_X1 \s5/U18  (.A(\s5/n14 ),
	.ZN(\s5/n12 ));
   OAI21_X1 \s5/U17  (.A(\s5/n7 ),
	.B1(\s5/n8 ),
	.B2(\s5/n11 ),
	.ZN(\s5/n13 ));
   AOI22_X1 \s5/U16  (.A1(ct[16]),
	.A2(\s5/n6 ),
	.B1(\s5/n5 ),
	.B2(\s5/n11 ),
	.ZN(perm_state[52]));
   INV_X1 \s5/U15  (.A(\s5/n4 ),
	.ZN(\s5/n5 ));
   AOI22_X1 \s5/U14  (.A1(ct[16]),
	.A2(\s5/n4 ),
	.B1(\s5/n6 ),
	.B2(\s5/n11 ),
	.ZN(perm_state[20]));
   AOI21_X1 \s5/U13  (.A(\s5/n9 ),
	.B1(ct[19]),
	.B2(\s5/n7 ),
	.ZN(\s5/n6 ));
   AOI221_X1 \s5/U12  (.A(\s5/n14 ),
	.B1(ct[19]),
	.B2(ct[18]),
	.C1(\s5/n9 ),
	.C2(\s5/n7 ),
	.ZN(\s5/n4 ));
   NOR2_X1 \s5/U11  (.A1(ct[17]),
	.A2(\s5/n3 ),
	.ZN(\s5/n14 ));
   INV_X1 \s5/U10  (.A(ct[18]),
	.ZN(\s5/n7 ));
   NOR2_X1 \s5/U9  (.A1(ct[19]),
	.A2(\s5/n8 ),
	.ZN(\s5/n9 ));
   XNOR2_X1 \s5/U8  (.A(\s5/n2 ),
	.B(\s5/n1 ),
	.ZN(perm_state[4]));
   AOI22_X1 \s5/U7  (.A1(ct[16]),
	.A2(ct[19]),
	.B1(\s5/n3 ),
	.B2(\s5/n11 ),
	.ZN(\s5/n1 ));
   INV_X1 \s5/U6  (.A(ct[16]),
	.ZN(\s5/n11 ));
   INV_X1 \s5/U5  (.A(ct[19]),
	.ZN(\s5/n3 ));
   NAND2_X1 \s5/U4  (.A1(\s5/n8 ),
	.A2(ct[18]),
	.ZN(\s5/n2 ));
   INV_X1 \s5/U3  (.A(ct[17]),
	.ZN(\s5/n8 ));
   OAI221_X1 \s6/U20  (.A(\s6/n10 ),
	.B1(\s6/n14 ),
	.B2(\s6/n13 ),
	.C1(\s6/n12 ),
	.C2(\s6/n11 ),
	.ZN(perm_state[37]));
   OAI221_X1 \s6/U19  (.A(ct[22]),
	.B1(\s6/n14 ),
	.B2(ct[20]),
	.C1(\s6/n14 ),
	.C2(\s6/n9 ),
	.ZN(\s6/n10 ));
   INV_X1 \s6/U18  (.A(\s6/n14 ),
	.ZN(\s6/n12 ));
   OAI21_X1 \s6/U17  (.A(\s6/n7 ),
	.B1(\s6/n8 ),
	.B2(\s6/n11 ),
	.ZN(\s6/n13 ));
   AOI22_X1 \s6/U16  (.A1(ct[20]),
	.A2(\s6/n6 ),
	.B1(\s6/n5 ),
	.B2(\s6/n11 ),
	.ZN(perm_state[53]));
   INV_X1 \s6/U15  (.A(\s6/n4 ),
	.ZN(\s6/n5 ));
   AOI22_X1 \s6/U14  (.A1(ct[20]),
	.A2(\s6/n4 ),
	.B1(\s6/n6 ),
	.B2(\s6/n11 ),
	.ZN(perm_state[21]));
   AOI21_X1 \s6/U13  (.A(\s6/n9 ),
	.B1(ct[23]),
	.B2(\s6/n7 ),
	.ZN(\s6/n6 ));
   AOI221_X1 \s6/U12  (.A(\s6/n14 ),
	.B1(ct[23]),
	.B2(ct[22]),
	.C1(\s6/n9 ),
	.C2(\s6/n7 ),
	.ZN(\s6/n4 ));
   NOR2_X1 \s6/U11  (.A1(ct[21]),
	.A2(\s6/n3 ),
	.ZN(\s6/n14 ));
   INV_X1 \s6/U10  (.A(ct[22]),
	.ZN(\s6/n7 ));
   NOR2_X1 \s6/U9  (.A1(ct[23]),
	.A2(\s6/n8 ),
	.ZN(\s6/n9 ));
   XNOR2_X1 \s6/U8  (.A(\s6/n2 ),
	.B(\s6/n1 ),
	.ZN(perm_state[5]));
   AOI22_X1 \s6/U7  (.A1(ct[20]),
	.A2(ct[23]),
	.B1(\s6/n3 ),
	.B2(\s6/n11 ),
	.ZN(\s6/n1 ));
   INV_X1 \s6/U6  (.A(ct[20]),
	.ZN(\s6/n11 ));
   INV_X1 \s6/U5  (.A(ct[23]),
	.ZN(\s6/n3 ));
   NAND2_X1 \s6/U4  (.A1(\s6/n8 ),
	.A2(ct[22]),
	.ZN(\s6/n2 ));
   INV_X1 \s6/U3  (.A(ct[21]),
	.ZN(\s6/n8 ));
   OAI221_X1 \s7/U20  (.A(\s7/n10 ),
	.B1(\s7/n14 ),
	.B2(\s7/n13 ),
	.C1(\s7/n12 ),
	.C2(\s7/n11 ),
	.ZN(perm_state[38]));
   OAI221_X1 \s7/U19  (.A(ct[26]),
	.B1(\s7/n14 ),
	.B2(ct[24]),
	.C1(\s7/n14 ),
	.C2(\s7/n9 ),
	.ZN(\s7/n10 ));
   INV_X1 \s7/U18  (.A(\s7/n14 ),
	.ZN(\s7/n12 ));
   OAI21_X1 \s7/U17  (.A(\s7/n7 ),
	.B1(\s7/n8 ),
	.B2(\s7/n11 ),
	.ZN(\s7/n13 ));
   AOI22_X1 \s7/U16  (.A1(ct[24]),
	.A2(\s7/n6 ),
	.B1(\s7/n5 ),
	.B2(\s7/n11 ),
	.ZN(perm_state[54]));
   INV_X1 \s7/U15  (.A(\s7/n4 ),
	.ZN(\s7/n5 ));
   AOI22_X1 \s7/U14  (.A1(ct[24]),
	.A2(\s7/n4 ),
	.B1(\s7/n6 ),
	.B2(\s7/n11 ),
	.ZN(perm_state[22]));
   AOI21_X1 \s7/U13  (.A(\s7/n9 ),
	.B1(ct[27]),
	.B2(\s7/n7 ),
	.ZN(\s7/n6 ));
   AOI221_X1 \s7/U12  (.A(\s7/n14 ),
	.B1(ct[27]),
	.B2(ct[26]),
	.C1(\s7/n9 ),
	.C2(\s7/n7 ),
	.ZN(\s7/n4 ));
   NOR2_X1 \s7/U11  (.A1(ct[25]),
	.A2(\s7/n3 ),
	.ZN(\s7/n14 ));
   INV_X1 \s7/U10  (.A(ct[26]),
	.ZN(\s7/n7 ));
   NOR2_X1 \s7/U9  (.A1(ct[27]),
	.A2(\s7/n8 ),
	.ZN(\s7/n9 ));
   XNOR2_X1 \s7/U8  (.A(\s7/n2 ),
	.B(\s7/n1 ),
	.ZN(perm_state[6]));
   AOI22_X1 \s7/U7  (.A1(ct[24]),
	.A2(ct[27]),
	.B1(\s7/n3 ),
	.B2(\s7/n11 ),
	.ZN(\s7/n1 ));
   INV_X1 \s7/U6  (.A(ct[24]),
	.ZN(\s7/n11 ));
   INV_X1 \s7/U5  (.A(ct[27]),
	.ZN(\s7/n3 ));
   NAND2_X1 \s7/U4  (.A1(\s7/n8 ),
	.A2(ct[26]),
	.ZN(\s7/n2 ));
   INV_X1 \s7/U3  (.A(ct[25]),
	.ZN(\s7/n8 ));
   OAI221_X1 \s8/U20  (.A(\s8/n10 ),
	.B1(\s8/n14 ),
	.B2(\s8/n13 ),
	.C1(\s8/n12 ),
	.C2(\s8/n11 ),
	.ZN(perm_state[39]));
   OAI221_X1 \s8/U19  (.A(ct[30]),
	.B1(\s8/n14 ),
	.B2(ct[28]),
	.C1(\s8/n14 ),
	.C2(\s8/n9 ),
	.ZN(\s8/n10 ));
   INV_X1 \s8/U18  (.A(\s8/n14 ),
	.ZN(\s8/n12 ));
   OAI21_X1 \s8/U17  (.A(\s8/n7 ),
	.B1(\s8/n8 ),
	.B2(\s8/n11 ),
	.ZN(\s8/n13 ));
   AOI22_X1 \s8/U16  (.A1(ct[28]),
	.A2(\s8/n6 ),
	.B1(\s8/n5 ),
	.B2(\s8/n11 ),
	.ZN(perm_state[55]));
   INV_X1 \s8/U15  (.A(\s8/n4 ),
	.ZN(\s8/n5 ));
   AOI22_X1 \s8/U14  (.A1(ct[28]),
	.A2(\s8/n4 ),
	.B1(\s8/n6 ),
	.B2(\s8/n11 ),
	.ZN(perm_state[23]));
   AOI21_X1 \s8/U13  (.A(\s8/n9 ),
	.B1(ct[31]),
	.B2(\s8/n7 ),
	.ZN(\s8/n6 ));
   AOI221_X1 \s8/U12  (.A(\s8/n14 ),
	.B1(ct[31]),
	.B2(ct[30]),
	.C1(\s8/n9 ),
	.C2(\s8/n7 ),
	.ZN(\s8/n4 ));
   NOR2_X1 \s8/U11  (.A1(ct[29]),
	.A2(\s8/n3 ),
	.ZN(\s8/n14 ));
   INV_X1 \s8/U10  (.A(ct[30]),
	.ZN(\s8/n7 ));
   NOR2_X1 \s8/U9  (.A1(ct[31]),
	.A2(\s8/n8 ),
	.ZN(\s8/n9 ));
   XNOR2_X1 \s8/U8  (.A(\s8/n2 ),
	.B(\s8/n1 ),
	.ZN(perm_state[7]));
   AOI22_X1 \s8/U7  (.A1(ct[28]),
	.A2(ct[31]),
	.B1(\s8/n3 ),
	.B2(\s8/n11 ),
	.ZN(\s8/n1 ));
   INV_X1 \s8/U6  (.A(ct[28]),
	.ZN(\s8/n11 ));
   INV_X1 \s8/U5  (.A(ct[31]),
	.ZN(\s8/n3 ));
   NAND2_X1 \s8/U4  (.A1(\s8/n8 ),
	.A2(ct[30]),
	.ZN(\s8/n2 ));
   INV_X1 \s8/U3  (.A(ct[29]),
	.ZN(\s8/n8 ));
   OAI221_X1 \s9/U20  (.A(\s9/n10 ),
	.B1(\s9/n14 ),
	.B2(\s9/n13 ),
	.C1(\s9/n12 ),
	.C2(\s9/n11 ),
	.ZN(perm_state[40]));
   OAI221_X1 \s9/U19  (.A(ct[34]),
	.B1(\s9/n14 ),
	.B2(ct[32]),
	.C1(\s9/n14 ),
	.C2(\s9/n9 ),
	.ZN(\s9/n10 ));
   INV_X1 \s9/U18  (.A(\s9/n14 ),
	.ZN(\s9/n12 ));
   OAI21_X1 \s9/U17  (.A(\s9/n7 ),
	.B1(\s9/n8 ),
	.B2(\s9/n11 ),
	.ZN(\s9/n13 ));
   AOI22_X1 \s9/U16  (.A1(ct[32]),
	.A2(\s9/n6 ),
	.B1(\s9/n5 ),
	.B2(\s9/n11 ),
	.ZN(perm_state[56]));
   INV_X1 \s9/U15  (.A(\s9/n4 ),
	.ZN(\s9/n5 ));
   AOI22_X1 \s9/U14  (.A1(ct[32]),
	.A2(\s9/n4 ),
	.B1(\s9/n6 ),
	.B2(\s9/n11 ),
	.ZN(perm_state[24]));
   AOI21_X1 \s9/U13  (.A(\s9/n9 ),
	.B1(ct[35]),
	.B2(\s9/n7 ),
	.ZN(\s9/n6 ));
   AOI221_X1 \s9/U12  (.A(\s9/n14 ),
	.B1(ct[35]),
	.B2(ct[34]),
	.C1(\s9/n9 ),
	.C2(\s9/n7 ),
	.ZN(\s9/n4 ));
   NOR2_X1 \s9/U11  (.A1(ct[33]),
	.A2(\s9/n3 ),
	.ZN(\s9/n14 ));
   INV_X1 \s9/U10  (.A(ct[34]),
	.ZN(\s9/n7 ));
   NOR2_X1 \s9/U9  (.A1(ct[35]),
	.A2(\s9/n8 ),
	.ZN(\s9/n9 ));
   XNOR2_X1 \s9/U8  (.A(\s9/n2 ),
	.B(\s9/n1 ),
	.ZN(perm_state[8]));
   AOI22_X1 \s9/U7  (.A1(ct[32]),
	.A2(ct[35]),
	.B1(\s9/n3 ),
	.B2(\s9/n11 ),
	.ZN(\s9/n1 ));
   INV_X1 \s9/U6  (.A(ct[32]),
	.ZN(\s9/n11 ));
   INV_X1 \s9/U5  (.A(ct[35]),
	.ZN(\s9/n3 ));
   NAND2_X1 \s9/U4  (.A1(\s9/n8 ),
	.A2(ct[34]),
	.ZN(\s9/n2 ));
   INV_X1 \s9/U3  (.A(ct[33]),
	.ZN(\s9/n8 ));
   OAI221_X1 \s10/U20  (.A(\s10/n10 ),
	.B1(\s10/n14 ),
	.B2(\s10/n13 ),
	.C1(\s10/n12 ),
	.C2(\s10/n11 ),
	.ZN(perm_state[41]));
   OAI221_X1 \s10/U19  (.A(ct[38]),
	.B1(\s10/n14 ),
	.B2(ct[36]),
	.C1(\s10/n14 ),
	.C2(\s10/n9 ),
	.ZN(\s10/n10 ));
   INV_X1 \s10/U18  (.A(\s10/n14 ),
	.ZN(\s10/n12 ));
   OAI21_X1 \s10/U17  (.A(\s10/n7 ),
	.B1(\s10/n8 ),
	.B2(\s10/n11 ),
	.ZN(\s10/n13 ));
   AOI22_X1 \s10/U16  (.A1(ct[36]),
	.A2(\s10/n6 ),
	.B1(\s10/n5 ),
	.B2(\s10/n11 ),
	.ZN(perm_state[57]));
   INV_X1 \s10/U15  (.A(\s10/n4 ),
	.ZN(\s10/n5 ));
   AOI22_X1 \s10/U14  (.A1(ct[36]),
	.A2(\s10/n4 ),
	.B1(\s10/n6 ),
	.B2(\s10/n11 ),
	.ZN(perm_state[25]));
   AOI21_X1 \s10/U13  (.A(\s10/n9 ),
	.B1(ct[39]),
	.B2(\s10/n7 ),
	.ZN(\s10/n6 ));
   AOI221_X1 \s10/U12  (.A(\s10/n14 ),
	.B1(ct[39]),
	.B2(ct[38]),
	.C1(\s10/n9 ),
	.C2(\s10/n7 ),
	.ZN(\s10/n4 ));
   NOR2_X1 \s10/U11  (.A1(ct[37]),
	.A2(\s10/n3 ),
	.ZN(\s10/n14 ));
   INV_X1 \s10/U10  (.A(ct[38]),
	.ZN(\s10/n7 ));
   NOR2_X1 \s10/U9  (.A1(ct[39]),
	.A2(\s10/n8 ),
	.ZN(\s10/n9 ));
   XNOR2_X1 \s10/U8  (.A(\s10/n2 ),
	.B(\s10/n1 ),
	.ZN(perm_state[9]));
   AOI22_X1 \s10/U7  (.A1(ct[36]),
	.A2(ct[39]),
	.B1(\s10/n3 ),
	.B2(\s10/n11 ),
	.ZN(\s10/n1 ));
   INV_X1 \s10/U6  (.A(ct[36]),
	.ZN(\s10/n11 ));
   INV_X1 \s10/U5  (.A(ct[39]),
	.ZN(\s10/n3 ));
   NAND2_X1 \s10/U4  (.A1(\s10/n8 ),
	.A2(ct[38]),
	.ZN(\s10/n2 ));
   INV_X1 \s10/U3  (.A(ct[37]),
	.ZN(\s10/n8 ));
   OAI221_X1 \s11/U20  (.A(\s11/n10 ),
	.B1(\s11/n14 ),
	.B2(\s11/n13 ),
	.C1(\s11/n12 ),
	.C2(\s11/n11 ),
	.ZN(perm_state[42]));
   OAI221_X1 \s11/U19  (.A(ct[42]),
	.B1(\s11/n14 ),
	.B2(ct[40]),
	.C1(\s11/n14 ),
	.C2(\s11/n9 ),
	.ZN(\s11/n10 ));
   INV_X1 \s11/U18  (.A(\s11/n14 ),
	.ZN(\s11/n12 ));
   OAI21_X1 \s11/U17  (.A(\s11/n7 ),
	.B1(\s11/n8 ),
	.B2(\s11/n11 ),
	.ZN(\s11/n13 ));
   AOI22_X1 \s11/U16  (.A1(ct[40]),
	.A2(\s11/n6 ),
	.B1(\s11/n5 ),
	.B2(\s11/n11 ),
	.ZN(perm_state[58]));
   INV_X1 \s11/U15  (.A(\s11/n4 ),
	.ZN(\s11/n5 ));
   AOI22_X1 \s11/U14  (.A1(ct[40]),
	.A2(\s11/n4 ),
	.B1(\s11/n6 ),
	.B2(\s11/n11 ),
	.ZN(perm_state[26]));
   AOI21_X1 \s11/U13  (.A(\s11/n9 ),
	.B1(ct[43]),
	.B2(\s11/n7 ),
	.ZN(\s11/n6 ));
   AOI221_X1 \s11/U12  (.A(\s11/n14 ),
	.B1(ct[43]),
	.B2(ct[42]),
	.C1(\s11/n9 ),
	.C2(\s11/n7 ),
	.ZN(\s11/n4 ));
   NOR2_X1 \s11/U11  (.A1(ct[41]),
	.A2(\s11/n3 ),
	.ZN(\s11/n14 ));
   INV_X1 \s11/U10  (.A(ct[42]),
	.ZN(\s11/n7 ));
   NOR2_X1 \s11/U9  (.A1(ct[43]),
	.A2(\s11/n8 ),
	.ZN(\s11/n9 ));
   XNOR2_X1 \s11/U8  (.A(\s11/n2 ),
	.B(\s11/n1 ),
	.ZN(perm_state[10]));
   AOI22_X1 \s11/U7  (.A1(ct[40]),
	.A2(ct[43]),
	.B1(\s11/n3 ),
	.B2(\s11/n11 ),
	.ZN(\s11/n1 ));
   INV_X1 \s11/U6  (.A(ct[40]),
	.ZN(\s11/n11 ));
   INV_X1 \s11/U5  (.A(ct[43]),
	.ZN(\s11/n3 ));
   NAND2_X1 \s11/U4  (.A1(\s11/n8 ),
	.A2(ct[42]),
	.ZN(\s11/n2 ));
   INV_X1 \s11/U3  (.A(ct[41]),
	.ZN(\s11/n8 ));
   OAI221_X1 \s12/U20  (.A(\s12/n10 ),
	.B1(\s12/n14 ),
	.B2(\s12/n13 ),
	.C1(\s12/n12 ),
	.C2(\s12/n11 ),
	.ZN(perm_state[43]));
   OAI221_X1 \s12/U19  (.A(ct[46]),
	.B1(\s12/n14 ),
	.B2(ct[44]),
	.C1(\s12/n14 ),
	.C2(\s12/n9 ),
	.ZN(\s12/n10 ));
   INV_X1 \s12/U18  (.A(\s12/n14 ),
	.ZN(\s12/n12 ));
   OAI21_X1 \s12/U17  (.A(\s12/n7 ),
	.B1(\s12/n8 ),
	.B2(\s12/n11 ),
	.ZN(\s12/n13 ));
   AOI22_X1 \s12/U16  (.A1(ct[44]),
	.A2(\s12/n6 ),
	.B1(\s12/n5 ),
	.B2(\s12/n11 ),
	.ZN(perm_state[59]));
   INV_X1 \s12/U15  (.A(\s12/n4 ),
	.ZN(\s12/n5 ));
   AOI22_X1 \s12/U14  (.A1(ct[44]),
	.A2(\s12/n4 ),
	.B1(\s12/n6 ),
	.B2(\s12/n11 ),
	.ZN(perm_state[27]));
   AOI21_X1 \s12/U13  (.A(\s12/n9 ),
	.B1(ct[47]),
	.B2(\s12/n7 ),
	.ZN(\s12/n6 ));
   AOI221_X1 \s12/U12  (.A(\s12/n14 ),
	.B1(ct[47]),
	.B2(ct[46]),
	.C1(\s12/n9 ),
	.C2(\s12/n7 ),
	.ZN(\s12/n4 ));
   NOR2_X1 \s12/U11  (.A1(ct[45]),
	.A2(\s12/n3 ),
	.ZN(\s12/n14 ));
   INV_X1 \s12/U10  (.A(ct[46]),
	.ZN(\s12/n7 ));
   NOR2_X1 \s12/U9  (.A1(ct[47]),
	.A2(\s12/n8 ),
	.ZN(\s12/n9 ));
   XNOR2_X1 \s12/U8  (.A(\s12/n2 ),
	.B(\s12/n1 ),
	.ZN(perm_state[11]));
   AOI22_X1 \s12/U7  (.A1(ct[44]),
	.A2(ct[47]),
	.B1(\s12/n3 ),
	.B2(\s12/n11 ),
	.ZN(\s12/n1 ));
   INV_X1 \s12/U6  (.A(ct[44]),
	.ZN(\s12/n11 ));
   INV_X1 \s12/U5  (.A(ct[47]),
	.ZN(\s12/n3 ));
   NAND2_X1 \s12/U4  (.A1(\s12/n8 ),
	.A2(ct[46]),
	.ZN(\s12/n2 ));
   INV_X1 \s12/U3  (.A(ct[45]),
	.ZN(\s12/n8 ));
   OAI221_X1 \s13/U20  (.A(\s13/n10 ),
	.B1(\s13/n14 ),
	.B2(\s13/n13 ),
	.C1(\s13/n12 ),
	.C2(\s13/n11 ),
	.ZN(perm_state[44]));
   OAI221_X1 \s13/U19  (.A(ct[50]),
	.B1(\s13/n14 ),
	.B2(ct[48]),
	.C1(\s13/n14 ),
	.C2(\s13/n9 ),
	.ZN(\s13/n10 ));
   INV_X1 \s13/U18  (.A(\s13/n14 ),
	.ZN(\s13/n12 ));
   OAI21_X1 \s13/U17  (.A(\s13/n7 ),
	.B1(\s13/n8 ),
	.B2(\s13/n11 ),
	.ZN(\s13/n13 ));
   AOI22_X1 \s13/U16  (.A1(ct[48]),
	.A2(\s13/n6 ),
	.B1(\s13/n5 ),
	.B2(\s13/n11 ),
	.ZN(perm_state[60]));
   INV_X1 \s13/U15  (.A(\s13/n4 ),
	.ZN(\s13/n5 ));
   AOI22_X1 \s13/U14  (.A1(ct[48]),
	.A2(\s13/n4 ),
	.B1(\s13/n6 ),
	.B2(\s13/n11 ),
	.ZN(perm_state[28]));
   AOI21_X1 \s13/U13  (.A(\s13/n9 ),
	.B1(ct[51]),
	.B2(\s13/n7 ),
	.ZN(\s13/n6 ));
   AOI221_X1 \s13/U12  (.A(\s13/n14 ),
	.B1(ct[51]),
	.B2(ct[50]),
	.C1(\s13/n9 ),
	.C2(\s13/n7 ),
	.ZN(\s13/n4 ));
   NOR2_X1 \s13/U11  (.A1(ct[49]),
	.A2(\s13/n3 ),
	.ZN(\s13/n14 ));
   INV_X1 \s13/U10  (.A(ct[50]),
	.ZN(\s13/n7 ));
   NOR2_X1 \s13/U9  (.A1(ct[51]),
	.A2(\s13/n8 ),
	.ZN(\s13/n9 ));
   XNOR2_X1 \s13/U8  (.A(\s13/n2 ),
	.B(\s13/n1 ),
	.ZN(perm_state[12]));
   AOI22_X1 \s13/U7  (.A1(ct[48]),
	.A2(ct[51]),
	.B1(\s13/n3 ),
	.B2(\s13/n11 ),
	.ZN(\s13/n1 ));
   INV_X1 \s13/U6  (.A(ct[48]),
	.ZN(\s13/n11 ));
   INV_X1 \s13/U5  (.A(ct[51]),
	.ZN(\s13/n3 ));
   NAND2_X1 \s13/U4  (.A1(\s13/n8 ),
	.A2(ct[50]),
	.ZN(\s13/n2 ));
   INV_X1 \s13/U3  (.A(ct[49]),
	.ZN(\s13/n8 ));
   OAI221_X1 \s14/U20  (.A(\s14/n10 ),
	.B1(\s14/n14 ),
	.B2(\s14/n13 ),
	.C1(\s14/n12 ),
	.C2(\s14/n11 ),
	.ZN(perm_state[45]));
   OAI221_X1 \s14/U19  (.A(ct[54]),
	.B1(\s14/n14 ),
	.B2(ct[52]),
	.C1(\s14/n14 ),
	.C2(\s14/n9 ),
	.ZN(\s14/n10 ));
   INV_X1 \s14/U18  (.A(\s14/n14 ),
	.ZN(\s14/n12 ));
   OAI21_X1 \s14/U17  (.A(\s14/n7 ),
	.B1(\s14/n8 ),
	.B2(\s14/n11 ),
	.ZN(\s14/n13 ));
   AOI22_X1 \s14/U16  (.A1(ct[52]),
	.A2(\s14/n6 ),
	.B1(\s14/n5 ),
	.B2(\s14/n11 ),
	.ZN(perm_state[61]));
   INV_X1 \s14/U15  (.A(\s14/n4 ),
	.ZN(\s14/n5 ));
   AOI22_X1 \s14/U14  (.A1(ct[52]),
	.A2(\s14/n4 ),
	.B1(\s14/n6 ),
	.B2(\s14/n11 ),
	.ZN(perm_state[29]));
   AOI21_X1 \s14/U13  (.A(\s14/n9 ),
	.B1(ct[55]),
	.B2(\s14/n7 ),
	.ZN(\s14/n6 ));
   AOI221_X1 \s14/U12  (.A(\s14/n14 ),
	.B1(ct[55]),
	.B2(ct[54]),
	.C1(\s14/n9 ),
	.C2(\s14/n7 ),
	.ZN(\s14/n4 ));
   NOR2_X1 \s14/U11  (.A1(ct[53]),
	.A2(\s14/n3 ),
	.ZN(\s14/n14 ));
   INV_X1 \s14/U10  (.A(ct[54]),
	.ZN(\s14/n7 ));
   NOR2_X1 \s14/U9  (.A1(ct[55]),
	.A2(\s14/n8 ),
	.ZN(\s14/n9 ));
   XNOR2_X1 \s14/U8  (.A(\s14/n2 ),
	.B(\s14/n1 ),
	.ZN(perm_state[13]));
   AOI22_X1 \s14/U7  (.A1(ct[52]),
	.A2(ct[55]),
	.B1(\s14/n3 ),
	.B2(\s14/n11 ),
	.ZN(\s14/n1 ));
   INV_X1 \s14/U6  (.A(ct[52]),
	.ZN(\s14/n11 ));
   INV_X1 \s14/U5  (.A(ct[55]),
	.ZN(\s14/n3 ));
   NAND2_X1 \s14/U4  (.A1(\s14/n8 ),
	.A2(ct[54]),
	.ZN(\s14/n2 ));
   INV_X1 \s14/U3  (.A(ct[53]),
	.ZN(\s14/n8 ));
   OAI221_X1 \s15/U20  (.A(\s15/n10 ),
	.B1(\s15/n14 ),
	.B2(\s15/n13 ),
	.C1(\s15/n12 ),
	.C2(\s15/n11 ),
	.ZN(perm_state[46]));
   OAI221_X1 \s15/U19  (.A(ct[58]),
	.B1(\s15/n14 ),
	.B2(ct[56]),
	.C1(\s15/n14 ),
	.C2(\s15/n9 ),
	.ZN(\s15/n10 ));
   INV_X1 \s15/U18  (.A(\s15/n14 ),
	.ZN(\s15/n12 ));
   OAI21_X1 \s15/U17  (.A(\s15/n7 ),
	.B1(\s15/n8 ),
	.B2(\s15/n11 ),
	.ZN(\s15/n13 ));
   AOI22_X1 \s15/U16  (.A1(ct[56]),
	.A2(\s15/n6 ),
	.B1(\s15/n5 ),
	.B2(\s15/n11 ),
	.ZN(perm_state[62]));
   INV_X1 \s15/U15  (.A(\s15/n4 ),
	.ZN(\s15/n5 ));
   AOI22_X1 \s15/U14  (.A1(ct[56]),
	.A2(\s15/n4 ),
	.B1(\s15/n6 ),
	.B2(\s15/n11 ),
	.ZN(perm_state[30]));
   AOI21_X1 \s15/U13  (.A(\s15/n9 ),
	.B1(ct[59]),
	.B2(\s15/n7 ),
	.ZN(\s15/n6 ));
   AOI221_X1 \s15/U12  (.A(\s15/n14 ),
	.B1(ct[59]),
	.B2(ct[58]),
	.C1(\s15/n9 ),
	.C2(\s15/n7 ),
	.ZN(\s15/n4 ));
   NOR2_X1 \s15/U11  (.A1(ct[57]),
	.A2(\s15/n3 ),
	.ZN(\s15/n14 ));
   INV_X1 \s15/U10  (.A(ct[58]),
	.ZN(\s15/n7 ));
   NOR2_X1 \s15/U9  (.A1(ct[59]),
	.A2(\s15/n8 ),
	.ZN(\s15/n9 ));
   XNOR2_X1 \s15/U8  (.A(\s15/n2 ),
	.B(\s15/n1 ),
	.ZN(perm_state[14]));
   AOI22_X1 \s15/U7  (.A1(ct[56]),
	.A2(ct[59]),
	.B1(\s15/n3 ),
	.B2(\s15/n11 ),
	.ZN(\s15/n1 ));
   INV_X1 \s15/U6  (.A(ct[56]),
	.ZN(\s15/n11 ));
   INV_X1 \s15/U5  (.A(ct[59]),
	.ZN(\s15/n3 ));
   NAND2_X1 \s15/U4  (.A1(\s15/n8 ),
	.A2(ct[58]),
	.ZN(\s15/n2 ));
   INV_X1 \s15/U3  (.A(ct[57]),
	.ZN(\s15/n8 ));
   OAI221_X1 \s16/U20  (.A(\s16/n10 ),
	.B1(\s16/n14 ),
	.B2(\s16/n13 ),
	.C1(\s16/n12 ),
	.C2(\s16/n11 ),
	.ZN(perm_state[47]));
   OAI221_X1 \s16/U19  (.A(ct[62]),
	.B1(\s16/n14 ),
	.B2(ct[60]),
	.C1(\s16/n14 ),
	.C2(\s16/n9 ),
	.ZN(\s16/n10 ));
   INV_X1 \s16/U18  (.A(\s16/n14 ),
	.ZN(\s16/n12 ));
   OAI21_X1 \s16/U17  (.A(\s16/n7 ),
	.B1(\s16/n8 ),
	.B2(\s16/n11 ),
	.ZN(\s16/n13 ));
   AOI22_X1 \s16/U16  (.A1(ct[60]),
	.A2(\s16/n6 ),
	.B1(\s16/n5 ),
	.B2(\s16/n11 ),
	.ZN(perm_state[63]));
   INV_X1 \s16/U15  (.A(\s16/n4 ),
	.ZN(\s16/n5 ));
   AOI22_X1 \s16/U14  (.A1(ct[60]),
	.A2(\s16/n4 ),
	.B1(\s16/n6 ),
	.B2(\s16/n11 ),
	.ZN(perm_state[31]));
   AOI21_X1 \s16/U13  (.A(\s16/n9 ),
	.B1(ct[63]),
	.B2(\s16/n7 ),
	.ZN(\s16/n6 ));
   AOI221_X1 \s16/U12  (.A(\s16/n14 ),
	.B1(ct[63]),
	.B2(ct[62]),
	.C1(\s16/n9 ),
	.C2(\s16/n7 ),
	.ZN(\s16/n4 ));
   NOR2_X1 \s16/U11  (.A1(ct[61]),
	.A2(\s16/n3 ),
	.ZN(\s16/n14 ));
   INV_X1 \s16/U10  (.A(ct[62]),
	.ZN(\s16/n7 ));
   NOR2_X1 \s16/U9  (.A1(ct[63]),
	.A2(\s16/n8 ),
	.ZN(\s16/n9 ));
   XNOR2_X1 \s16/U8  (.A(\s16/n2 ),
	.B(\s16/n1 ),
	.ZN(perm_state[15]));
   AOI22_X1 \s16/U7  (.A1(ct[60]),
	.A2(ct[63]),
	.B1(\s16/n3 ),
	.B2(\s16/n11 ),
	.ZN(\s16/n1 ));
   INV_X1 \s16/U6  (.A(ct[60]),
	.ZN(\s16/n11 ));
   INV_X1 \s16/U5  (.A(ct[63]),
	.ZN(\s16/n3 ));
   NAND2_X1 \s16/U4  (.A1(\s16/n8 ),
	.A2(ct[62]),
	.ZN(\s16/n2 ));
   INV_X1 \s16/U3  (.A(ct[61]),
	.ZN(\s16/n8 ));
   OAI221_X1 \key_sbox/U20  (.A(\key_sbox/n10 ),
	.B1(\key_sbox/n14 ),
	.B2(\key_sbox/n13 ),
	.C1(\key_sbox/n12 ),
	.C2(\key_sbox/n11 ),
	.ZN(next_round_key_78));
   OAI221_X1 \key_sbox/U19  (.A(current_key[17]),
	.B1(\key_sbox/n14 ),
	.B2(current_key[15]),
	.C1(\key_sbox/n14 ),
	.C2(\key_sbox/n9 ),
	.ZN(\key_sbox/n10 ));
   INV_X1 \key_sbox/U18  (.A(\key_sbox/n14 ),
	.ZN(\key_sbox/n12 ));
   OAI21_X1 \key_sbox/U17  (.A(\key_sbox/n7 ),
	.B1(\key_sbox/n8 ),
	.B2(\key_sbox/n11 ),
	.ZN(\key_sbox/n13 ));
   AOI22_X1 \key_sbox/U16  (.A1(current_key[15]),
	.A2(\key_sbox/n6 ),
	.B1(\key_sbox/n5 ),
	.B2(\key_sbox/n11 ),
	.ZN(next_round_key_79));
   INV_X1 \key_sbox/U15  (.A(\key_sbox/n4 ),
	.ZN(\key_sbox/n5 ));
   AOI22_X1 \key_sbox/U14  (.A1(current_key[15]),
	.A2(\key_sbox/n4 ),
	.B1(\key_sbox/n6 ),
	.B2(\key_sbox/n11 ),
	.ZN(next_round_key_77));
   AOI21_X1 \key_sbox/U13  (.A(\key_sbox/n9 ),
	.B1(current_key[18]),
	.B2(\key_sbox/n7 ),
	.ZN(\key_sbox/n6 ));
   AOI221_X1 \key_sbox/U12  (.A(\key_sbox/n14 ),
	.B1(current_key[18]),
	.B2(current_key[17]),
	.C1(\key_sbox/n9 ),
	.C2(\key_sbox/n7 ),
	.ZN(\key_sbox/n4 ));
   NOR2_X1 \key_sbox/U11  (.A1(current_key[16]),
	.A2(\key_sbox/n3 ),
	.ZN(\key_sbox/n14 ));
   INV_X1 \key_sbox/U10  (.A(current_key[17]),
	.ZN(\key_sbox/n7 ));
   NOR2_X1 \key_sbox/U9  (.A1(current_key[18]),
	.A2(\key_sbox/n8 ),
	.ZN(\key_sbox/n9 ));
   XNOR2_X1 \key_sbox/U8  (.A(\key_sbox/n2 ),
	.B(\key_sbox/n1 ),
	.ZN(next_round_key_76));
   AOI22_X1 \key_sbox/U7  (.A1(current_key[15]),
	.A2(current_key[18]),
	.B1(\key_sbox/n3 ),
	.B2(\key_sbox/n11 ),
	.ZN(\key_sbox/n1 ));
   INV_X1 \key_sbox/U6  (.A(current_key[15]),
	.ZN(\key_sbox/n11 ));
   INV_X1 \key_sbox/U5  (.A(current_key[18]),
	.ZN(\key_sbox/n3 ));
   NAND2_X1 \key_sbox/U4  (.A1(\key_sbox/n8 ),
	.A2(current_key[17]),
	.ZN(\key_sbox/n2 ));
   INV_X1 \key_sbox/U3  (.A(current_key[16]),
	.ZN(\key_sbox/n8 ));
endmodule

